### ISSUE TITLE
Getting "403 - Authentication Credentials not provided" error when trying to view an unprotected resource

### ISSUE THREAD

**Issue by alysarnau** [sei-ec-remote/project-4-issues#101]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
When I try to view http://127.0.0.1:8000/resources/ , it gives me an error that I need to be authenticated. However, this is not a protected resource (so to speak) - anyone, logged in or not, should be able to see it. Can you assist?

### Post any code you think might be relevant (one fenced block per file)
Model:
```
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Resource(models.Model):
    resource_name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    image = models.CharField(max_length=150)
    sale_price = models.IntegerField(
        validators=[
            MaxValueValidator(2147483647),
            MinValueValidator(1),
        ]
    )
    link_to_wiki = models.CharField(max_length=150)
    def __str__(self):
        return self.resource_name
```
Views
```
from rest_framework.response import Response
from rest_framework import generics, status
from django.shortcuts import get_object_or_404
from django.middleware.csrf import get_token

from JunimoDatabaseApp.models import resource
from ..models.resource import Resource
from ..serializers import ResourceSerializer

# Create your views here.
class Resources(generics.ListCreateAPIView):
    serializer_class = ResourceSerializer
    def get(self, request):
        """Index request"""
        # Get all the resources:
        resources = Resource.objects.all()
        # Run the data through the serializer
        data = ResourceSerializer(resources, many=True).data
        return Response({ 'resources': data })


class ResourceDetail(generics.RetrieveUpdateDestroyAPIView):
    def get(self, request, pk):
        """Show request"""
        # Locate the resource to show
        resource = get_object_or_404(Resource, pk=pk)

        # Run the data through the serializer so it's formatted
        data = ResourceSerializer(resource).data
        return Response({ 'resource': data })
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

`{"detail":"Authentication credentials were not provided."}`

### What is your best guess as to the source of the problem?
There's something I'm not seeing that is marking it as protected

### What things have you already tried to solve the problem?
I looked into Kyle's solution and spoke with him at length and we troubleshot my code to see what I was missing.

**Paste a link to your repository here**
https://github.com/alysvolatile/my-junimo-api (on the 'resources' branch)

**Comment by kestler01** [comment]
Django defaults to authentication so we need to expressly tell it that we don't need to be signed in or own the resource 

```    
    authentication_classes = ()
    permission_classes = ()
```
