### ISSUE TITLE
Help with fetching from 3rd party api

### ISSUE THREAD

**Issue by christian-the-brewer** [sei-ec-remote/project-4-issues#105]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Figure how the correct way to fetch data from a 3rd party api via the backend

### Post any code you think might be relevant (one fenced block per file)
```js
router.get('/movies/:region', (req, res, next) => {
    //fetch top 20 most popular movies from API
    fetch(`https://api.themoviedb.org/3/discover/movie?api_key=58a92a2a4d225c25e73bb7fe5bfb8183&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&watch_region=${req.params.region}`)
        .then(handle404)
        .then((movies) =>
            res.status(201).json({ movies: movies.toObject() }))
        .catch(next)
})

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
so far we are  getting a 404, I dont have the up to date front end to copy and paste the error code

### What is your best guess as to the source of the problem?
I think that I am fetching incorrectly. I think I might have to take the res and change it to json in a .then before moving to other .then? like maybe: 
```js
router.get('/movies/:region', (req, res, next) => {
    //fetch top 20 most popular movies from API
    fetch(`https://api.themoviedb.org/3/discover/movie?api_key=58a92a2a4d225c25e73bb7fe5bfb8183&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&watch_region=${req.params.region}`)
         .then(res => res.json())
                 .then(handle404)
                  .then((movies) =>
                         res.status(201).json({ movies: movies.toObject() }))
        .catch(next)
})

```

### What things have you already tried to solve the problem?
I have tried googling but there are so many different ways to do it I am a bit confused

**Paste a link to your repository here**
https://github.com/christian-the-brewer/streamgenie-backend_api

**Comment by kestler01** [comment]
So, getting a 404 is great! fetch is working, we're just not finding the resource specified in the query string, 
Start by double checking your region variable (console.log before the fetch) and then if that isn't the issue, double check the API docs and make sure the rest of that string is correct

**Comment by christian-the-brewer** [comment]
I actually discovered that I forgot to include the route in my server.js, so i think that 404 was from the backend for the front end request, not from the third party api. I am now getting that fetch is not defined. I think I will need to install node-fetch to get that to work, or I can use axios instead of fetch to query the database?

**Comment by christian-the-brewer** [comment]
I am now making an api file in the back end that will hold the axios requests I want to make to the url, I will see how that goes.

**Comment by kestler01** [comment]
well there you go, that'll do it. I like the idea of the separate file with axios calls - keep me updated on progress here

**Comment by kestler01** [comment]
I'm assuming axios is working out for you so far. closing for now lmk if that is not the case

**Comment by christian-the-brewer** [comment]
not working out for us yet! I am still working on getting the calls down

**Comment by christian-the-brewer** [comment]
I am having trouble with importing my multiple axios call functions from my file. I tried
```js
import { fetchPopularMovies, fetchPopularMoviesByPlatform, fetchMovieById, fetchMovieTitleByPlatform } from '../api'

```
but it said I cant use import outside of a module. Then I tried destructuring with 
```js
const { fetchPopularMovies, fetchPopularMoviesByPlatform, fetchMovieById, fetchMovieTitleByPlatform } = require('../api')

```
and that says it is expecting an export, could you help direct me to destructure correctly?

**Comment by timmshinbone** [comment]
Share your entire api file you're trying to import and destructure from

**Comment by christian-the-brewer** [comment]
```js
const discoverMovieUrl = "https://api.themoviedb.org/3/discover/movie?api_key=58a92a2a4d225c25e73bb7fe5bfb8183&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1"

const discoverTvUrl = "https://api.themoviedb.org/3/discover/tv?api_key=58a92a2a4d225c25e73bb7fe5bfb8183&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1"

const showMovieUrl = `https://api.themoviedb.org/3/movie/${movieId}?api_key=58a92a2a4d225c25e73bb7fe5bfb8183&language=en-US`

const showTvUrl = `https://api.themoviedb.org/3/tv/${showId}?api_key=58a92a2a4d225c25e73bb7fe5bfb8183&language=en-US`

//FETCH MOST POPULAR BY REGION
export const fetchPopularMovies = (region) => {
    return axios({
        url: `${discoverMovieUrl}&watch_region=${region}`,
        method: 'GET'
    })
}

export const fetchPopularShows = (region) => {
    return axios({
        url: `${discoverTvUrl}&watch_region=${region}`,
        method: 'GET'
    })
}

//FETCH MOST POPULAR BY REGION AND STREAMING PLATFORM
export const fetchPopularMoviesByPlatform = (region, platform) => {
    return axios({
        url: `${discoverMovieUrl}&watch_region=${region}&with_watch_providers=${platform}`,
        method: 'GET'
    })
}

export const fetchPopularShowsByPlatform = (region, platform) => {
    return axios({
        url: `${discoverTvUrl}&watch_region=${region}&with_watch_providers=${platform}`,
        method: 'GET'
    })
}

//FETCH SPECIFIC TITLE BY API SUPPLIED ID
export const fetchMovieById = (id) => {
    movieId = id
    return axios({
        url: `${showMovieUrl}`,
        method: 'GET'
    })
}

export const fetchShowById = (id) => {
    showId = id
    return axios({
        url: `${showTvUrl}`,
        method: 'GET'
    })
}



```

perhaps I need to use module.exports?

**Comment by christian-the-brewer** [comment]
I was also thinking of doing 
```js
const apiCalls = require('../api')
```
and then using dot notation to access the functions inside? like 
```js
apiCalls.fetchShowById()

```

**Comment by timmshinbone** [comment]
I like doing that. You can also do it like this:
```js
import { fetchPopularMovies, fetchPopularShows} from '../api'
```

^If that line is giving you trouble, check your path

**Comment by christian-the-brewer** [comment]
if declaring the whole file as a variable is a good way, how do I export the entire file at the bottom? the way you like doing it is how I tried the first time. It says that I cannot use import outside of a module, Is that because my path is wrong? My api.js file is located  at app/api.js, while the routes files I am calling it in is at app/routes/movie_routes.js

**Comment by christian-the-brewer** [comment]
per andrew's input I got rid of the ES6 syntax and got it to work correctly.
