### ISSUE TITLE
Having an issue refreshing show after editing in modal

### ISSUE THREAD

**Issue by shaialoni** [sei-ec-remote/project-4-issues#108]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Auto refresh show page after edit in modal submits

### Post any code you think might be relevant (one fenced block per file)
```javascript
// update function
 updateDeveloper(user, dev._id, editedFields)
        .then(res => {
          onClose()
          triggerRefresh()
      })
```
```javascript
//modal using a shared form - DevForm
 <Modal isOpen={isOpen} onClose={onClose}>
                <ModalOverlay />
                <ModalContent>
                    <ModalHeader>Modal Title</ModalHeader>
                    <ModalCloseButton />
                    <ModalBody>
                        <DevForm
                            type='edit'
                            msgAlert={msgAlert} 
                            user={user}
                            triggerRefresh={() => setUpdated(prev => !prev)}
                            dev={developer}
                            onClose={onClose}
                        />
                    </ModalBody>
        
                    <ModalFooter>
                    
                    <Button colorScheme='blue' mr={3} onClick={onClose}>
                        Cancel
                    </Button>
                    <Button variant='ghost'>Secondary Action</Button>

                    </ModalFooter>
                </ModalContent>
            </Modal>
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
N/A

### What is your best guess as to the source of the problem?
The refresh is happening inside a component inside the modal, so when running it does not refresh "the right thing"

### What things have you already tried to solve the problem?
Changing refresh method, moving the trigger function def around, navigating instead of refreshing

**Paste a link to your repository here**
https://github.com/tylly/project-4-react

**Comment by aishcann** [comment]
solved - needed to add a dependency array to useEffect

**Comment by shaialoni** [comment]
We added the state being changed in the dependency array, but it causes it to query somewhere between 80-100 times a second (I started counting but gave up...
Tried different things, like using updated, setUpdated for the dependency array but it's not working....
