### ISSUE TITLE
Sign-in and sign-up

### ISSUE THREAD

**Issue by katherine-kania** [sei-ec-remote/project-4-issues#11]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
I am trying to sign in and sign up in postman and it's asking for credentials. 

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![image](https://user-images.githubusercontent.com/98362705/165122093-622beaee-bf75-46dd-a73e-efe9a15cb65d.png)

### What is your best guess as to the source of the problem?
Maybe it's the token?  I need some guidance on where to get it or add it!

### What things have you already tried to solve the problem?
Secret key in token.

**Paste a link to your repository here**
https://github.com/katherine-kania/project-4-api

**Comment by DoireannJane** [comment]
https://github.com/sei-ec-remote/project-4-issues/issues/8

**Comment by DoireannJane** [comment]
Hope this helps! Let me know if not!

**Comment by katherine-kania** [comment]
It did! Thank you, Doireann. I was passing user instead of credentials. For some annoying reason, postman deleted all my past project collections and request and I felt disoriented. :(
