### ISSUE TITLE
Making use of Admin view Groups and assigning them to users.

### ISSUE THREAD

**Issue by DRG104** [sei-ec-remote/project-4-issues#110]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
Trying to selectively allow permissions for users depending on a Boolean set during user creation. In case it matters, the plan is to allow this Boolean to be toggled by user to switch between allowable options/permissions. I looked into the Groups in the admin view and it seems to be what I'm looking for. After creating a group and choosing its permission, I would like to know how to assign these groups to users so I can better control what options are available to them.

I am also aware of these options, (Thank you Alys!), and understand the boilerplate sets the `permission_classes` to `(isAuthenticated,)`
Fiddling with it basically just allows for views of my models to be interacted with, and is not quite what I'm looking for.
```
    authentication_classes = ()
    permission_classes = ()
```

These are the groups/permissions in the admin views I am referring to:
![image](https://user-images.githubusercontent.com/106381005/186389480-f8854ba2-db80-4e1b-8f82-f094b26574fd.png)

### Post any code you think might be relevant (one fenced block per file)
I don't have any relevant code really but for example:
```
class Contracts(generics.ListCreateAPIView):
    permission_classes=(IsAuthenticated,)
    serializer_class = ContractSerializer
    def get(self, request):
        """Index request"""
        # Get all the contracts:
        # contracts = Contract.objects.all()
        # Filter the contracts by owner, so you can only see your owned contracts
        contracts = Contract.objects.filter(owner=request.user.id)
        # Run the data through the serializer
        data = ContractSerializer(contracts, many=True).data
        return Response({ 'contracts': data })

    def post(self, request):
        """Create request"""
        # Add user to request data object
        request.data['contract']['owner'] = request.user.id
        # Serialize/create contract
        contract = ContractSerializer(data=request.data['contract'])
        # If the contract data is valid according to our serializer...
        if contract.is_valid():
            # Save the created contract & send a response
            contract.save()
            return Response({ 'contract': contract.data }, status=status.HTTP_201_CREATED)
        # If the data is not valid, return a response with the errors
        return Response(contract.errors, status=status.HTTP_400_BAD_REQUEST)
```
If I change the permission classes to = `()` then users without authentication can access this view. I would like for users to be authenticated, but based on groups assigned I would like to limit/allow what authenticated users are allowed to do.

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
n/a

### What is your best guess as to the source of the problem?
I am lacking

### What things have you already tried to solve the problem?
I read through: https://www.django-rest-framework.org/api-guide/generic-views/
and
https://www.django-rest-framework.org/api-guide/permissions/
to see if they make any reference to Groups and how to utilize them, but maybe I'm looking in the wrong place / for the wrong thing.

**Paste a link to your repository here**
https://github.com/Zene09/server-dreamlancer

**Comment by timmshinbone** [comment]
What if you reserve those types of permissions for the front-end in version 1 of this app, which will be much easier to set rules for that boolean either in your api call function or before that function gets called, and if you want to practice with non-default permission classes in version 2, you can once the full app's been done?

**Comment by DRG104** [comment]
Issue closed, Timm provided documents for exactly what I need for reference if anyone needs this:
https://testdriven.io/blog/custom-permission-classes-drf/
Is pretty much everything you need.

In case you don't know what to look for, look at...
```
class AuthorAllStaffAllButEditOrReadOnly(permissions.BasePermission):

    edit_methods = ("PUT", "PATCH")

    def has_permission(self, request, view):
        if request.user.is_authenticated:
            return True

    def has_object_permission(self, request, view, obj):
        if request.user.is_superuser:
            return True

        if request.method in permissions.SAFE_METHODS:
            return True

        if obj.author == request.user:
            return True

        if request.user.is_staff and request.method not in self.edit_methods:
            return True

        return False
```
