### ISSUE TITLE
Trying to populate owner information into comments

### ISSUE THREAD

**Issue by bostonbachexchange** [sei-ec-remote/project-4-issues#113]
### What stack are you using? 
MERN(mongoose + react)

### What's the problem you're trying to solve?
I am trying to populate the owner information into the comments(comment is subdocuments model of Message) . This would hopefully allow me to pull in user information like user name of comment creator and other things. I manage to assign the owner Id to the comment. The owner information is already populating in the message document, but not within the comment subdoc.

### Post any code you think might be relevant (one fenced block per file)
```js
// SHOW
// GET /messageboard/5a7db6c74d55bc51bdf39793
router.get('/messageboard/:id', (req, res, next) => {
	// req.params.id will be set based on the `:id` in the route
	MessageBoard.findById(req.params.id)
	.populate('owner')
		.then(handle404)
		// if `findById` is succesful, respond with 200 and "example" JSON
		// .then((message) => {
		// 	if (message.comments) {
		// 		console.log('message.comments', message.comments)
		// 		// message.comments.find()
		// 		// .populate('owner')
		// 	}
		// })
		.then((message) => res.status(200).json({ message: message.toObject() }))
		// if an error occurs, pass it to the handler
		.catch(next)
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
cannot read properties of undefined

### What is your best guess as to the source of the problem?
Comments are show on the message page, not their own show page. I am guess they need to be populated from the message_routes.

### What things have you already tried to solve the problem?
```js
		// .then((message) => {
		// 	if (message.comments) {
		// 		console.log('message.comments', message.comments)
		// 		// message.comments.find()
		// 		// .populate('owner')
		// 	}
```
**Paste a link to your repository here**
https://github.com/bostonbachexchange/project_4_API.git

**Comment by timmshinbone** [comment]
Try adapting your populate message to include multiple fields, like this:
```js
.populate('owner', 'comments.owner')
```

Another more technical population method looks like this:
```js
.populate({
	path:     'comments',			
	populate: { path:  'owner',
		    model: 'users' }
  })
```

**Comment by timmshinbone** [comment]
If you share what the models look like it'll be easier for me to say how this should be written out. Sharing the data you're currently receiving from the API will help even further

**Comment by bostonbachexchange** [comment]
MODELS: 

```js
const mongoose = require('mongoose')
const commentSchema = require('./comment')
// const user = require('./user')
const { Schema, model } = mongoose

const messageBoardSchema = new Schema(
	{
		name: {
			type: String,
		},
		title: {
			type: String,
		},
		content: {
			type: String,
			required: true,
		},
		date: {
			type: Date,
			default: Date.now,
		},
		comments: [commentSchema],
		owner: {
			type: Schema.Types.ObjectId,
			ref: 'User',
			required: true,
		},
	},
	{
		timestamps: true,
	}
)

module.exports = model('MessageBoard', messageBoardSchema)
```

```js
const mongoose = require('mongoose')
// const { Schema, model } = mongoose

const commentSchema = new mongoose.Schema(
	{
		content: {
			type: String,
			required: true,
		},
		date: {
			type: Date,
			default: Date.now,
		},
		owner: {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'User',
			// required: true
		},
	},
	{
		timestamps: true,
	}
)

module.exports = commentSchema
```

**Comment by bostonbachexchange** [comment]
oh man.... my indentation is not like that i promise

**Comment by timmshinbone** [comment]
Don't worry I fixed the formatting. What's the data look like when you get a response from the route?

**Comment by bostonbachexchange** [comment]
![Screen Shot 2022-08-24 at 10 57 30 AM](https://user-images.githubusercontent.com/105309528/186452074-04e14f33-2e1a-49b8-8831-48a9777f9798.png)

**Comment by timmshinbone** [comment]
Ok, did you try adjusting your populate message? Should look a little something like this:
```js
MessageBoard.findById(req.params.id)
	.populate('owner', 'comments.owner')
```

**Comment by bostonbachexchange** [comment]
MessageBoard.findById(req.params.id)
	.populate('owner', 'comments.owner')
		.then(handle404)


ok, just tried this one, still no dice

**Comment by timmshinbone** [comment]
any change in response data?

**Comment by bostonbachexchange** [comment]
![Screen Shot 2022-08-24 at 11 06 01 AM](https://user-images.githubusercontent.com/105309528/186454097-f9174935-6c45-4c57-aa3e-5dcbbcd02f77.png)


not that i can tell

**Comment by timmshinbone** [comment]
ok, let's check it out in a breakout room

**Comment by bostonbachexchange** [comment]
Thanks, Tim! Adding comments.owner in the array works

MessageBoard.findById(req.params.id)
     .populate(['owner', 'comments.owner'])
     .then(handle404)
