### ISSUE TITLE
.map for Cards

### ISSUE THREAD

**Issue by Rando-cal** [sei-ec-remote/project-4-issues#114]
### What stack are you using? 
MERN
### What's the problem you're trying to solve?
.Map a prop array to generate Bootstrap cards.

### Post any code you think might be relevant (one fenced block per file)
```js
const Cards = ({topTitlesList}) => {
   const id = uuid()

    const addFavorite = () => {
        console.log('in addFavorite:cards.js');
    }

    const [userName, setUserName] = useState('')
    const [region, setRegion] = useState('')
    const [topTitles,setTopTitles] = useState([])

    console.log('topTitles after useEffect:',topTitles)

    const titleCards = topTitlesList.map((aTitle) => {

        <Card style={{ width: '18rem' }} key={aTitle.id}>
            <Card.Img variant="top"  />
             <Card.Body>
                <Card.Title>{aTitle.backdrop_path}</Card.Title>
                <Card.Text>
                    Some quick example text to build on the card title and make up the
                    bulk of the card's content.
                </Card.Text>
                <Button variant="primary">Go somewhere</Button>
            </Card.Body>
        </Card>
    
    })

    console.log('titleCards',titleCards);

    return (
        <>
        <div className= "card-container BG-black">

           <h1>{titleCards}</h1>
        </div>
        </>
    )
}

export default Cards
```
See:  totTItlesList from prop is populated with an array of items...  however,  the titleCards (consolelog) is all undefined

![array](https://user-images.githubusercontent.com/106480852/186463538-db6094cc-9480-414c-9d77-6c95534bf0e6.PNG)
![markup](https://user-images.githubusercontent.com/106480852/186463562-a3dc97b9-f50e-4e06-bef6-ca110b291f77.PNG)

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Only, error, which is non-blocking is "index.js:1 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    at a
    at LinkWithRef (http://localhost:3000/static/js/vendors~main.chunk.js:51481:5)"

### What is your best guess as to the source of the problem?
.map is not happy

### What things have you already tried to solve the problem?
tried various permutations of .map and the input array

**Paste a link to your repository here**
https://github.com/Rando-cal/streamgenie-react-front

**Comment by kestler01** [comment]
Hey randy, I don't actually see a use effect in the code above, or where you do an assignment TopTitles using setTopTitles. 
Have you tried the useEffect with a setTopTitles  OR  initializing TopTitles with a default of the TopTitlesList ?

**Comment by timmshinbone** [comment]
Your map needs to return the cards. Try changing the callback function's curlies to parens for the _implied return_

**Comment by Rando-cal** [comment]
Andrew, TopTitlesList is generated in the parent component then passed down through the props:

```
	useEffect(()=> {
		getTopTitles()
		.then((res) => {setTopTitlesList(res.data.results)})
		.catch((error)=> {console.log(error)})
	},[])
```

**Comment by Rando-cal** [comment]
Yuupppp... The curlies to parenthes fixed it.  Thanks!
