### ISSUE TITLE
Showing data in card (Map method)

### ISSUE THREAD

**Issue by lancenguyen100** [sei-ec-remote/project-4-issues#115]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Trying to display data in myPlant page

### Post any code you think might be relevant (one fenced block per file)
```js
<>
        const plantCards = plants.map(plant => (
            (user && user._id === plant.owner._id)
            ?
            <Card style={{ width: '30%', margin: 5}} key={ plant._id }>
                <Card.Header><Link to={`/greenhome/${plant._id}`}> { plant.name }</Link></Card.Header>
                <Card.Body>
                    <Card.Text>
                        <Link to={`/greenhome/${plant._id}`}> <img src={`${plant.image}`} height="200" width="auto" /></Link>
                    </Card.Text>
                </Card.Body>
            </Card>
            :
            null
        ))
        </>
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Created plant cannot be displayed.

### What is your best guess as to the source of the problem?
Maybe we are using the ternary wrong.

### What things have you already tried to solve the problem?
Looking at old codes and solving as a group.

**Paste a link to your repository here**[
](https://github.com/dangdo85/project-4-client)

**Comment by kestler01** [comment]
I think you should start by changing this arrow function to use the explicit return () =>{ return x }
and add some console.logs to check your variables and logic here - update with new code and comments / logs

**Comment by timmshinbone** [comment]
Currently your map callback is returning either a false or a card, I think you should approach this one of two ways:
Either make a route in the backend that only returns the user specific plants, or move your conditional statement that looks for the user and compares their id with the plant owner outside of that function and in a place that will still allow that data to be shown when the condition is true.

**Comment by lancenguyen100** [comment]
`===== Incoming Request =====
Wed Aug 24 2022 13:35:12 GMT-0400 (Eastern Daylight Time)
GET /greenhome/myplants
body {}
============================
 13:35:12 GMT-0400 (Eastern Daylight Time):
CastError: Cast to ObjectId failed for value “myplants” (type string) at path “_id” for model “Plant”
  at model.Query.exec (/Users/dangdo/sei/projects/project-4/project-4-api/node_modules/mongoose/lib/query.js:4584:21)`


***Getting this error when trying to display the "myPlant"***

**Comment by kestler01** [comment]
did you remember to add the requireToken middleware to the API's path definition ?

**Comment by lancenguyen100** [comment]
Yes. We did add the requireToken in.

**Comment by timmshinbone** [comment]
Did you add in `requireOwnership`? share the whole route. NOT THE WHOLE FILE, JUST THE ROUTE WERE TALKING ABOUT

**Comment by lancenguyen100** [comment]
```js
// CREATE
// POST /myplants
router.post('/greenhome/myplants', requireToken, (req, res, next) => {
	// set owner of new myplant to be current user
	req.body.plant.owner = req.user.id

	Myplant.create(req.body.plant)
		// respond to succesful `create` with status 201 and JSON of new "myplant"
		.then((myPlant) => {
			console.log('my plant in create route', myPlant)
			res.status(201).json({ myPlant: myPlant.toObject() })
		})
		// if an error occurs, pass it off to our error handler
		// the error handler needs the error message and the `res` object so that it
		// can send an error message back to the client
		.catch(next)
})
```

**Comment by timmshinbone** [comment]
Thought we were trying to hit a get route

**Comment by lancenguyen100** [comment]
```
// INDEX
// GET /myplants
router.get('/greenhome/myplants', requireToken, (req, res, next) => {
	Myplant.find()
		.populate("owner")
	// we want everyone to see our plants whether they are logged in or not, we remove the `requireToken`
	// if we wanted to protect these resources, we can add the requireToken middleware in
	// requireToken goes between the route and the callback function
		.then((myplants) => {
			// `myplants` will be an array of Mongoose documents
			// we want to convert each one to a POJO, so we use `.map` to
			// apply `.toObject` to each one
			return myplants.map((myplant) => myplant.toObject())
		})
		// respond with status 200 and JSON of the myplants
		.then((myplants) => res.status(200).json({ myplants: myplants }))
		// if an error occurs, pass it to the handler
		.catch(next)
})```

Sorry! wrong one.

**Comment by timmshinbone** [comment]
lmao I can not understand how or why your code blocks are formatted differently every single time. before the code, add three backtics and js (\```js\) and start the code on the next line, after all the code, close it with three backtics (\```\)

**Comment by timmshinbone** [comment]
And the solution to the problem is to utilize the `requireOwnership` middleware like we used in the pets app

**Comment by lancenguyen100** [comment]
Hey Tim..Do you mind hopping in a room with us. We are just a bit lost here.

**Comment by lancenguyen100** [comment]
Change myplant._id to myplantId. The id was not within an object.
