### ISSUE TITLE
uni_verse_client

### ISSUE THREAD

**Issue by SunGod7** [sei-ec-remote/project-4-issues#117]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN(mongoose + react)
### What's the problem you're trying to solve?

getting data from api
### Post any code you think might be relevant (one fenced block per file)
```
const handleSubmit = (e) => {
        e.preventDefault()

console.log(`\nsubmitted value:\n${searchValue}`)
      axios.get(`https://api.lyrics.ovh/v1/${searchValue}`)
            .then((res) => {
                const data = res.data
                 console.log(data)
                 handleViewLyricsInModal(data)

            })
            .catch(err => console.log(err))
    }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
src/components/lyrics/FilterIndexForm.js
  Line 76:8:  React Hook useEffect has missing dependencies: 'msgAlert' and 'props'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
index.js:1 Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
submitted value:
dmx slippin
FilterIndexForm.js:137 Error: Request failed with status code 404
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:66:1)

### What is your best guess as to the source of the problem?

i think it has something to do with the way im calling the api
### What things have you already tried to solve the problem?
used different methods for fetching the data also tried to use seed data

**Paste a link to your repository here**
https://github.com/SunGod7/uni_verse_client

**Comment by timmshinbone** [comment]
Drop a link to your API documentation and share what your `console.log(data)` line delivers

**Comment by SunGod7** [comment]
https://github.com/SunGod7/my_uni_verse_api

===== Incoming Request =====

Wed Aug 24 2022 13:34:30 GMT-0400 (Eastern Daylight Time)
GET /lyrics
body {}

============================

**Comment by timmshinbone** [comment]
no I meant the docs for THIS api you're calling in this line ->
```js
axios.get(`https://api.lyrics.ovh/v1/${searchValue}`)
```
and the subsequent console log in that function call's `.then()`

**Comment by SunGod7** [comment]
https://lyricsovh.docs.apiary.io/#reference/0/lyrics-of-a-song

**Comment by SunGod7** [comment]
Error: Request failed with status code 404
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:66:1)

**Comment by mattkeane-ga** [comment]
Looking at your logs, it looks like the value for `searchValue` is `'dmx slippin'`. If you look at [the api documentation](https://lyricsovh.docs.apiary.io/#reference/0/lyrics-of-a-song/search), requests are in the form of `https://api.lyrics.ovh/v1/artist/title`. If you interpolate `'dmx slippin'` into `https://api.lyrics.ovh/v1/${searchValue}`, what do you get? Does this match the url pattern that the api is looking for?

**Comment by SunGod7** [comment]
i had it like this and still wasn't working
`https://api.lyrics.ovh/v1/${artistName}/${titleName}`

**Comment by mattkeane-ga** [comment]
Can you show the code for that version please? Where does `artistName` and `titleName` come from?

**Comment by SunGod7** [comment]
const FilterIndexForm = (props) => {

    const { user, msgAlert } = props

     const [artistName, setArtistName] = useState('')
     const [titleName, setTitleName] = useState('')
    // const [lyrics, setLyrics] = useState('')
    const [lyrics, setLyrics] = useState(null)
    //const [searchValue, setSearchValue] = useState({ artist: '', title: '' })
    const [lyricsToView, setLyricsToView] = useState([])
    const [createLyricModalShow, setCreateLyricModalShow] = useState(false)
    const [showLyricViewModal, setShowLyricViewModal] = useState(false)
    const [lyricInViewModal, setLyricInViewModal] = useState({})
    const [updateTaggedLyrics, setUpdateTaggedLyrics] = useState(true)

**Comment by mattkeane-ga** [comment]
The rest of the component? Any errors? What happens when you try to submit?

**Comment by SunGod7** [comment]
The auth components work and the forms. when i submit i get this:
src/components/lyrics/FilterIndexForm.js
  Line 17:24:  'setTitleName' is assigned a value but never used                                                                          no-unused-vars
  Line 76:8:   React Hook useEffect has missing dependencies: 'msgAlert' and 'props'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
printWarnings @ webpackHotDevClient.js:138
FilterIndexForm.js:125 
submitted value:
dmx slippin/
FilterIndexForm.js:139 Error: Request failed with status code 404
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:66:1)

**Comment by mattkeane-ga** [comment]
It doesn't look like you are using `setTitleName` at all, and it looks like you're still submitting your search as one single long string with both the name of the artist and the name of the title. You would need to have two inputs on your form—one for the artist and one for the title. Then you will need to make a request to your api in the pattern that the documentation specifies with both values separated by a slash.

**Comment by SunGod7** [comment]
ok I'll try that
