### ISSUE TITLE
socket io

### ISSUE THREAD

**Issue by jadenRuplal** [sei-ec-remote/project-4-issues#118]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
react express

### What's the problem you're trying to solve?
I've been looking at the documentation and I'm not really sure on where to go to implement this on my project

### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/jadenRuplal/project-4-carbid-api
https://github.com/jadenRuplal/project-4-carbid-client

**Comment by timmshinbone** [comment]
Add some pseudo code and maybe we can figure out where to place this together. What should be the behavior of the app when utilizing a socket. Add pseudo code here as a list of steps that should be taken by either user or the code to implement the desired result, something like this:

- user adds a message
- user hits send
- send makes api call to xyz route...

and so on, then we can think about where to try implementing sockets

**Comment by jadenRuplal** [comment]
- add an on-click to bid submission and comment submission 
- once the user hits send a new function is called which emits the desired values to the API 
- the API broadcasts these new values for everyone to see on screen (current bid gets updated) (new comments displayed on screen)


looking at the server stuff is confusing to me not sure how to do that end but I think I got the idea of how to do it on the front end. 

`import io from 'socket.io-client'`

` socket.on('connect', () => {
                setIsConnected(true)
              })
        socket.on('disconnect', () => {
                setIsConnected(false)
              })

        return () => {
                socket.off('connect')
                socket.off('disconnect')
                socket.off('pong')
              }`

`const sendPing = () => {
        socket.emit('ping')
        console.log('ping')
      }`

**Comment by timmshinbone** [comment]
Is that all? Any way to make the pseudo code more detailed?(including which routes are hit specifically, lifecycles of components etc)

**Comment by jadenRuplal** [comment]
the routes being hit would be /cars/:id/comments for comments and cars/bid/:id


there are other routes that can be hit but these are the two key ones I want to try first

**Comment by jadenRuplal** [comment]
I've got a base kinda working but not so sure
