### ISSUE TITLE
Issue with two API requests in one route

### ISSUE THREAD

**Issue by christian-the-brewer** [sei-ec-remote/project-4-issues#119]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?

I am making two api fetches in one route from my back end, and sending two objects to the front. The first is a fetch by Id of a specific movie, the second is also by id and for the platforms (Hulu, HBOMAX) that are streaming it. The second request works and is returning usable data, the first is undefined though. 
### Post any code you think might be relevant (one fenced block per file)
```js
//SHOW
// GET /movie/:id
router.get('/movie/:id', (req, res, next) => {
    //fetch specified move using API's title id
    console.log("hit the route")
    fetchMovieById(req.params.id)
        .then(handle404)
        .then((movie) => {
            fetchMovieProviders(req.params.id)
                .then(handle404)
                .then((providers) => {
                    console.log("Providers:", providers.data.results)
                    console.log("movie:", movie.data.results)
                    res.status(201).json({ providers: providers, movie: movie.data.results })
                })
                .catch(next)
            // res.status(201).json({ movie: movie.data.results })


        }
        )
        .catch(next)
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```js
movie: undefined

 13:49:39 GMT-0400 (Eastern Daylight Time):
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/express/lib/response.js:260:14)
    at /home/gene/sei/projects/capstone_project/streamgenie-backend_api/app/routes/movie_routes.js:69:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

### What is your best guess as to the source of the problem?

perhaps something to do with converting the data to an object? I am not sure what circular means in the error. 
### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/christian-the-brewer/streamgenie-backend_api

**Comment by aishcann** [comment]
What is the data returning when you `console.log(providers.data.results)`?

**Comment by aishcann** [comment]
I also think I need to see everything you are trying to do and see how everything is working to help you best. Slack me and let me know when you are able to hop on Zoom. We have a meeting from 3-4pm - I'm available before and after that time.

**Comment by aishcann** [comment]
resolved - created an object within the GET route, and added the necessary provider and movie data to it
