### ISSUE TITLE
Refreshing show page after editing entry in modal

### ISSUE THREAD

**Issue by shaialoni** [sei-ec-remote/project-4-issues#120]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
refreshing show page after closing modal
Modal renders a shared form that's in a different component, and I believe the trigger refresh that is being called in that form does not refresh the show page.

### Post any code you think might be relevant (one fenced block per file)
```javascript
<Modal isOpen={isOpen} onModalClose={onModalClose}>
        <ModalOverlay />
        <ModalContent>
            {/* <ModalHeader>Modal Title</ModalHeader> */}
            <ModalCloseButton />
            <ModalBody>
                <DevForm
                    type='edit'
                    msgAlert={msgAlert} 
                    user={user}
                    triggerRefresh={() => setUpdated(prev => !prev)}
                    dev={developer}
                    onClose={onClose}
                />
            </ModalBody>

            <ModalFooter>
            
            <Button colorScheme='blue' mr={3} onClick={onClose}>
                Cancel
            </Button>
            <Button variant='ghost'>Secondary Action</Button>

            </ModalFooter>
        </ModalContent>
        </Modal>

```
```javascript
function handleSubmitEdit (e) {
      e.preventDefault()
      const editedFields = {
      name,
      linkedin,
      github,
      portfolio
      }
      updateDeveloper(user, dev._id, editedFields)
        .then(res => {
          onClose()
          triggerRefresh()
      })
      .catch(err => {
        console.log(err)
        msgAlert("edit post error", "error")
      })
    }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
When I add the state I am changing to the dependency array, it submits around 100 queries a second when on the show page, so it works, but not the way I want it to...

### What is your best guess as to the source of the problem?
I believe the refresh is not happening on the show page

### What things have you already tried to solve the problem?
trying to trigger the refresh on the show page itself in combination with closing the modal

**Paste a link to your repository here**
https://github.com/tylly/project-4-react

**Comment by timmshinbone** [comment]
I might need to see this in a breakout room

**Comment by shaialoni** [comment]
Trigger refresh was re defined in the child component, disconnecting it from the initial state.
Thank you!
