### ISSUE TITLE
Polyfills are not autofilled in WebPack 5 - using old webpack

### ISSUE THREAD

**Issue by hrmoyes** [sei-ec-remote/project-4-issues#124]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I am trying to automate webscraping to retrieve github profile image. It works in javascript just fine, but if I ever try to use it with React it COMPLETELY breaks, telling me that "polyfills are not autofilled in WebPack 5+.

### Post any code you think might be relevant (one fenced block per file)
```
const request = require('request-promise')
const cheerio = require('cheerio')

request('https://github.com/tylly/', (error, response, html) => {
    if(!error && response.statusCode==200) {
        const loadGitPfp = cheerio.load(html);

        const profileImgLoad = loadGitPfp(".avatar.avatar-user.width-full")
        console.log(profileImgLoad)
        console.log(profileImgLoad[0].attribs.src)
    }
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Something along the lines of: Polyfills are not autofilled in Webpack 5+

### What is your best guess as to the source of the problem?
From what I've seen, the packages I used are antiquated, however they work in vanilla JS, but not when attempting to use it in accordance with React. I think I need to put it in the backend but I'm not sure how exactly.

### What things have you already tried to solve the problem?
Tried to downgrade to react-scripts 4.0.3 (broke a lot), different polyfill packages, different online fixes. A lot.

**Paste a link to your repository here**
https://github.com/tylly/

**Comment by mattkeane-ga** [comment]
Is there a reason you're trying to perform the scraping from the front end rather than from the back end?

**Comment by hrmoyes** [comment]
I suppose I am confused on how to implement it in the back end based on how I am accessing the data currently. This might be one of those things that a quick talk could help.

**Comment by timmshinbone** [comment]
@hrmoyes was this resolved?
