### ISSUE TITLE
stuck in loop trying to login with api

### ISSUE THREAD

**Issue by mayday91** [sei-ec-remote/project-4-issues#127]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
get token from url

### Post any code you think might be relevant (one fenced block per file)

from App.js 
```
function App() {
  const [token, setToken] = useState(null)

  useEffect(() => {
    const hash = getTokenFromUrl
    window.location.hash = ""
    const _token = hash.access_token

    if (_token) {
      setToken(_token)
    }

    console.log("I HAVE A TOKEN! 👉 ", token)
  }, [])

  return (
    <div className="app">{!token ? <Login /> : <h1>I am logged in</h1> }</div>
  )
}
```

from spotify.js
```
export const getTokenFromUrl = () => {
  return window.location.hash
    .substring(1)
    .split('&')
    .reduce((initial, item) => {
      let parts = item.split('=')
      initial[parts[0]] = decodeURIComponent(parts[1])

      return initial
    }, {})
}
```
### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
app going in circles when clicking login button due to token not being pulled out

### What is your best guess as to the source of the problem?
useEffect hook

### What things have you already tried to solve the problem?
commenting out different parts, trying different variables to access token, changed dependency array, console.log's

**Paste a link to your repository here**
https://github.com/mayday91/spotify-musicmatch-client

**Comment by mattkeane-ga** [comment]
When you say you are stuck in a loop, what loop are you stuck in? How do you know that you are stuck in it?

**Comment by mayday91** [comment]
It keeps bringing me back to the same page when I click login and the inspect console in the browser is showing 'null' for the token I'm trying to pull from URL to actually login

**Comment by mattkeane-ga** [comment]
What does your `Login` component look like?

**Comment by mayday91** [comment]
```
import React from 'react';
import { loginUrl } from './spotify';
import './Login.css';

function Login() {
  return (
    <div className="login">
      <img src='musicMatchLogo.png' alt=""></img>
      <a href={loginUrl}>LOGIN WITH SPOTIFY</a>
    </div>
  )
}

export default Login 
```
