### ISSUE TITLE
Question with bootstrap dropdown menu and navlinks

### ISSUE THREAD

**Issue by christian-the-brewer** [sei-ec-remote/project-4-issues#129]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN
### What's the problem you're trying to solve?
I am trying to figure out bootstrap drop down menu and navlink but I am having trouble getting the link to take me somewhere. I have been going over their documentation for some time and cant get it to work

### Post any code you think might be relevant (one fenced block per file)
```js
<NavDropdown title="Platforms">

			<NavLink href="/movies/US/8">
				<Dropdown.Item>Netflix
				</Dropdown.Item>
			</NavLink>

		</NavDropdown>

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
the browser tells me the link is localhost:3000/# when I hover over netflix in the dropdown

### What is your best guess as to the source of the problem?
I think I dont understand their documentation

### What things have you already tried to solve the problem?
https://react-bootstrap.netlify.app/components/navs/

**Paste a link to your repository here**
https://github.com/christian-the-brewer/streamgenie-react-front

**Comment by mattkeane-ga** [comment]
[Take a look at the documentation for Nav.Dropdown.Item.](https://react-bootstrap.netlify.app/components/dropdowns/#dropdown-item-props) It takes an `onClick` prop. You should be able to use the `useNavigate` prop from React router, and then give that prop an event handler that will navigate to the page you want.

**Comment by christian-the-brewer** [comment]
thanks for the help! I actually just clicked on that page before reading your comment! It works for me without passing any onclick, should I worry about using the usenavigate instead of just assigning it an href?

**Comment by mattkeane-ga** [comment]
There might possibly be an issue with using that in conjunction with React Router. Under the hood it probably functions as a vanilla `<a>`, which will force a reload of your entire app, potentially messing up anything you have in state. Recall how in React router we use the custom `<Link>` component rather than `<a>` tags to navigate around our app. The `useNavigate` hook will allow you to mimic that behavior without forcing a reload of the client side routing of your app.

**Comment by christian-the-brewer** [comment]
okay you're right, it refreshes the whole page, signing me out. I will have to look into using usenavigate, closing the ticket now
