### ISSUE TITLE
Accessing information from a component

### ISSUE THREAD

**Issue by shaialoni** [sei-ec-remote/project-4-issues#130]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Trying to access info from a component

### Post any code you think might be relevant (one fenced block per file)
```javascript
export default function Devs() {
  const [value, setValue] = useState("React");
  const [tags, setTags] = useState([]);
  const [developersItems, setDevelopersItems] = useState([]);

useEffect(() => {
  getAllDevelopers()
    .then((res) => {
      setDevelopersItems(res.data.developers);
      console.log(developersItems);
    })
    .catch((err) => {
      console.log(err);
    });
}, [])
  const developerDropDownItems = developersItems.map((item) => (
    <Dropdown.Item 
      eventKey={item._id}
      key={item._id}
    
    >{item.name}</Dropdown.Item>
  ));

  return <>{developerDropDownItems}</>;
}
```
```javascript
 const ProjectForm = ({ heading, user, msgAlert }) => {
  //   const [image, setImage] = useState({ preview: "", raw: "" });
  const [value, setValue] = useState("React");
  const [tags, setTags] = useState([]);
  const [devs, setDevs] = useState([])

  const handleSelect = (e) => {
    console.log(e);
    setTags((current) => [e, ...current]);
    console.log(tags);
    // setValue(e);
    // console.log(e)
  };
  const handleSelectDevs = (e) => {
    console.log('E from drop down menu', e);
    setDevs((current) => [e, ...current]);
    // setValue(e);
    // console.log(e)
  };
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I need to be able to access more than one piece of info from the dropdown menu

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/tylly/project-4-react

**Comment by mattkeane-ga** [comment]
What information do you need to access from the dropdown menu?

**Comment by shaialoni** [comment]
We have a dropdown menu to select entries from an array from the database.
Through the drop down menu we only have access to one piece of information, so I tried something else, sending state down to the child component, and have the component use that, so I can access it in the parent component.
I am currently having an issue maping over said array and not sure where I am supposed to do it for the result I am looking for.....

**Comment by mattkeane-ga** [comment]
I'm assuming you have in state an array of objects that represent entries from your database. If this is the case, you shouldn't need to get any additional information from the dropdown, you just need to get which item is selected from the dropdown and then treat state as your source of truth. I would suggest using the index of selected item as an identifier. It might look something like:
```jsx
const CatDropDown = () => {
    // a simplified version without useState
    const [cats, setCats] = useState([
        {
            name: 'Lydia',
            color: 'calico',
            _id: '9uhaf3'
        },
        {
            name: 'Allegra',
            color: 'black',
            _id: 'g43j'
        }
    ])
    const [selectedCat, setSelectedCat] = useState(-1)
    // -1 is often used in JavaScript to indicate non-existent or "none selected"

    const handleSelect = eventKey => setSelectedCat(eventKey)
    
    return (
        <Dropdown onSelect={ handleSelect }>
        {
            cats.map((cat, idx) => (
                <Dropdown.Item
                    key={ cat._id }
                    eventKey={ idx }
                >
                    { cat.name }
                </Dropdown.item>
            )
        }
        </Dropdown>
    )
}
```
Then you should be able to reference the selected cat (and any information related to it) with `cats[selectedCat]`.

**Comment by shaialoni** [comment]
I am not looking for the information to display on the dropdown itself, we have that, I want to display multiple selections in a different field.
the "cat.name" is coming from a map in a child component, and I have tried a few different things to get it on a state originating in the parent component but nothing has worked perfectly yet

**Comment by mattkeane-ga** [comment]
I'm not sure I fully understand the problem. Can you post more code? Perhaps the code for the child component that has the map?

**Comment by shaialoni** [comment]
```javascript
import React from "react";
import { useState, useLocation, useEffect } from "react";
import { Dropdown, DropdownButton, Form } from "react-bootstrap";
import { getAllDevelopers } from "../../api/developers";
import "../../style.css";

export default function Devs({setDevNames}) {
  const [value, setValue] = useState("React");
  const [tags, setTags] = useState([]);
  const [developersItems, setDevelopersItems] = useState([]);

useEffect(() => {
  getAllDevelopers()
    .then((res) => {
      setDevelopersItems(res.data.developers);
      console.log(developersItems);
      developersItems.forEach(item => {
        setDevNames(current => [item.name, ...current])
      })
    })
    .catch((err) => {
      console.log(err);
    });
    
}, [])
  const developerDropDownItems = developersItems.map((item) => (
    <Dropdown.Item 
      eventKey={item._id}
      key={item._id}
    
    >{item.name}</Dropdown.Item>
  ));

  return <>{developerDropDownItems}</>;
}

```

**Comment by mattkeane-ga** [comment]
I think I understand what you're trying to do. Are you trying to add items from `developersItems` to `devs` when you click on them from the dropdown?

**Comment by shaialoni** [comment]
Functionality wise it's working, I am able to get the item id which is what I need for it to work.
But since I am selecting multiple developers, I want to display a list of the selections.
We do something similar with tags, but tags is just a regular array, not a database item

**Comment by mattkeane-ga** [comment]
So maybe instead of an array of the ids you want an array of the objects themselves? What if for the `eventKey` you used the entire object instead of just its `_id`?

**Comment by shaialoni** [comment]
I thought you couldnt render objects in jsx returns?

**Comment by mattkeane-ga** [comment]
Cancel that, looking at the docs, it has to be a string or number. But, what you could do is use the event key to access the the item from the `developersItems` array and then add that to to the `devs` array. Instead of using the developer's `_id` as an event key, use its index array. Then inside of the child component, create a function that will add the selected dev (accessible with its array index) to the `devs` array, and use that as the `onSelect` handler.

**Comment by shaialoni** [comment]
I feel like we tried something similar that didn't work the way we intended...
Maybe we just don't display those :)

**Comment by mattkeane-ga** [comment]
Try it, if it works, close this issue. If it doesn't, post the code and explain any issues you're having with it.

**Comment by timmshinbone** [comment]
@shaialoni was this resolved?

**Comment by shaialoni** [comment]
We’re still working on it……
