### ISSUE TITLE
Help with getting the same component to refresh

### ISSUE THREAD

**Issue by christian-the-brewer** [sei-ec-remote/project-4-issues#133]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN
### What's the problem you're trying to solve?

I am trying to render a shared component again with new props passed into it from a NavDropdown in the header file, but it is not working. The browser goes to the new url after I click a new dropdown item, such as netflix or hulu, but the page does not change. My useEffect is not triggering to update the state, which is how I want to change the state.
### Post any code you think might be relevant (one fenced block per file)
```js
<NavDropdown title="Platforms">
			<NavDropdown.Item onClick={useNavigate('/movies/netflix')}>
				{/* <Link to={{ pathname: '/movies/netflix', state: { platformId: 8 } }} >
					Netflix
				</Link> */}
				Netflix
			</NavDropdown.Item>
			<NavDropdown.Item >
				<Link to={{ pathname: '/movies/hbo_max' }} >
					Hbo Max
				</Link>
			</NavDropdown.Item>
			<NavDropdown.Item >
				<Link to={{ pathname: '/movies/amazon_prime' }} >
					Amazon Prime
				</Link>
			</NavDropdown.Item>
			<NavDropdown.Item >
				<Link to={{ pathname: '/movies/hulu' }} >
					Hulu
				</Link>
			</NavDropdown.Item>
			<NavDropdown.Item >
				<Link to={{ pathname: '/movies/disney' }} >
					Disney+
				</Link>
			</NavDropdown.Item>
		</NavDropdown>
```

```js
<Route
					path="/movies/platform"
					element={<IndexMoviesByPlatform user={user} msgAlert={msgAlert} />}
				/>
				<Route
					path="/movies/netflix"
					element={<IndexMoviesByPlatform user={user} platformId={8} msgAlert={msgAlert} />}
				/>
				<Route
					path="/movies/disney"
					element={<IndexMoviesByPlatform user={user} platformId={390} msgAlert={msgAlert} />}
				/>
				<Route
					path="/movies/hulu"
					element={<IndexMoviesByPlatform user={user} platformId={15} msgAlert={msgAlert} />}
				/>
				<Route
					path="/movies/hbo_max"
					element={<IndexMoviesByPlatform user={user} platformId={384} msgAlert={msgAlert} />}
				/>
				<Route
					path="/movies/amazon_prime"
					element={<IndexMoviesByPlatform user={user} platformId={9} msgAlert={msgAlert} />}
				/>
```
### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
no error messages

### What is your best guess as to the source of the problem?
I need to update the state of the component somehow outside of the useEffect maybe? 

### What things have you already tried to solve the problem?

I tried using different methods to link to the platforms. I included my most recent attempt in the above code which you can see on the Nertflix drop down. I was thinking of using useNavigate, but I am having trouble getting it to run because it says that usenavigate cannot be called in the top level  and needs to be in a functional component.
**Paste a link to your repository here**
<Route
					path="/movies/platform"
					element={<IndexMoviesByPlatform user={user} msgAlert={msgAlert} />}
				/>
				<Route
					path="/movies/netflix"
					element={<IndexMoviesByPlatform user={user} platformId={8} msgAlert={msgAlert} />}
				/>
				<Route
					path="/movies/disney"
					element={<IndexMoviesByPlatform user={user} platformId={390} msgAlert={msgAlert} />}
				/>
				<Route
					path="/movies/hulu"
					element={<IndexMoviesByPlatform user={user} platformId={15} msgAlert={msgAlert} />}
				/>
				<Route
					path="/movies/hbo_max"
					element={<IndexMoviesByPlatform user={user} platformId={384} msgAlert={msgAlert} />}
				/>
				<Route
					path="/movies/amazon_prime"
					element={<IndexMoviesByPlatform user={user} platformId={9} msgAlert={msgAlert} />}
				/>

**Comment by kestler01** [comment]
interesting, I would have expected that to work. - do you have a dependency array on the use effect ? 

An alternative could be to write a handler function for this to make state changes and redirect: triggering on click 
_but I hesitate to suggest making this redirect so much more complicated than it should be._
Very open to other instructors opinions here ( it's still pre-coffee-early) @mattkeane-ga @timmshinbone

**Comment by christian-the-brewer** [comment]
My useEffect in the index  Component:
```js
const IndexMoviesByPlatform = (props) => {
    const { msgAlert, user, platformId } = props
    const [id, setId] = useState(null)
    const [movies, setMovies] = useState(null)
    const [error, setError] = useState(false)

    //let data = useLocation()

    console.log("in index platform", movies)

    useEffect(() => {
        console.log("InuseEffect", movies)
        getPopularMoviesByPlatform(region, platformId)
            .then(res => setMovies(res.data.movies))
            .catch(err => {
                msgAlert({
                    heading: 'Error Getting Movies',
                    message: messages.getContentFailure,
                    variant: 'danger',
                })
                console.log(err)
                setError(true)
            })
    }, [])
```

**Comment by christian-the-brewer** [comment]
I have the empty dependency array like we used in class

**Comment by kestler01** [comment]
ah, have you tried using params instead of state here to get the platformId ?

**Comment by christian-the-brewer** [comment]
params from the axios call to the back end?

**Comment by kestler01** [comment]
If you need to use state I think the handler function I mentioned is looking better and better. But you could absolutely use the match params from react router https://v5.reactrouter.com/web/example/url-params

**Comment by timmshinbone** [comment]
^ In response to Andrew's comment, we're using react-router v6, which uses the `useParams` hook, match params went out the window with the hooks upgrade. [docs here](https://reactrouter.com/en/v6.3.0/api#useparams)

**Comment by christian-the-brewer** [comment]
so I would put all the platform routes in as children of one parent route that was just /movies/platform, and the children would be something like /movies/platform/8, but in the route I would just write /8 and the 8 would be a params I could assign to a variable in the page?

**Comment by timmshinbone** [comment]
After survey time, let's look together in a breakout room, little tricky to explain without pointing at actual code

**Comment by kestler01** [comment]
Thank you Timm!

**Comment by timmshinbone** [comment]
update this with the solution in a comment and close the issue

**Comment by christian-the-brewer** [comment]
SOLVED: used useParms to pass the needed platform ID through the url to the component and into the axios call. Needed to include this variable in the useEffect dependency array in order for it to refresh when passed a new ID
