### ISSUE TITLE
firebase module not found

### ISSUE THREAD

**Issue by lancenguyen100** [sei-ec-remote/project-4-issues#136]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN

### What's the problem you're trying to solve?
trying to resolvea module not found error

### Post any code you think might be relevant (one fenced block per file)
```
```

### What is your best guess as to the source of the problem?
I am not sure

### What things have you already tried to solve the problem?

**Paste a link to your repository here**

**Comment by lancenguyen100** [comment]
![Screen Shot 2022-08-26 at 11 15 23 AM](https://user-images.githubusercontent.com/103372967/186937576-2f0e70b5-3380-4db2-9590-12df1adaa1e6.png)

**Comment by mattkeane-ga** [comment]
Show some code. Where are you importing `firebase`?

**Comment by timmshinbone** [comment]
firebase ain't the move here, issue closing
