### ISSUE TITLE
Weird filter

### ISSUE THREAD

**Issue by tylly** [sei-ec-remote/project-4-issues#140]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I am trying to use the includes method on arrays of tags, developers and project names, but i only get the desired effect when i specify which index to check

### Post any code you think might be relevant (one fenced block per file)
```js
   let handleChange = (e) => {
      let arr = projects.filter((i) => {
        if (e.target.value !== "")
        { 
          if(i.tags[0].includes(e.target.value) || i.developers[0].name.includes(e.target.value) || i.name.includes(e.target.value)){
          return i
        } }
        else if (e.target.value === "") {
          console.log("heyyyyyyy")
          getAllProjects()
            .then(res => {
                console.log(res)
                console.log(res.data)
                console.log(res.data.projects)
                setProjects(res.data.projects)})
            .catch(err => {
                msgAlert({
                    heading: 'Error Getting Projects',
                    message: messages.getProjectsFailure,
                    variant: 'danger',
                })
                setError(true)
            })
        }
      })
      console.log("====================>", e.target.value === "", arr)
      setProjects(arr)
    }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
When I take away the [0] from the arrays in the nested if statement, I get nothing. 

### What is your best guess as to the source of the problem?
maybe i misunderstand how includes works. I thought it would check the entire array for the specified string

### What things have you already tried to solve the problem?
nesting a filter method to run the includes method on every element, although i thought this wasnt necessary

**Paste a link to your repository here**
https://github.com/tylly/project-4-react

**Comment by tylly** [comment]
Also i know the else if could just be an else, changing that now

**Comment by mattkeane-ga** [comment]
It sounds like `i.tags` is an array of arrays. Is this accurate?

**Comment by kestler01** [comment]
[check out the filter docs here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#syntax)
we can actually pass index in our callback - see syntax section

**Comment by tylly** [comment]
no, i.tags is an array of strings

**Comment by kestler01** [comment]
what does your project data, `i` .look like

**Comment by tylly** [comment]
![Screen Shot 2022-08-26 at 1 26 07 PM](https://user-images.githubusercontent.com/87946973/186977496-efeb893a-0a1f-4873-bb56-aad8cc2bed87.png)

**Comment by kestler01** [comment]
please put it into a code block so we can see the start and end of the array and the objects in it ( we don't need to see EVERY object  )

**Comment by tylly** [comment]
here is the model
```js
const mongoose = require("mongoose")
const likeSchema = require('./like')

const { Schema, model } = mongoose

const projectSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
    },
    description: String,
    tags: [
      {
        type: String,
      },
    ],
    deployment: String,
    img: String,
    front_end_repo: String,
    back_end_repo: String,
    developers: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: "Developer",
      required: true,
    }],
    likes:[],
    owner: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  {
    timestamps: true,
  }
)
```

here is one of those documents console logged

```
back_end_repo: ""
createdAt: "2022-08-26T18:17:45.039Z"
deployment: ""
description: "Haydens fun little css project"
developers: [{…}]
front_end_repo: ""
img: "https://seir6-6-project3.s3.amazonaws.com/1661537864262_cancel-close-delete-exit-remove-stop-x-icon-326993.png"
likes: []
name: "Hayden project 2"
owner: "6307c34b577df21f17999015"
tags: Array(2)
0: "node"
1: "css"
length: 2
[[Prototype]]: Array(0)
updatedAt: "2022-08-26T18:17:45.039Z"
__v: 0
_id: "63090e496aaa36f190414956"
```

**Comment by kestler01** [comment]
So we have this : conditional

`if(i.tags[0].includes(e.target.value) || i.developers[0].name.includes(e.target.value) || i.name.includes(e.target.value))`

we break it into 3 parts 1 for each of the includes you have here 

```
project.tags is a  ? Array of stings 
project.developers is a ? Array Objects
project.name is a ?  String
```
We need to check if we can use includes with the event value your passing in for the check to make sense in each one of these contexts 

we also need to ask 'What are we actually doing by defining the index to run includes on'

**Comment by tylly** [comment]
got it! solved with this. just need to do the same for the other fields

```js
if(project.tags.find(tag => tag.includes(e.target.value.toLowerCase()))
          //|| project.developers[0].name.includes(e.target.value) || project.name.includes(e.target.value)
          ){
          return project
        }
```
