### ISSUE TITLE
Deployment help

### ISSUE THREAD

**Issue by lancenguyen100** [sei-ec-remote/project-4-issues#143]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN

### What's the problem you're trying to solve?
DEPLOYMENT

### Post any code you think might be relevant (one fenced block per file)
```
N/A
```

### What is your best guess as to the source of the problem?
NOT SURE

### What things have you already tried to solve the problem?

**Paste a link to your repository here**[
](https://github.com/dangdo85/project-4-client)

**Comment by lancenguyen100** [comment]
![Screen Shot 2022-08-28 at 9 46 24 AM](https://user-images.githubusercontent.com/103372967/187209020-93f995f6-c350-4a8e-a7de-a4c5738fc4d5.png)

**Comment by kestler01** [comment]
you will have to make heroku use an older stack config here, be right back with a reference / link

**Comment by kestler01** [comment]
`heroku stack:set heroku-20`

**Comment by lancenguyen100** [comment]
Do I run that inside my backend and frontend terminal? My backend also says heroku22 when i log into heroku.

**Comment by kestler01** [comment]
front end,
