### ISSUE TITLE
Best way to conditionally render buttons on user logged in status

### ISSUE THREAD

**Issue by christian-the-brewer** [sei-ec-remote/project-4-issues#144]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I am trying to conditionally render buttons, links, and conditionally make axios calls depending on whether a user is logged in.

### Post any code you think might be relevant (one fenced block per file)
```js

const [areLoggedIn, setareLoggedIn] = useState(false)
if (user !== null) {
        setareLoggedIn(true)
    }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Currently our issue is that the behaviour of the boolean is not always what we expect and we are wondering if there is a better way to keep track of the logged in status. 

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/christian-the-brewer/streamgenie-react-front

**Comment by kestler01** [comment]
try using `!user` instead of evaluating against null

**Comment by kestler01** [comment]
```
undefined === null
false
```

**Comment by christian-the-brewer** [comment]
so I am doing:
```js
if (!user) {
        setareLoggedIn(false)
    }
```

**Comment by christian-the-brewer** [comment]
that didnt seem to work any different. is the issue that someplaces user will be be null and some places it will be undefined?

**Comment by christian-the-brewer** [comment]
We have this conditional in the useeffect which I think might not be evualting correctly. I think it is not doing the first if when we are logged in: 
```js
useEffect(() => {
        if (areLoggedIn) {
            getOneMovie(id)
                .then(res => {

                    const theMovie = res.data.movie
                    console.log("movie after getOnemovie:", theMovie)
                    getFavorites(user)
                        .then(res => {
                            console.log("theMovie after getFavorites:", theMovie)
                            console.log("favorites after getFavorites:", res.data.favorites)
                            setFavorites(res.data.favorites)
                            setMovie(theMovie)
                        })
                        .catch(err => {
                            msgAlert({
                                heading: 'Error getting favorites',
                                message: messages.getContentFailure,
                                variant: 'danger'
                            })
                            navigate('/')
                            //navigate back to the home page if there's an error fetching
                        })
                })
                .catch(err => {
                    msgAlert({
                        heading: 'Error getting favorites',
                        message: messages.getContentFailure,
                        variant: 'danger'
                    })
                    navigate('/')
                    //navigate back to the home page if there's an error fetching
                })
        } else {
            getOneMovie(id)
                .then(res => setMovie(res.data.movie))
                .catch(err => {
                    msgAlert({
                        heading: 'Error getting movie',
                        message: messages.getContentFailure,
                        variant: 'danger'
                    })
                    navigate('/')
                    //navigate back to the home page if there's an error fetching
                })
        }

    }, [updatedFavorites])
```

**Comment by christian-the-brewer** [comment]
I am going to try a ternary

**Comment by christian-the-brewer** [comment]
that did not change anything unfortunately.  We are mapping over the res of user's favorites list if they are logged in, so we have that in a conditional as well:
```js
let favoritesIdArray = []
    if (areLoggedIn) {
        favoritesIdArray = favorites.map((favorites) => {
            return favorites.contentId
        })
        console.log("This is favoritesIdArray:", favoritesIdArray)
        console.log("this is movie.contentId:", movie.contentId)
    }

    const checkFavorites = () => {
        if (favoritesIdArray.includes(movie.contentId)) {
            return true
        } else {
            return false
        }
    }
```
the problem we are having is that the program keeps running that map whether we are logged in or not. it does not seem to be running the axios call to populate favorites though, and I am not sure why. Everything works without the conditional and with the user signed in, but we needed to have functionality for when users are not signed in and they wont have a favorites list. 

an option I am thinking of is ditching these conditional and simply making an empty favorites list for the user if they are not logged in, or a list with a specific id in it that tell s the page that the user is not signed in. I think that might be better

**Comment by mattkeane-ga** [comment]
Look at your dependency array. I think you're missing something.

**Comment by christian-the-brewer** [comment]
decided to go with easiest solution of requiring user to sign in to access page
