### ISSUE TITLE
Uni-verse

### ISSUE THREAD

**Issue by SunGod7** [sei-ec-remote/project-4-issues#145]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN(mongoose + react)
### What's the problem you're trying to solve?
when i try to edit a comment it lets me type it but when i submit i get error

### Post any code you think might be relevant (one fenced block per file)
```
const handleChange = (e) => {
        setComment(prevComment => {
            let value = e.target.value
            const name = e.target.name

            const updatedComment = {
                [name]: value
            }
            return {
                ...prevComment,
                ...updatedComment
            }
        })
    }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

errors: {
    'comments.0.note': CastError: Cast to string failed for value "{ note: 'rtyg' }" (type Object) at path "note"
        at SchemaString.cast (/Users/tyrellwells/sei/projects/project4/uni-verse-api/node_modules/mongoose/lib/schema/string.js:603:11)
        at SchemaType.applySetters (/Users/tyrellwells/sei/projects/project4/uni-verse-api/node_modules/mongoose/lib/schematype.js:1135:12)
        at EmbeddedDocument.$set (/Users/tyrellwells/sei/projects/project4/uni-verse-api/node_modules/mongoose/lib/document.js:1418:20)
        at EmbeddedDocument.$set (/Users/tyrellwells/sei/projects/project4/uni-verse-api/node_modules/mongoose/lib/document.js:1153:16)
        at EmbeddedDocument.Document (/Users/tyrellwells/sei/projects/project4/uni-verse-api/node_modules/mongoose/lib/document.js:158:12)
        at EmbeddedDocument.Subdocument (/Users/tyrellwells/sei/projects/project4/uni-verse-api/node_modules/mongoose/lib/types/subdocument.js:28:12)
        at EmbeddedDocument.ArraySubdocument [as constructor] (/Users/tyrellwells/sei/projects/project4/uni-verse-api/node_modules/mongoose/lib/types/ArraySubdocument.js:36:15)
        at new EmbeddedDocument (/Users/tyrellwells/sei/projects/project4/uni-verse-api/node_modules/mongoose/lib/schema/documentarray.js:115:17)
        at Proxy._cast (/Users/tyrellwells/sei/projects/project4/uni-verse-api/node_modules/mongoose/lib/types/DocumentArray/methods/index.js:84:17)
        at Proxy._mapCast (/Users/tyrellwells/sei/projects/project4/uni-verse-api/node_modules/mongoose/lib/types/array/methods/index.js:258:17) {
      stringValue: `"{ note: 'rtyg' }"`,
      messageFormat: undefined,
      kind: 'string',
      value: [Object],
      path: 'note',
      reason: null,
      valueType: 'Object'
    }
  },
  _message: 'Lyric validation failed'
}

### What is your best guess as to the source of the problem?

i think its something wrong with my handle change because when i click submit the comment shows in the terminal but not in the modal
### What things have you already tried to solve the problem?

change handle submit function, edited the modal, changed props
**Paste a link to your repository here**
https://github.com/SunGod7/uni_verse_client
https://github.com/SunGod7/my_uni_verse_api

**Comment by mattkeane-ga** [comment]
What do your models look like? Can you also share the code that handles your submits?

**Comment by SunGod7** [comment]
const handleSubmit = (e) => {
        // e equals the event
        e.preventDefault()

        updateComment(user, lyric._id, comment)
            // if we're successful in the modal, we want the modal to close
            .then(() => handleClose())
            // send a success message to the user
            .then(() => {
                msgAlert({
                    heading: 'Oh Yeah!',
                    message: 'Great! The comment is better than ever!',
                    variant: 'success'
                })
            })
            .then(() => triggerRefresh())
            // if there is an error, tell the user about it
            .catch(() => 
                msgAlert({
                    heading: 'Oh No!',
                    message: 'Something went wrong, please try again',
                    variant: 'danger'
                })
            )
    }

    return (
        <Modal show={show} onHide={handleClose}>
            <Modal.Header closeButton />
            <Modal.Body>
                <CommentForm 
                    comment={comment}
                    handleChange={handleChange}
                    handleSubmit={handleSubmit}
                    heading="Update this Comment!"
                />
            </Modal.Body>
        </Modal>
    )
}

**Comment by SunGod7** [comment]
const commentSchema = new mongoose.Schema(
    {
        note: {
            type: String,
            required: true
    
        },
        owner: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true
        }
    }, 
    {
        timestamps: true
    }
)

**Comment by SunGod7** [comment]
const { Schema, model } = mongoose
const lyricSchema = new Schema(

    {
        artist: {
            type: String,
            required: true
        },
        title: {
            type: String,
            required: true
        },
        img: {
            type: String,
            //required: true
        },


        lyrics: {
            type: String,
            required: true
        },
        comments:[commentSchema],
        // reasonTagged: String,

        owner: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            //required: true,
        }

    },
    {
        timestamps: true,
    }
 )

**Comment by mattkeane-ga** [comment]
Can you show the code for `updateComment` please.

**Comment by SunGod7** [comment]
export const updateComment = (user, lyricId, updatedComment) => {
    console.log('updateComment in API was hit')
    console.log('this is updatedComment', updatedComment)
	return axios({
		url: `${apiUrl}/comments/${lyricId}/${updatedComment._id}`,
		method: 'PATCH',
		headers: {
			Authorization: `Token token=${user.token}`
		},
		data: {
			note: updatedComment.note
		}
	})
}

**Comment by mattkeane-ga** [comment]
And also the form you're submitting please.

**Comment by SunGod7** [comment]
const CommentForm = (props) => {
    const {comment, handleChange, handleSubmit, heading} = props

    return (
        <Container className="justify-content-center">
            <h3>{heading}</h3>
            <Form onSubmit={handleSubmit}>
                <Form.Label htmlFor="name">Note</Form.Label>
                <Form.Control
                    placeholder="comment here"
                    name="note"
                    type="text"
                    as="textarea"
                    rows={3}
                    value={ comment.note }
                    onChange={ handleChange }
                />
                
                <Button type="submit">Submit</Button>
            </Form>
        </Container>
    )
}

**Comment by mattkeane-ga** [comment]
One last thing, the update route on the back end.

**Comment by SunGod7** [comment]
/ UPDATE 
// PATCH /comments/<lyric_id>/<comment_id>
router.patch('/comments/:lyricId/:commentId', requireToken, removeBlanks, (req, res, next) => {

    const lyricId = req.params.lyricId
    const commentId = req.params.commentId

    // console.log('Heres the new note: ', req.body.note)

    // find our lyric
    Lyric.findById(lyricId)
        .then(handle404)
        .then(lyric => {
            // single out the comment 
            const theComment = lyric.comments.id(commentId)
            // make sure the user sending the request is the owner
            // requireOwnership(req, lyric)
            // update the comment with a subdocument method
            theComment.set(req.body)
            // return the saved lyric
            // console.log('Heres the lyric AFTER updating note: ', lyric)
            return lyric.save()

            
            
        })
        .then(() => res.sendStatus(204))
        .catch(next)
})

**Comment by mattkeane-ga** [comment]
When you see the error `CastError: Cast to string failed for value "{ note: 'rtyg' }" (type Object) at path "note"`, what that means is that you're trying to set a field that's set to be a string in your schema to an object. In your update route, you're trying to update a field to `req.body`. What datatype is that going to be? What datatype do you want it to be?

**Comment by SunGod7** [comment]
i want it to be a object

**Comment by mattkeane-ga** [comment]
Are you sure? In `commentSchema` note is specified to be a string.

**Comment by SunGod7** [comment]
i think i understand now, so the schema is the object and the note is the prop. so what would i set theComment to ?
(req.params.note)

**Comment by mattkeane-ga** [comment]
Close, you want `req.body.note`.

**Comment by SunGod7** [comment]
i change req.body to req.body.note and i still get the same error

**Comment by SunGod7** [comment]
i figured it out i had create comment route owner required. thank you
