### ISSUE TITLE
Search bar to filter through list

### ISSUE THREAD

**Issue by dangdo85** [sei-ec-remote/project-4-issues#151]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
incorporating a search bar

### Post any code you think might be relevant (one fenced block per file)
```
import "../App.css"
import {useState} from 'react'


function SearchBar() {
    const [searchTerm, setSearchTerm] = useState('')
    return (
    <div className="App">
        <input 
            type="text" 
            placeholder="search..." 
            onChange={event => 
                {setSearchTerm(event.target.value)}}/>
        {plants.filter((plant) => {
            if (searchTerm === "") {
                return plant
            } else if (plant.name.toLowerCase().includes(searchTerm.toLowerCase())) {
                return plant
            }
            })
            .map((plant, key) => {
            return (
                <div className="user" key={key}> 
                {plant.name}
                </div>
            )
        })}
    </div>
    );
}

export default SearchBar;
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Not sure where to incorporate the code

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/dangdo85/project-4-client

**Comment by aishcann** [comment]
Are you trying to figure out which component to put it in?  If so, how do you see it functioning in your app? Where do you want to people to search?

**Comment by dangdo85** [comment]
I want to use it in the plant index and my plant index pages.

**Comment by aishcann** [comment]
Okay. Try importing the component into those pages (just try one page first) and pass the appropriate props over to the `SearchBar` component.  See how that is working then update this issue.
