### ISSUE TITLE
Heroku : undo a 'npx create-react-app $APP_NAME'

### ISSUE THREAD

**Issue by Rando-cal** [sei-ec-remote/project-4-issues#152]
### What stack are you using? 
MERN

### What's the problem you're trying to solve?
I'm trying to deploy front. I believe I ran:

npx create-react-app $APP_NAME
cd $APP_NAME

when I didn't need to... I believe. I then ran: 

heroku create $APP_NAME --buildpack https://github.com/mars/create-react-app-buildpack.git
git add -A
git commit -m "new react app"
git push heroku main
heroku open

Then I during push it failed...

Can I undo  "npx create-react-app $APP_NAME" ???

### Post any code you think might be relevant (one fenced block per file)
```
randy@ubuntu:~/sei/projects/project4/sg-react-front$ ls -al
total 1676
drwxrwxr-x    8 randy randy    4096 Aug 29 13:52 .
drwxrwxr-x    4 randy randy    4096 Aug 20 20:53 ..
-rw-rw-r--    1 randy randy     148 Aug 21 16:26 .env
drwxrwxr-x    8 randy randy    4096 Aug 29 14:10 .git
-rw-rw-r--    1 randy randy     324 Aug 22 10:47 .gitignore
drwxrwxr-x 1125 randy randy   36864 Aug 26 18:32 node_modules
-rw-rw-r--    1 randy randy    1037 Aug 28 20:57 package.json
-rw-rw-r--    1 randy randy 1621632 Aug 28 20:57 package-lock.json
drwxrwxr-x    2 randy randy    4096 Aug 21 15:18 public
-rw-rw-r--    1 randy randy    9207 Mar 29 01:01 README.md
drwxrwxr-x    4 randy randy    4096 Aug 29 13:51 src
drwxrwxr-x    5 randy randy    4096 Aug 29 13:53 streamgenie-front
drwxrwxr-x    2 randy randy    4096 Aug 26 11:16 .vscode

```

Below a new directory the npx generated:
```
randy@ubuntu:~/sei/projects/project4/sg-react-front/streamgenie-front$ ls -al
total 1224
drwxrwxr-x   5 randy randy    4096 Aug 29 13:53 .
drwxrwxr-x   8 randy randy    4096 Aug 29 13:52 ..
-rw-rw-r--   1 randy randy     310 Aug 29 13:53 .gitignore
drwxrwxr-x 799 randy randy   32768 Aug 29 13:53 node_modules
-rw-rw-r--   1 randy randy     820 Aug 29 13:53 package.json
-rw-rw-r--   1 randy randy 1183955 Aug 29 13:53 package-lock.json
drwxrwxr-x   2 randy randy    4096 Aug 29 13:53 public
-rw-rw-r--   1 randy randy    3359 Aug 29 13:53 README.md
drwxrwxr-x   2 randy randy    4096 Aug 29 13:53 src
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

remote: 
remote: !	Push rejected to streamgenie-client.
remote: 
To https://git.heroku.com/streamgenie-client.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/streamgenie-client.git'

### What things have you already tried to solve the problem?

**Paste a link to your repository here**

**Comment by mattkeane-ga** [comment]
Yes. All `npx create-react-app` does is create a new react project using a very basic boiler plate. You should see a directory wherever you ran your code with the same name as the app name that you passed to `npx create-react-app`. Undoing it should be as simple as removing that directory.

**Comment by Rando-cal** [comment]
Ok.... 

I deleted it....


I suppose that wasn't my problem.... On Heroku main push i get:

```
remote: Verifying deploy...
remote: 
remote: !	Push rejected to streamgenie-client.
remote: 
To https://git.heroku.com/streamgenie-client.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/streamgenie-client.git'
```

**Comment by Rando-cal** [comment]
I can make a new ticket...

**Comment by mattkeane-ga** [comment]
Yes, make a new ticket, also include the full error from `heroku logs --tail`. But first, try reading the _entire_ error yourself and see if you can figure out what the issue is on your own.
