### ISSUE TITLE
Pulling Isse

### ISSUE THREAD

**Issue by lancenguyen100** [sei-ec-remote/project-4-issues#154]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
TRYING PULL FROM UPSTREAM MAIN

### Post any code you think might be relevant (one fenced block per file)
```
GIT PULL UPSTREAM MAIN
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
NOT POSSIBLE TO FAST-FORWARD, ABORTING.

### What is your best guess as to the source of the problem?
I AM NOT SURE. 

### What things have you already tried to solve the problem?
LOOK AT STACKOVERFLOW DOCS

**Paste a link to your repository here**

**Comment by aishcann** [comment]
solved - did `git pull upstream main --rebase`
