### ISSUE TITLE
Trying to do anything that requires Auth

### ISSUE THREAD

**Issue by hewinsonj** [sei-ec-remote/project-4-issues#166]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
Trying to do anything that requires Auth

### Post any code you think might be relevant (one fenced block per file)
```
Not sure
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
"detail": "Authentication credentials were not provided."

### What is your best guess as to the source of the problem?
Not sure

### What things have you already tried to solve the problem?
Deleting credentials in curl-scripts/auth/

**Paste a link to your repository here**
https://github.com/hewinsonj/Testaurant-Back-end

**Comment by kestler01** [comment]
if we remember how the default django form structured our data ( without a credentials key) we may need to adjust what the routes need/ remove references to 'credentials' to access the passed data properly 

It also wouldn't hurt to add more context surrounding the error as is

**Comment by kestler01** [comment]
resolved with super user ?

**Comment by hewinsonj** [comment]
Trying it now

**Comment by hewinsonj** [comment]
Ok that worked! The solution was to use command"python manage.py createsuperuser", follow the prompts then start the server and go to (http://127.0.0.1:8000/admin/) and log in with the credentials that were just made in the terminal.
