### ISSUE TITLE
issue to sign in and sign up from react

### ISSUE THREAD

**Issue by Salam3377** [sei-ec-remote/project-4-issues#167]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
getting a 400 error on sign-up and getting a 500 error on sign in when doing it from React. Everything is successful when doing it from django

### Post any code you think might be relevant (one fenced block per file)
```
i am not sure which code would be relevant
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
[21/Nov/2022 18:01:29] "POST /sign-in/ HTTP/1.1" 500 99266
Bad Request: /sign-up/
[21/Nov/2022 18:02:48] "POST /sign-up/ HTTP/1.1" 400 128
Bad Request: /sign-up/
[21/Nov/2022 18:05:34] "POST /sign-up/ HTTP/1.1" 400 128

```

### What is your best guess as to the source of the problem?

not sure

### What things have you already tried to solve the problem?

been in office hours we tried

**Paste a link to your repository here**
https://github.com/Salam3377/Django-lux-house

**Comment by kestler01** [comment]
resolved with super user ?

**Comment by sam-phillips21** [comment]
not entirely sure. we were able to use the super user yesterday

**Comment by sam-phillips21** [comment]
we are able to log in with a non admin account on django but we cant log out any user on the django side. we are wondering how react and django work together with credentials. any chance you can jump into our breakout room to discuss?

**Comment by kestler01** [comment]
Sam, this is not your issue thread.

**Comment by Salam3377** [comment]
Thanks Andrew. resolved issue by adding ['credentials'] in user_views, sign-up and sign-in classes
