### ISSUE TITLE
django auth - logout issues

### ISSUE THREAD

**Issue by amishizaki** [sei-ec-remote/project-4-issues#168]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
Having trouble logging out.

### Post any code you think might be relevant (one fenced block per file)
views/user_views.py
```
class SignOut(generics.DestroyAPIView):
    def delete(self, request):
        # Remove this token from the user
        request.user.delete_token()
        # Logout will remove all session data
        logout(request)
        return Response(status=status.HTTP_204_NO_CONTENT)
```
urls.py
```
urlpatterns = [
  	# Restful routing
...
    path('sign-out/', SignOut.as_view(), name='sign-out'),
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
(latest error as of 8:34pm)
“GET /sign-out/ HTTP/1.1” 405 5016
Method Not Allowed: /sign-out/

### What is your best guess as to the source of the problem?
Seems to be a bug in the system

### What things have you already tried to solve the problem?
(Below is a limited list of attempts)
settings.py change:
```
/// attempt 1 ///
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

/// attempt 2 ///
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
```

Changing the urls.py:
```
/// attempt 1 ///
path("", TemplateView.as_view(template_name="home.html"), name="home")

/// attempt 2 ///
url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout')

/// attempt 3 ///
path("logout/", LogoutView.as_view(), name="logout")

/// attempt 4 ///
path('logout/', views.logout_view, name='logout')

```

Changing user_views.py:
```
/// attempt 1 ///
from django.shortcuts import redirect
from django.contrib.auth import logout

/// attempt 2 ///
def logout_view(request):
    username = UserLoggedIn(request)
    if username != None:
        logout(request)
        return redirect(your_home_view_here)
```

**Paste a link to your repository here**
https://github.com/angel-zh/django-pawsitters

**Comment by amishizaki** [comment]
also, we tried changing settings.py like this (from TokenAuth to BasicAuth):
```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication'
    ]
```

**Comment by sam-phillips21** [comment]
5 hours of auth issues!

**Comment by kestler01** [comment]
resolved with super user ?

**Comment by amishizaki** [comment]
The use of React negates the need to use Django's interface with a "regular" user logins. We were trying to do more than was needed or possible with Django as a backend.
