### ISSUE TITLE
Help making code drier (if possible)

### ISSUE THREAD

**Issue by mattd0512** [sei-ec-remote/project-4-issues#169]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
mongoose + react

### What's the problem you're trying to solve?
Help making code drier. 

### Post any code you think might be relevant (one fenced block per file)
```router.get('/NFL', (req, res) => {
	axios({
        method: "GET",
		url: 'https://sportspage-feeds.p.rapidapi.com/conferences',
        params: {league: "NFL"},
        headers: {
            'X-RapidAPI-Key': '',
            'X-RapidAPI-Host': 'sportspage-feeds.p.rapidapi.com'
        }
	})
        .then(handle404)
		.then(response => {
			res.status(200).json(response.data);
		})
		.catch((err) => {
			res.status(500).json({ message: err });
		});
});
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
The code above displays the conferences for the NFL. I want to make it to where I can display conferences for the NBA, MLB, NHL, NCAAF, and NCAAB. Do I need to repeat that code for all the leagues or is there a way display conferences for each league without having to repeat that code for each league.

### What is your best guess as to the source of the problem?
My best guess is to repeat that code.

### What things have you already tried to solve the problem?
Not much I'm limited to 20 calls to the API per day.

**Paste a link to your repository here**
https://github.com/mattd0512/Sportz-Data-api

**Comment by kestler01** [comment]
use a variable to insert a different string into the parameters ... 
only 20 requests per day is a big 'oof' : so if you want to use this api for your project - you may want your backend to hit this other api a set amount of times a day to get the data saved to your db to serve up.
