### ISSUE TITLE
Getting error with API

### ISSUE THREAD

**Issue by megwelch** [sei-ec-remote/project-4-issues#170]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Trying to access a single tv show from API

### Post any code you think might be relevant (one fenced block per file)
```
const TvShow = () => {
    const { id } = useParams()
    const [show, setShow] = useState([])

    useEffect(() => {
        console.log(id)
        const fetchData = async () => {
            console.log('id', id)
            const res = await axios.get(`https://api.tvmaze.com/shows/${id}`)
            console.log(res)
            setShow('show', res.data)
        };
        fetchData();
    }, []);

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

Access to XMLHttpRequest at 'https://api.tvmaze.com/shows/:1' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
xhr.js:210          GET https://api.tvmaze.com/shows/:1 net::ERR_FAILED 404

### What is your best guess as to the source of the problem?

I believe I might be calling the API incorrectly

### What things have you already tried to solve the problem?

I've tried to rewrite the function multiple ways

**Paste a link to your repository here**
https://github.com/megwelch/Project-4_Front-End

**Comment by aishcann** [comment]
Have you googled your error? What are some solutions / suggestions that come up?

**Comment by kestler01** [comment]
CORS policy: No 'Access-Control-Allow-Origin' : "new number who dis". / stranger danger : the api version
Did your access key in the header like for your index

**Comment by megwelch** [comment]
I have googled the error and have been researching CORS for a good while but haven't been able to find a solution that works. I am confused because this API works for me when accessing all of the tv shows so I don't understand what the difference is when trying to access only one show.

**Comment by aishcann** [comment]
Okay. I'm also noticing that it is trying to pull data from this url: `https://api.tvmaze.com/shows/:1`. Note the `/:1` at the end. Is this the endpoint you are trying to hit, or should it simply be `/1`?

**Comment by megwelch** [comment]
Thank you, that was the issue.

solution
```
const { id } = useParams()
const sliceId = id.slice(1, id.length)
```
