### ISSUE TITLE
Need help debugging

### ISSUE THREAD

**Issue by emilybernard1** [sei-ec-remote/project-4-issues#172]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I keep getting breaking errors when trying to do npm start on the front end. Right now, these bugs are hindering me from moving forward at all.

### Post any code you think might be relevant (one fenced block per file)
```
import SantasSecrets from "./secrets/ShowSantasSecrets";

const MessageOffCanvas = (props) => {

  const { wishList, user, msgAlert, setUpdated } = props
  const santasSecrets = wishList.santasSecrets
  console.log('this is wishlist in props\n', wishList)
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
ERROR in ./src/components/shared/MessageOffCanvas.js 7:0-56

Module not found: Error: Can't resolve './secrets/ShowSantasSecrets' in '/Users/emilybare/sei_monster_mash/projects/santas-helper/src/components/shared'
```
and
```
ERROR in ./node_modules/cloudinary/lib-es5/api_client/execute_request.js 5:52-67

Module not found: Error: Can't resolve 'http' in '/Users/emilybare/sei_monster_mash/projects/santas-helper/node_modules/cloudinary/lib-es5/api_client'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
	- install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "http": false }
```

### What is your best guess as to the source of the problem?
I've been trying to trouble shoot this all day. I think it's a pathing problem for the first error that I copy and pasted above. 
For the second error above- I really don't know what the problem is there. I know it pointed me towards a specific spot in the node-modules (which I found) but I'm afraid to touch anything there.

### What things have you already tried to solve the problem?
I tried installing everything that the errors said to install. I've tried to make sure the pathing is correct as well as the export defaults matching the const's. 
I found the following link on stackoverflow about how to Polyfill node core modules in webpack 5, but I don't really understand what to do next and would love some help: 

https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5 

**Paste a link to your repository here**
https://github.com/emilybernard1/santas-helper
https://github.com/emilybernard1/SantasHelperBackEnd

**Comment by aishcann** [comment]
Yes it is more than likely a pathing error for the first error you showed. Double check that you are pointing to the right location. Maybe it's a `../` instead of just `./` - or some other small thing you need to change.

For the second, try deleting your `package-lock.json` and your `node_modules`, then run `npm i` again. This may fix it.

**Comment by emilybernard1** [comment]
I figured out some of the pathing but there are two problems still. I know exactly where they are, but I can't for the life of me figure out what to type exactly to fix the problem. Would you mind giving me a second set of eyes?
<img width="825" alt="Screen Shot 2022-11-22 at 2 58 51 PM" src="https://user-images.githubusercontent.com/77028684/203420031-d6a7acb2-b68f-4003-9a39-13e506954ac6.png">
<img width="830" alt="Screen Shot 2022-11-22 at 2 59 53 PM" src="https://user-images.githubusercontent.com/77028684/203420144-38c7d5a3-481f-4348-a3b7-8ce58563d4d1.png">

**Comment by emilybernard1** [comment]
I also deleted package-lock.json and node_modules, then ran npm i again. I still got errors related to cloudinary so I did npm install cloundinary and I'm getting other cloudinary errors now.

**Comment by emilybernard1** [comment]
I found this link as well: https://webpack.js.org/migrate/5/#clean-up-configuration

**Comment by emilybernard1** [comment]
Aisha helped me solve all my pathing problems! The rest of the errors have to do with cloudinary, so I'm going to talk to Sarah and also look at the things Aisha sent me about cloudinary to see if I can figure that part out.
