### ISSUE TITLE
POST 404 and 400 error for reviews

### ISSUE THREAD

**Issue by melsil11** [sei-ec-remote/project-4-issues#175]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

DR(django + react),

### What's the problem you're trying to solve?
When I create a review for a petsitter I get a 404 not found on the server side. I was able to create reviews before I dropped my database and remade users. 

### Post any code you think might be relevant (one fenced block per file)
```
React side 
/ CREATE a booking - token required
export const bookingCreate = (user, petSitter, newBooking) => {
	const ownerId = { owner: user._id }
	const booking = {...newBooking, ...ownerId}

	return axios({
		url: `${apiUrl}/bookings/${petSitter.owner}/`,
		method: 'POST',
		data: { booking: booking }
	})
}

Django side 
view
 def post(self, request, pk):
        print('request.data', request.data)
        """Create request"""
        # serializer = ReviewMadeSerializer
        review = get_object_or_404(Review, pk=pk)
        request.data['review']['owner'] = request.user.id
        review = ReviewSerializer(data=request.data['review'])
        if review.is_valid():
            review.save()
            return Response({ 'review': review.data }, status=status.HTTP_201_CREATED)
        return Response(review.errors, status=status.HTTP_400_BAD_REQUEST) 

url 
path('reviews/<int:pk>/', ReviewDetailView.as_view(), name='review'),
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
404 reviews/2/ not found 

### What is your best guess as to the source of the problem?
That it was not getting the correct pk 

### What things have you already tried to solve the problem?
I have moved the post into the other class in the views , changed serializers, change urls on react side, changed the model to include owner and made sure that the requests match the model in django. Now I am getting a 404 bad request error

**Paste a link to your repository here**[
](https://github.com/melsil11/react-pawsitters/blob/reviewsnamechange/src/api/review.js)[
](https://github.com/melsil11/django-pawsitters)

**Comment by melsil11** [comment]
sorry, I realized I put the books react code in not the reviews create axios call
```
// CREATE a review- token required
export const reviewCreate= (user, petsitterOwner, petownerId, reviewCreate) => {
    // console.log('user', user)
    // console.log('petsitter', petsitterOwner)
	const ownerId = { owner: user.id }
	const review = {...reviewCreate, ...ownerId, ...petsitterOwner, ...petownerId}

	return axios({
		url: `${apiUrl}/reviews/${petsitterOwner}/`,
		method: 'POST',
        headers: {
			Authorization: `Token ${user.token}`,
		},
		data: { review: review }
	})
}

**Comment by melsil11** [comment]
I drop my database and create a new pet sitter and pet owner. 
I then go to make a review on the react side and it will not let me create a review. My django terminal says 
```
request.data {'review': {'owner': 1, 'comment': '', 'rating': '1', 'image': '', 'pet_sitter': 2, 'pet_owner': 1, 'owner_email': 'mel@admin.com'}}
Not Found: /reviews/
[28/Nov/2022 15:38:50] "POST /reviews/ HTTP/1.1" 404 23
```
If I go to django admin and create an initial review and then go back to react and create a review it allows me to create a review only after there is one made from the django admin

**Comment by timmshinbone** [comment]
Hey Mel is this bug still around? Update the issue with any progress you've made, or close it with a solution if you've found one.

**Comment by melsil11** [comment]
Still no solution

**Comment by timmshinbone** [comment]
Ok, any updates?

**Comment by melsil11** [comment]
I have been looking over the readme's trying to better understand how it is supposed to work through our labs we did in class.  I dropped my data base and I am back to the 404 error

**Comment by timmshinbone** [comment]
Ok, I'll join your breakout room in a few minutes and we can take a look!

**Comment by melsil11** [comment]
Deleted this line from code
```
# review = get_object_or_404(Review, )
```
It was saying there is no object (review) so throw a 404. It wasn't getting a chance to ecreate one.
