### ISSUE TITLE
git pull problem

### ISSUE THREAD

**Issue by nguyenpham207** [sei-ec-remote/project-4-issues#176]
### What's the problem you're trying to solve?

trying to pull from github
### Post any code you think might be relevant (one fenced block per file)
```
 git pull upstream main
From https://github.com/Salam3377/React-Lux-house
 * branch            main       -> FETCH_HEAD
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

```
 git pull upstream main
From https://github.com/Salam3377/React-Lux-house
 * branch            main       -> FETCH_HEAD
```
### What is your best guess as to the source of the problem?
have multiples branch

### What things have you already tried to solve the problem?

```
git pull --rebase
```
**Paste a link to your repository here**
https://github.com/Salam3377/React-Lux-house/tree/main/src

**Comment by scarletpuma** [comment]
Make sure you've pushed any changes you've made before you pull down, and that you're in your main branch when you try to pull from it.

**Comment by nguyenpham207** [comment]
I pushed and everything.

**Comment by scarletpuma** [comment]
Can you send a screencap of your terminal?

**Comment by nguyenpham207** [comment]
![Screen Shot 2022-11-28 at 7 19 01 AM](https://user-images.githubusercontent.com/110972681/204314315-5678a121-0cbf-4225-b8d7-ac2bdf827bc1.png)

**Comment by nguyenpham207** [comment]
solution: Me and my partner have two working branch
![Screen Shot 2022-11-28 at 7 40 51 AM](https://user-images.githubusercontent.com/110972681/204319389-0f97a359-ddfa-47ef-9a56-453dab76aaea.png)
es and it created a merge conflict.
