### ISSUE TITLE
Having trouble getting favorite TV shows

### ISSUE THREAD

**Issue by megwelch** [sei-ec-remote/project-4-issues#178]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
trying to get favorited tv shows to display

### Post any code you think might be relevant (one fenced block per file)
```
router.get('/favorites', (req, res, next) => {
    TvShow.find({ owner: req.user.userId })
        .populate("owner")
        .then(tvShows => {
			console.log(tvShows)
            return tvShows.map((tvShow) => tvShow.toObject())
        })
        .catch(next)
})
```
```
    useEffect(() => {
        favoritesIndex()
            .then(res=> {
                setAllFavorites(res.data.favorites)
            })
            .catch((error) => {
                msgAlert({
                    heading: "Failure",
                    message: "Failed to find favorites" + error,
                    variant: "danger"
                })
            })
    }, [])
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
TypeError: Cannot read properties of undefined (reading 'userId')

### What is your best guess as to the source of the problem?
I understand that userId is not defined, but I am confused on how to connect it to the userId

### What things have you already tried to solve the problem?
I've gone back to project 2 and tried to rewrite my code based on how I was able to display the users cocktails but it is still not working. Also have been googling for a while to find a solution

**Paste a link to your repository here**
https://github.com/megwelch/Project-4_Front-End
https://github.com/megwelch/Project-4_Back-End

**Comment by scarletpuma** [comment]
Have you tried ._Id instead of .userId?

Make sure you're console.logging to see where your code is breaking/what variables it's not grabbing.

**Comment by timmshinbone** [comment]
I think your `/favorites` route is _missing something_. Look back at the notes to see where `req.user` comes from, because it's having trouble reading that part of the request. The initial problem('cannot read "userId" of `undefined`') means that it doesn't know what `req.user` is

**Comment by megwelch** [comment]
solution: needed require token
```
router.get('/favorites', requireToken, (req, res, next) => {
    // req.params.id will be set based on the `:id` in the route
	console.log('req inside of favorites index', req)
    TvShow.find({owner: req.user.id})
        .populate('owner')
        .then(handle404)
        // if `findById` is succesful, respond with 200 and "post" JSON
        // .then((tvShow) => res.status(200).json({ tvShow: tvShow.toObject() }))
        .then(tvShow => {
            res.status(200).json({ tvShow: tvShow})
        })
        // if an error occurs, pass it to the handler
        .catch(next)
})
```
```
export const favoritesIndex = (user) => {
	return axios({
		method: 'GET',
		url: apiUrl + `/favorites`,
        headers: {
			Authorization: `Token token=${user.token}`,
		},
	})
}
```
