### ISSUE TITLE
Trying to add to array

### ISSUE THREAD

**Issue by hewinsonj** [sei-ec-remote/project-4-issues#181]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
I'm trying to add id's to an array 

### Post any code you think might be relevant (one fenced block per file)
```
    const defaultTest = {
        name: '',
        question_new: [],
    }

```
```
if (updatedName === 'question_new' && target.checked) {
                updatedValue =  (e.target.value).push(parseInt(target.id))
            }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

e.target.value.push is not a function

### What is your best guess as to the source of the problem?

the function isn't aware that the (e.target.value) is an array

### What things have you already tried to solve the problem?
I've tried wrapping (e.target.value) in square brackets, I've tried .append and I've tried wrapping both (e.target.value) and parseInt(target.id) in curly brackets.

**Paste a link to your repository here**
(https://github.com/hewinsonj/Testaurant-Back-end)

**Comment by kestler01** [comment]
lets try console.logging the e.target in the function before we try our push and see what we get

**Comment by hewinsonj** [comment]
```
this is the test from testAdd 
{name: 'Hot Dog', question_new: Array(0)}
name
: 
"Hot Dog"
question_new
: 
[]
[[Prototype]]
: 
`Object`
```

**Comment by hewinsonj** [comment]
The key I'm trying to add to comes back as an empty array before trying to add to it.

**Comment by hewinsonj** [comment]
I was mutating the value of the checkbox every time my 'handleChange' function was triggered. I was also using over complicated syntax.
