### ISSUE TITLE
Semantic UI dropdown unable to get value

### ISSUE THREAD

**Issue by harrisimon** [sei-ec-remote/project-4-issues#182]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
Trying to get a Semantic UI dropdown to have a recognized value for handleChange
https://react.semantic-ui.com/modules/dropdown/#types-multiple-search-selection

### Post any code you think might be relevant (one fenced block per file)
```js
<Dropdown
	required
	fluid
	multiple
	search
	selection
	placeholder="Illustrators"
	name="illustrators"
	options={illustrators}
	label="Illustrator(s)"
	onChange={handleChange}
/>



	const handleChange = (e) => {
		console.log("value?", e.target.value)
		setComic((prevComic) => {
			const name = e.target.name
			let value = e.target.value
			const updatedComic = {
				[name]: value,
			}
			return {
				...prevComic,
				...updatedComic,
			}
		})
		console.log(comic)
	}


	let illustrators = res.data.illustrators
	console.log("the res", illustrators)
	const illustratorOptions = illustrators.map(
		(illustrators, index) => ({
			key: index,
			value:
				illustrators.first_name +" " +illustrators.last_name,
			text:
			        illustrators.first_name +" " +illustrators.last_name,
					})
				)
				setIllustrators(illustratorOptions)
				console.log(illustrators)

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error but trying to figure out how to extract the value for handleChange--it doesn't appear and only appears as a span with innerText to select

### What is your best guess as to the source of the problem?
Trying to figure out how to add the value / track it. It seemingly adds when mapping the options for for some reason that doesn't come through

### What things have you already tried to solve the problem?
Bunch of googling and doc reading, asking group members

**Paste a link to your repository here**
https://github.com/OHammerpaw/react-comics

**Comment by timmshinbone** [comment]
Doesn't look like you're setting `value=` anywhere in the `<Dropdown/>` along with the rest of the attributes. What happens when you try to console log the value?

**Comment by harrisimon** [comment]
It's undefined. I tried setting a value in the dropdown but it needs to be mapped to the options. In the example they give they have the value mapped in the options.

**Comment by harrisimon** [comment]
Decided to abandon semantic dropdowns in favor of React Select npm https://react-select.com/home
Additionally I needed to create a handleChange for each dropdown
