### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by megwelch** [sei-ec-remote/project-4-issues#183]
*** I was in office hours tonight and Aisha suggested putting in this issue now to discuss in the morning

###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I was trying to get reviews to display them , however, after talking with Aisha, because the API with the tv shows is on the front-end, there is nothing in the back-end to attach the reviews to so I am stuck on whether there is a solution to this or whether I need to scrap the API and just seed the tv show data.

### Post any code you think might be relevant (one fenced block per file)
```
router.get('/reviews/:showId', (req, res, next) => {
    const showId = req.params.showId
    Review.find({tvShow: showId})
        .populate("owner")
        .then(reviews => {
            return reviews.map((review) => review.toObject())
        })
        .catch(next)
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error, review GET route is not working due to the tv shows not being on the backend

### What is your best guess as to the source of the problem?
I think I may have to seed my data

### What things have you already tried to solve the problem?
I haven't tried to seed the data yet because Aisha suggested I talk to Timm or Beth in the morning first

**Paste a link to your repository here**
https://github.com/megwelch/Project-4_Front-End
https://github.com/megwelch/Project-4_Back-End

**Comment by timmshinbone** [comment]
Can you send me a link to the API you're using? Also, share one of the pieces of code you're using on the front end to retrieve the API data, as well as your reviews model from your backend. After I take a look at those, I'll head to your breakout room with a plan!

**Comment by megwelch** [comment]
API link: https://www.tvmaze.com/api

API code block to get individual tv show:
```
const TvShow = ({ user: user }) => {
    const { id } = useParams()
    const sliceId = id.slice(1, id.length)
    const [show, setShow] = useState(null)

    useEffect(() => {
        const fetchData = async () => {
            const res = await axios(`https://api.tvmaze.com/shows/${sliceId}`)
            setShow(res.data)
            console.log('show', show)
        };
        fetchData();
    }, []);

    if (!show){
        return <div>Loading...</div>
    }

    let summary = show.summary.replace(/<\/?[^>]+>/gi, '')
```

Review routes (haven't done anything with update or delete yet):
```
///////GET route to INDEX reviews by show//////
router.get('/reviews/:showId', (req, res, next) => {
    const showId = req.params.showId
    Review.find({tvShow: showId})
        .populate("owner")
        .then(reviews => {
            return reviews.map((review) => review.toObject())
        })
        .catch(next)
})

////POST route to CREATE review//////////
router.post('/reviews/:showId', requireToken, (req, res, next) => {
	// set owner of new example to be current user
	req.body.review.owner = req.user.id
    Review.create(req.body.review)
        .then(review => {
            TvShow.findById(review.tvshow)
                .then(tvshow => {
                    res.status(201).json({ review: review.toObject() })
                })
                review.save()
        })
        .catch(next)
})
```

**Comment by kestler01** [comment]
is this an active issue Meghan ?
