### ISSUE TITLE
400 Posting error from React to Django but posting in Django works

### ISSUE THREAD

**Issue by skbarbee** [sei-ec-remote/project-4-issues#185]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

DR
### What's the problem you're trying to solve?
When I try to post from React and I get a 400 error

### Post any code you think might be relevant (one fenced block per file)
```
export const authorCreate = (data) => {
	console.log('this is the data',JSON.stringify(data))
	return axios({
		method: 'POST',
		url: apiUrl + '/authors/',
		data: {
			author: JSON.stringify(data),
		},
		// headers: {
		// 	Authorization: `Token token=${user.token}`,
		// },
	})
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
It gives be a 400 error

### What is your best guess as to the source of the problem?
I've console logged the data and it's right, so I think it must be something I don't know about going from javascript to python. 

### What things have you already tried to solve the problem?
I tried making the data into JSON then sending it but that didn't change, I made sure the data looked correct, and I googled posting through axios to django but haven't found a solution yet. 

**Paste a link to your repository here**
https://github.com/OHammerpaw/react-comics
![Screen Shot 2022-11-28 at 8 46 30 PM](https://user-images.githubusercontent.com/112960135/204553755-dcf3750f-e438-4d1e-a24c-57a69aba556c.png)
![Screen Shot 2022-11-28 at 8 55 25 PM](https://user-images.githubusercontent.com/112960135/204553759-6128c551-de8b-4cb1-91f6-2109d8accc37.png)
![Screen Shot 2022-11-28 at 8 57 11 PM](https://user-images.githubusercontent.com/112960135/204553761-231b3d15-a452-4744-be73-2bdd7c693fe1.png)

**Comment by timmshinbone** [comment]
Might sound weird, but, what does the data look like before being `JSON.stringified`? Also, what data is that table expecting?

**Comment by skbarbee** [comment]
So I took out the JSON.stringified, for now. It was just turning the first_name from first_name: "Sarah" to "first_name": "Sarah". 
Which I thought would work because when I post on the backend 
```
{
    'first_name': 'Sarah'.
    'last_name': 'Barbee' 
}
it creates it, but I only tested with the form and the JSON , when I do the x-www-form-urlencoded (which I think axios is?) It tells me the fields are required , so IDK if that could be the problem, but it doesn't work with or without the stringify

**Comment by skbarbee** [comment]
This is what the api is getting

![Screen Shot 2022-11-29 at 10 42 49 AM](https://user-images.githubusercontent.com/112960135/204575435-4df44245-0ab8-4603-9057-74c4bf097a69.png)

**Comment by skbarbee** [comment]
FRONT END API

```
export const authorCreate = (data) => {
	console.log('this is the data for create author', data.first_name, data.last_name)
	return axios({
		method: 'post',
		url: apiUrl + '/authors/',
		data: {
			author:
			{first_name: data.first_name,
			last_name: data.last_name}
				
		
		},
		headers: {
			'Content-Type' : 'application/json'
		},
	})
}
```
BACKEND VIEW
```
	def post(self, request):
		serializer = AuthorSerializer(data=request.data['author'])
		print('this is the author create\n', request.data['author'])
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
		
```
