### ISSUE TITLE
Objects will POST but won't save the nested models

### ISSUE THREAD

**Issue by hewinsonj** [sei-ec-remote/project-4-issues#186]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
I'm trying to create 'tests' that have 'questions' as a many to many relationship. I am getting a 201 successful and the 'tests' ARE being created but the 'questions' are not saving with the new 'test'. 

### Post any code you think might be relevant (one fenced block per file)
```
[29/Nov/2022 01:09:54] "POST /test_thiss/ HTTP/1.1" 201 154
```
API route
```

export const createTest = (user, test) => {
    console.log(test, 'this be the test right before my api request')
    return axios({
        method: 'POST',
        headers: {
            Authorization: `Token ${user.token}`
        },
        url: apiUrl + '/test_thiss/',
        data: {
            "test_this": {
                "name": test.name,
                "question_new": test.question_new,
            },
        }
    })
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
That's the thing, it says it's posting successfully. No error messages

### What is your best guess as to the source of the problem?
Not sure, but I think it could be something to do with authorization since I can create a test that saves(with questions) from the admin page.

### What things have you already tried to solve the problem?
I've tried sending id's instead of whole objects but they come back as a bad request. I've console logged the data being sent right before the api request, I've printed the data right before creating the 'test' and both the log and the print show that the full 'question' objects are being sent. 

**Paste a link to your repository here**
(https://github.com/hewinsonj/Testaurant-Back-end)

**Comment by timmshinbone** [comment]
What's the model look like? Share it here

**Comment by hewinsonj** [comment]
```

from django.db import models
from django.contrib.auth import get_user_model
from .question_new import Question_new

# Create your models here.
class Test_this(models.Model):
  # define fields
  # https://docs.djangoproject.com/en/3.0/ref/models/fields/
    name = models.CharField(max_length=1000)
    question_new = models.ManyToManyField(Question_new)
    owner = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    
    

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        # This must return a string
        return f"{self.name}"

    def as_dict(self):
        """Returns dictionary version of Test models"""
        return {
            'id': self.id,
            'name': self.name,
            'created_at': self.created_at,
            'updated_at': self.updated_at
        }

```

**Comment by kestler01** [comment]
just wanted to check in and see if this is still an active issue team

**Comment by hewinsonj** [comment]
Oh it's active alright! REAL active! lol

**Comment by hewinsonj** [comment]
Pretty sure the problem is that I'm creating a new entry to my test_this table but nothing is save to the through table that connects the test with the questions.
