### ISSUE TITLE
Getting TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by mattd0512** [sei-ec-remote/project-4-issues#188]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
Mongoose + react

### What's the problem you're trying to solve?
Im getting the error "TypeError: Cannot read properties of null" after running npm start

### Post any code you think might be relevant (one fenced block per file)
```  67 | <Col style={col1Style}>
  68 |     <Card style={cardCSS}>
  69 |         <Card.Header style={cardHeader}>
> 70 |             <h4 style={boldText}>{nfl.conference}</h4>
     | ^  71 |         </Card.Header>
  72 |         <Card.Body>
  73 |             <Card.Text>
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
TypeError: Cannot read properties of null (reading 'conference')

### What is your best guess as to the source of the problem?
My best guess is I'm missing something on my show file or missing something using axios in react.

### What things have you already tried to solve the problem?
I've tried reading documentation, and making minor changes but i'm still stuck on this particular error 

**Paste a link to your repository here**
https://github.com/mattd0512/Sportz-Data-api

**Comment by scarletpuma** [comment]
Can you push up your code so we can see your recent changes?

**Comment by mattd0512** [comment]
Code pushed up and this is the one I'm working in https://github.com/mattd0512/Sportz-Data-client

**Comment by scarletpuma** [comment]
Try conditionally rendering -- it's trying to run your useEffect and your return at the same time.

**Comment by mattd0512** [comment]
So i added this 
``` if (!nfl) {
        return (
            <>
                <div style={backgroundCSS}>
                    <Container style={findingResult}>
                        <p>Finding conferences</p>
                        <p>
                            <Spinner animation='border' style={spinnerCSS}>
                            </Spinner>
                        </p>
                    </Container>
                </div>
            </>
        )
    }
``` 
and now I'm getting "TypeError: Cannot read properties of undefined (reading 'token')". I'm not sure if I used requiretoken correctly in the backend.

**Comment by kestler01** [comment]
is this still an active issue Matthew ? have we solved it with the react links like we discussed ?
