### ISSUE TITLE
Check box bug

### ISSUE THREAD

**Issue by emilybernard1** [sei-ec-remote/project-4-issues#189]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN and DR

### What's the problem you're trying to solve?
I have a check box that I can't edit. Once checked, it's always checked

### Post any code you think might be relevant (one fenced block per file)
```
import React from "react";

const GiftCheckBox = ({ label, value, onChange }) => {

    return (
        <label>
            <div>
                <input
                    type="checkbox"
                    checked={value}
                    label="Has this item been bought?"
                    name="isBought"
                    onChange={onChange}
                />
            </div>
            {label}
        </label>
    )
}

export default GiftCheckBox


```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
VM668 react_devtools_backend.js:4026 Warning: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.

### What is your best guess as to the source of the problem?
The dev tools say it needs an onChange, but it has one, so I'm confused. 

### What things have you already tried to solve the problem?
I've been combing through my code and the boilerplate I used, trying to see where the difference is, but I haven't found it yet.

**Paste a link to your repository here**
https://github.com/emilybernard1/santas-helper

**Comment by kestler01** [comment]
check boxes are tricky : 
see the dmn docs here it may help clear things up - but also, it is a wanring so if it's working as intended i wouldn't worry so much unless it's the absolute last thing to get done 

---

[checked](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#attr-checked)
A Boolean attribute indicating whether this checkbox is checked by default (when the page loads). It does not indicate whether this checkbox is currently checked: if the checkbox's state is changed, this content attribute does not reflect the change. (Only the [HTMLInputElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement)'s checked IDL attribute is updated.)

**Comment by emilybernard1** [comment]
I think it might be the very last thing at this point. With the state of my health at this moment, I think I might need to stop at this point and call it good. It's fully functional other than that in the MERN stack. I had ALMOST gotten the back end working with Django and Python but I'm getting diminishing returns now because of my health. So, I might need to revisit that idea later.

**Comment by kestler01** [comment]
ok, don't worry to much about it: i hope you get well soon

**Comment by emilybernard1** [comment]
Thank you so much.

**Comment by emilybernard1** [comment]
Fixed with John in TA office hours
