### ISSUE TITLE
Connecting favorites to user and authors to related works

### ISSUE THREAD

**Issue by OHammerpaw** [sei-ec-remote/project-4-issues#191]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
Trying to decide how to move forward in regards to our favorites functionality. We want to have users be able to 'favorite' an author, that author is pushed to favorite_authors. Trying to decide if it makes more sense for the favorite_authors field to exist on a separate Favorites table or just add it to the user table. Also, on that author's show page the user would be able to see all of the comics they have attributed to them, so trying to figure out how to do a get call to show the relations between tables.

### Post any code you think might be relevant (one fenced block per file)
```
from django.db import models
from .author import Author
from .illustrator import Illustrator
from .character import Character
from .publisher import Publisher


class Favorite(models.Model):
    user = models.ForeignKey(
        'User',
        null=True, blank=True,
        on_delete=models.CASCADE,
      
    )
    author = models.ForeignKey(
        Author,
        null=True, blank=True,
        on_delete=models.CASCADE,
       
    )
    illustrator = models.ForeignKey(
        Illustrator,
        null=True, blank=True,
        on_delete=models.CASCADE,
       
    )
    character = models.ForeignKey(
        Character,
        null=True, blank=True,
        on_delete=models.CASCADE,
        
    )
    publisher = models.ForeignKey(
        Publisher,
        null=True, blank=True,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        'User',
        null=True, blank=True,
        on_delete=models.CASCADE,
    )

    def __str__(self):
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error message, no behavior at all yet

### What is your best guess as to the source of the problem?
We are just a bit stuck- I am sure we could all solve this given enough time, but we are a little under the gun at the moment.

### What things have you already tried to solve the problem?
We have looked at the django docs and the django rest framework docs along with several articles trying to decide what to do next

**Paste a link to your repository here**
[(https://github.com/OHammerpaw/django-comics)]
[(https://github.com/OHammerpaw/react-comics)]

**Comment by kestler01** [comment]
Hey, so this is a great potential solution for the many to many relationship and mimics whats going on in the database ( join table therefore join model )- but not the easiest of them. 
Have we tried implementing the many_to_many field yet instead ( lets django worry about the join table and make it for us ) ? 
[docs](https://docs.djangoproject.com/en/4.1/topics/db/examples/many_to_many/)

**Comment by OHammerpaw** [comment]
We have looked at that same documentation earlier and utilized the ManyToMany on our comic book model to link multiple authors, illustrators, and characters to a single comic. 
The issue that we are running into is say calling an author and seeing all of the related comics. We haven't found any documentation that explains that very clearly.
It looks like we would use some sort of filter, but we are unsure how to make that into an API call.
We believe the same principle would apply to the favorites.

```
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from .author import Author
from .character import Character
from .publisher import Publisher
from .illustrator import Illustrator

class ComicBook(models.Model):
    title = models.CharField(max_length=100)
    edition = models.IntegerField(validators=[MinValueValidator(0)])
    release_date = models.DateField(null=True, blank=True)
    publisher = models.ForeignKey(
      Publisher,
      on_delete=models.CASCADE,
      related_name='published_comics'
    ) 
    authors = models.ManyToManyField('Author')
    illustrators = models.ManyToManyField('Illustrator')
    characters = models.ManyToManyField('Character')
    cover = models.CharField(max_length=200, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}"
```

**Comment by kestler01** [comment]
might help : https://docs.djangoproject.com/en/4.1/topics/db/queries/#lookups-that-span-relationships

**Comment by OHammerpaw** [comment]
```
def get(self, request, pk):
		author = get_object_or_404(Author, pk=pk)
		comics_written = author.comics.filter(id=pk)
		print('this is the comics written\n', comics_written)
		serializer = AuthorSerializer(author)
		c_serializer = ComicBookReadSerializer
		print(c_serializer(comics_written,many=True).data)
		return Response(
			{'author': serializer.data , 
			"written":c_serializer(comics_written,many=True).data
			}
		)
```
