### ISSUE TITLE
Cannot read properties of name in SantasSecretsForm

### ISSUE THREAD

**Issue by emilybernard1** [sei-ec-remote/project-4-issues#192]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I can't get the page to render again when I click the "send message to Santa" button. In the console in the dev tools, it says "Cannot read properties of name " but I really don't understand why. This was working yesterday.

### Post any code you think might be relevant (one fenced block per file)
```
import React from 'react'
import { Form, Container, Button } from 'react-bootstrap'
import santasSecrets from './ShowSantasSecrets'

const SantasSecretForm = (props) => {
    const { santasSecrets, wishList, handleChange, handleSubmit, heading } = props

    console.log('this is santasSecret in the form\n', santasSecrets)

    return (
        <Container className="justify-content-center" style={{ fontFamily: "Oswald" }}>
            <h3>{heading}</h3>
            <Form onSubmit={handleSubmit}>
                <Form.Label>Name:</Form.Label>
                <Form.Control
                    placeholder="what's your recipient's name?"
                    name="name"
                    id="name"
                    value={santasSecrets.name}
                    onChange={handleChange}
                />
                <Form.Label>Wish List for Santa:</Form.Label>
                <Form.Control
                    placeholder="what would you like Santa to bring this person..."
                    name="secret"
                    id="secret"
                    value={santasSecrets.secret}
                    onChange={handleChange}
                />
                <Button className=" m-3 justify-content-end" type="submit"> Submit </Button>
            </Form>
        </Container>
    )
}

export default SantasSecretForm
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
react-dom.development.js:12056 Uncaught TypeError: Cannot read properties of undefined (reading 'name')

### What is your best guess as to the source of the problem?
I thought the model for santas secrets was missing the "name" property but it's not. So, I don't know what's going on.

### What things have you already tried to solve the problem?
I tried taking out "name" from line 18, then tried passing it through the props. I also tried comparing my code to my boilerplate code, line by line, but I don't seem to be missing anything, so I'm very confused.

**Paste a link to your repository here**
https://github.com/emilybernard1/santas-helper
https://github.com/emilybernard1/santas-helper

**Comment by timmshinbone** [comment]
Remember, 'cannot read property <something> of `undefined`' doesn't necessarily mean that the property doesn't exist, it means that the original object you're trying to read is undefined. So, if you're trying to access the `name` field on the object `santasSecrets` it means that it can't access the object, not the key. 

Share what the output of this console log says:
```js
console.log('this is santasSecret in the form\n', santasSecrets)
```

**Comment by emilybernard1** [comment]
Here's what that console.log came back with: 

```
this is santasSecret in the form
 undefined
```

**Comment by emilybernard1** [comment]
How do I get it to access the object?

**Comment by timmshinbone** [comment]
Where is santasSecret coming from?

**Comment by emilybernard1** [comment]
From santasSecretsForm, I believe.

**Comment by emilybernard1** [comment]
Here's the file for "santasSecretsForm"
```
import React from 'react'
import { Form, Container, Button } from 'react-bootstrap'
import santasSecrets from './ShowSantasSecrets'

const SantasSecretForm = (props) => {
    const { santasSecrets, wishList, handleChange, handleSubmit, heading } = props

    console.log('this is santasSecret in the form\n', santasSecrets)

    return (
        <Container className="justify-content-center" style={{ fontFamily: "Oswald" }}>
            <h3>{heading}</h3>
            <Form onSubmit={handleSubmit}>
                <Form.Label>Name:</Form.Label>
                <Form.Control
                    placeholder="what's your recipient's name?"
                    name="name"
                    id="name"
                    value={santasSecrets.name}
                    onChange={handleChange}
                />
                <Form.Label>Wish List for Santa:</Form.Label>
                <Form.Control
                    placeholder="what would you like Santa to bring this person..."
                    name="secret"
                    id="secret"
                    value={santasSecrets.secret}
                    onChange={handleChange}
                />
                <Button className=" m-3 justify-content-end" type="submit"> Submit </Button>
            </Form>
        </Container>
    )
}

export default SantasSecretForm
```

**Comment by emilybernard1** [comment]
Fixed with John in TA office hours
