### ISSUE TITLE
search bar filter not working

### ISSUE THREAD

**Issue by ange1026** [sei-ec-remote/project-4-issues#194]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN
### What's the problem you're trying to solve?
I'm trying to make a search bar to filter news, but i'm having problems connecting with the API that I'm using.

### Post any code you think might be relevant (one fenced block per file)
```js

const SearchBar = ({articles, description}) => {
    const [searchInput, setSearchInput] = useState('')

    const handleChange = (e) => {
        e.preventDefault();
        setSearchInput(e.data.articles)
    };

    if (searchInput.length > 0) {
        articles.filter((article) => {
            return article.target.match(searchInput);
        });
    }


    return (
        <>
        <Form className="d-flex">
            <Form.Control
              type="search"
              placeholder="Search"
              className="me-2"
              aria-label="Search"
			  style={{borderRadius: '50px', height: '40px'}}
              onChange = {handleChange}
              value = {searchInput}
            />
            <Button variant="primary">Search</Button>
          </Form>
        </>
    )
}

export default SearchBar
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

```
TypeError: Cannot read properties of undefined (reading 'articles')
```
### What is your best guess as to the source of the problem?
I'm not connecting the search bar with the api correctly

### What things have you already tried to solve the problem?

I tried to use 'title' instead of 'articles' but when I was using 'title' the error was: 'filter undefined'
**Paste a link to your repository here**
https://github.com/ange1026/Techy-Client

**Comment by kestler01** [comment]
have we looked at the e.data with a console log yet ?

**Comment by ange1026** [comment]
It says 'e' is undefined
