### ISSUE TITLE
API show page

### ISSUE THREAD

**Issue by Abdisheik3** [sei-ec-remote/project-4-issues#196]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN
### What's the problem you're trying to solve?
I am trying to show the data from my api but its not showing.

### Post any code you think might be relevant (one fenced block per file)
```
const CoinShow = ({ user, msgAlert }) => {

    const [coin, setCoin] = useState(null)
    const [updated, setUpdated] = useState(false)
    const { apiId } = useParams()


    useEffect(() => {
        coinShow(user, apiId)
            .then((res) => {
                setCoin({
                    name: res.data.results.name,
                    id: res.data.results.id
                })
            })
            .catch((error) => {
                msgAlert({
                    heading: 'Failure',
                    message: 'Failure to show coin ' + error,
                    variant: 'danger'
                })
            })
    }, [])

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Failure
Failure to show coin Error: Request failed with status code 500

### What is your best guess as to the source of the problem?
I feel like it has to do with how I wrote the api because I've been getting my data from using the api url and making it into a function.
### What things have you already tried to solve the problem?
I tried changing the api and using the url.

**Paste a link to your repository here**
https://github.com/Abdisheik3/CryptoWatcher-client

**Comment by kestler01** [comment]
have we looked at the backend api terminal and read the specific error it is generating that's triggering the 500 ?

**Comment by Abdisheik3** [comment]
There's no error in the back end terminal for me

**Comment by Abdisheik3** [comment]
GET /coins/undefined
this is what i get now when I click on a coin
