### ISSUE TITLE
database tables issuies

### ISSUE THREAD

**Issue by Salam3377** [sei-ec-remote/project-4-issues#197]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
i had for last 2 days like 10 different issues with databases, i fixed most, but now come once again to something simmlilar like
Programming Error relation already exists

### Post any code you think might be relevant (one fenced block per file)
```
its probably becuase i was creating and adding and deleting a lot trying to make a model to work, so i mademigrations,
deleted, migrated, deleteted database tables and added, it worked but now after some more experiments i broke it again
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "api_cart" already exists

```

### What is your best guess as to the source of the problem?
i was checking database in psql and pgadmin the tables i created did not have id columns, then i did create these, it worked for some time but when i try to add to cart now, in gives me this error that i posted

### What things have you already tried to solve the problem?
like all django, postres docs, and stackoverflow, myself roamed in databases, got lost, got out, got lost again, and thats pretty much my day routine for second day now

**Paste a link to your repository here**
https://github.com/Salam3377/Django-lux-house                It is not updated

**Comment by aishcann** [comment]
When is the last time you dropped your database? That may be the best option.  

Try that and then redo your migrations.

**Comment by Salam3377** [comment]
so should i drop whole database of my app? and then just createdb again and redo migrations?

because i was mostly trying to delete tables in that DB separately

**Comment by aishcann** [comment]
Yes, drop the database. Dropping tables individually rather than the whole database could be causing the issues.

**Comment by Salam3377** [comment]
ok im gonna  do it now

**Comment by Salam3377** [comment]
ok, it worked, thank you!

**Comment by aishcann** [comment]
Glad to hear it!
