### ISSUE TITLE
Not an issue yet but would like to talk to someone about having multiple user types

### ISSUE THREAD

**Issue by patrickga94** [sei-ec-remote/project-4-issues#2]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?

**Paste a link to your repository here**

**Comment by patrickga94** [comment]
Ok it's now an issue, I have two different kinds of users and I'm not sure how to give them both tokens on login

**Comment by patrickga94** [comment]
I...think I fixed it but want to make sure I didn't accidentally break something lol

**Comment by tkolsrud** [comment]
Are you talking about like a normal user and an administrator?

**Comment by patrickga94** [comment]
They're both normal users but have different privileges. One can create/edit/delete happy hours the other can only view/favorite them

**Comment by patrickga94** [comment]
It's currently working but (if possible) I'd like to show you my solution to make sure I didn't mess anything up because I had to change the lib/auth.js file
