### ISSUE TITLE
mapping issue

### ISSUE THREAD

**Issue by clds84** [sei-ec-remote/project-4-issues#20]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN
### What's the problem you're trying to solve?

I'm trying to use another if statement after the map function iterates. I'd like your advice bc what I'm doing might not be the best avenue. I have a projects model that I'm using for users to create projects they're working on. But I'm also using this model for a tutorials component so that the teacher (me) can have a card collection of tutorials that are happening. If users create projects, it gets mixed up with the seeded data I included, userless, and so I'm trying to add an additional if statement in the map iteration to say if there is no user model.owner, then render the cards. 

But now that I'm thinking about it, it seems like a waste of information/data/processing power,  w/e, to run this. Wouldn't I be better off just creating a tutorials model?

### Post any code you think might be relevant (one fenced block per file)
```js
import React, { useState, useEffect } from 'react'
import { getAllTutorials } from '../../api/tutorials'
import { Card } from 'react-bootstrap'
import { Link } from 'react-router-dom'
import {tutorialsIndexSuccess, tutorialsIndexFailure} from '../shared/AutoDismissAlert/messages'


const cardContainerLayout = {
    display: 'flex',
    justifyContent: 'center',
    flexFlow: 'row wrap'
}

const TutorialsIndex = (props) => {
	// const { msgAlert, user } = props
	console.log('props in tutorials index', props)
    const [tutorials, setTutorials] = useState(null)
    const {user, msgAlert } = props
    

    useEffect(() => {
        getAllTutorials(user)
            .then(projects => {
                console.log('this is the project data', projects.data.projects)
                setTutorials(projects.data.projects)
            })
            .catch(() =>
            msgAlert({
                heading: 'Oh No!',
                message: tutorialsIndexFailure,
                variant: 'danger',
        }))
    }, [])

    if (!tutorials) {
        return <p>loading...</p>
    } else if (tutorials.length === 0) {
        return <p>No tutorials as of yet!</p>
    }

    let tutorialsCards 
    
    if (tutorials.length > 0) { 
        
        tutorialsCards = tutorials.map(tutorial => (
           
    
            <Card key={tutorial.id} style={{ width: '30%' }} className="m-2" >
                <Card.Header>{tutorial.type}</Card.Header>
                <Card.Body>
                    <Card.Text>
                        <Link to={`/tutorials/${tutorial._id}`}>Start Tutorial</Link>
                    </Card.Text>
                </Card.Body>
            </Card>
        ))
    }
    
	return (
		<>
        <h3 className='logo'>All my favorite picks</h3>
        <div style={cardContainerLayout}>
            {tutorialsCards}
        </div>
    </>
    )
}

export default TutorialsIndex

```

### What is your best guess as to the source of the problem?
I'm not sure

### What things have you already tried to solve the problem?

I've tried changing up the syntax a few ways and it doesn't seem to work.

**Paste a link to your repository here**
https://github.com/clds84/Project-4-Client

**Comment by timmshinbone** [comment]
Is your API completely done and working? If not DON'T go to react land quite yet.

**Comment by clds84** [comment]
It is. Everything works in Postman. I did an additional model for the light stretch as well, and started on the comments, but def the mvp models are working through and through.

**Comment by timmshinbone** [comment]
ok let me know when you're back from break and I'll jump into your room to debug

**Comment by clds84** [comment]
issue resolved!
