### ISSUE TITLE
Trying to POST an object with a foreign key relationship

### ISSUE THREAD

**Issue by hewinsonj** [sei-ec-remote/project-4-issues#203]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
I'm trying to POST an object with a foreign key relationship

### Post any code you think might be relevant (one fenced block per file)
```
 id | score  | correct | wrong | total | percent | time  |          created_at           |          updated_at           | owner_id | the_test_id 
----+--------+---------+-------+-------+---------+-------+-------------------------------+-------------------------------+----------+-------------
  1 | 89/100 | 89      | 11    | 100   | 89      | 10:00 | 2022-11-30 18:58:32.629419-05 | 2022-11-30 18:58:32.629477-05 |        1 |           1
  2 | 34     | 34      | 11    | 100   | sfd     | 34    | 2022-11-30 18:58:49.235943-05 | 2022-11-30 18:58:49.235987-05 |        1 |           2
(2 rows)

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
integrityError: null value in column "the_test_id" of relation "api_result" violates not-null constraint
```

### What is your best guess as to the source of the problem?
I saw in a video I was watching that you're not supposed to send the 'id' or the whole object when referring to an object that is connected to another object in a foreign key relationship, but that you are supposed to send the instance of that object but I'm not sure how to do that. 

### What things have you already tried to solve the problem?
Everything but giving up.

**Paste a link to your repository here**
(https://github.com/hewinsonj/Testaurant-Back-end)

**Comment by kestler01** [comment]
have we tried adding the field option of allowing null for that? ( does that make sense in this context ? ) 
https://docs.djangoproject.com/en/4.1/ref/models/fields/

**Comment by kestler01** [comment]
it also seems that it may be a repeat of the issue from yesterday : in that your trying to create a relationship with a database entry that doesn't exist in the db yet, so doesn't have an id to associate

**Comment by hewinsonj** [comment]
'it also seems that it may be a repeat of the issue from yesterday : in that your trying to create a relationship with a database entry that doesn't exist in the db yet, so doesn't have an id to associate', this worked. Thanks!
