### ISSUE TITLE
Unable to get favorites to PATCH / PUT

### ISSUE THREAD

**Issue by harrisimon** [sei-ec-remote/project-4-issues#206]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
We're trying to get our favorites to POST or PATCH but both are saying bad request

### Post any code you think might be relevant (one fenced block per file)
```js
export const favoritesPost = (data,user) => {
	return axios({
		method: 'PATCH',
		url:  apiUrl + '/favorites/',
		headers: {
			Authorization: `Token ${user.token}`,
		},
		data : {
			favorites : {
				favorite_authors: data,
				owner: user.id
			},
		}
	})
```
```py
    def patch(self, request):
        """Update Request"""
        # Locate Favorites
        print("the req", request.data)
        print("the user", request.user)
        request.data['favorites']['owner'] = request.user.id
        # get_object_or_404 returns a object representation of our Favorites
        favorites = Favorites.objects.filter(owner=request.user.id)
        # Check the favorites's owner against the user making this request
        # if request.user != favorites.owner:
        #     raise PermissionDenied('Unauthorized, you do not own this favorites')

        # Ensure the owner field is set to the current user's ID
        # Validate updates with serializer
        data = FavoritesSerializer(favorites, data=request.data['favorites'], partial=True)
        if data.is_valid():
            # Save & send a 204 no content
            data.save()
            return Response(status=status.HTTP_204_NO_CONTENT)
        # If the data is not valid, return a response with the errors
        return Response(data.errors, status=status.HTTP_400_BAD_REQUEST)
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
We're getting 400s

### What is your best guess as to the source of the problem?
We're not sure the structure of outgoing data

### What things have you already tried to solve the problem?
We've tried following the user examples for password update

**Paste a link to your repository here**
https://github.com/OHammerpaw/react-comics
https://github.com/OHammerpaw/django-comics

**Comment by harrisimon** [comment]
We also tried making it both put and patch in the detail view but still get bad request

**Comment by kestler01** [comment]
my guess is not that the request itself is bad, but that the data.is_valid() is returning false - looking into your serializer and the data going into it here
