### ISSUE TITLE
Comment wont show

### ISSUE THREAD

**Issue by Abdisheik3** [sei-ec-remote/project-4-issues#207]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
trying to have my comments show up when created.

### Post any code you think might be relevant (one fenced block per file)
```
import React, { useState } from 'react'
import { Card, Button } from 'react-bootstrap'
import { useNavigate } from 'react-router-dom'




const ShowComment = (props) => {
    const { comment, coin, user} = props



    return (
        <>
            <Card className="m-2">
                <Card.Body>
                    <small>{ comment.comment }</small><br/>
                </Card.Body>
                <Card.Footer>
                    { 
                        user && coin.owner && user._id === coin.owner._id 
                        ?
                        <>
                            <Button
                                className="m-2" 
                                variant="warning"
                                onClick={() => setEditModalShow(true)}  
                            >
                                Edit Toy
                            </Button>
                        </>
                        :
                        null
                    }
                </Card.Footer>
            </Card>

        </>
    )
}

export default ShowComment
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

 POST http://localhost:8000/comments/bitcoin 401 (Unauthorized)

### What is your best guess as to the source of the problem?
I feel like I have a spelling error because I doubled checked with the pets app.
### What things have you already tried to solve the problem?
checked my game app and pets app.

**Paste a link to your repository here**
https://github.com/Abdisheik3/CryptoWatcher-client

**Comment by aishcann** [comment]
`401 not authorized` seems like an authentication issue. For the post route, do you have to be logged in to comment? Is it passing the user information to the backend correctly?

**Comment by Abdisheik3** [comment]
Yes you have to be logged in to comment. It's seems like everything should pass correctly.

**Comment by aishcann** [comment]
solved - was not calling token correctly in front end
