### ISSUE TITLE
Wondering if it's possible to create multiple child objects when creating a parent object

### ISSUE THREAD

**Issue by EricCSheppard** [sei-ec-remote/project-4-issues#211]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
Django app

### What's the problem you're trying to solve?
I am attempting to create new child objects automatically when creating a parent object

### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?
I am thinking I will need to iterate over the number of days and submit the numbers and dates that way but I really am just not even sure it's possible at this point and am wondering if it is.

**Paste a link to your repository here**
https://github.com/EricCSheppard/GoAway

**Comment by asands94** [comment]
What specifically are you trying to do?

**Comment by EricCSheppard** [comment]
So I want to create an object (a trip) and when I'm creating the trip, when you indicate the number of days in the trip I'd like to create that many "Day" objects (which are related to the trip).

**Comment by timmshinbone** [comment]
You can totally do that in your controller! Just loop up to the number of days, and for every iteration of the loop, create a new Day object. Check the mongoose docs, I believe the function is insertMany, so, your loop can create those objects(super easy if you define a class) then `insertMany` into your database.

**Comment by EricCSheppard** [comment]
Sadly I'm not using mongoose!  I'm trying to do it in the views.py in my Django project as a custom view.  My idea was basically this, iterate over the "number of days" field of the "trip" and create that many new "days" to be children of the "trip" parent.  I think the issue is I'm not entirely sure how to:
1. save the "trip" so that it has an idea that the "days" can be related to.
2. extract the "number of days" from the form submission to know how many "days" to create

**Comment by timmshinbone** [comment]
No sweat, it's even easier in python, since it's object oriented. So you'll need to submit the form first, then inside that controller or another controller, that's where you can loop through and create new instances of those days. Inside your loop, you can create a new Day object and save it, each time up until the loop stops, and inside the loop when you're creating your day, you can assign the trip id and whatever other specific data you have. Check out python's dateTime and see if you can implement it so that each day created within that loop has a date that is one higher than the last. Like, first iteration makes Monday March, 6th, then Tuesday March 7th, then Wednesday March 8th, so on and so forth.

**Comment by EricCSheppard** [comment]
That is the plan!  The trip has 3 fields "Name" "days" and "Start date".  Plan is to use "days" and "start date" and create a set of objects using that number and start date and iterating down.

I guess the place to do this is in views.py inside of my "create trip" function?

**Comment by timmshinbone** [comment]
Yeah, either there, or you can just have them add the days with a calendar picker that selects those days and creates them using a second view function. Up to you.

**Comment by EricCSheppard** [comment]
So I probably shouldn't try and use the class based view, will need to define a custom function right?

**Comment by timmshinbone** [comment]
Might be able to do it with one, read the docs to find out, but I'd recommend creating a custom one that does exactly what you want it to do.
