### ISSUE TITLE
Question about visibility, authorization, when to lock down screens for logged in users (while still building more)

### ISSUE THREAD

**Issue by tthephas** [sei-ec-remote/project-4-issues#215]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
my admin portal shows things working right. parents have kids, kids have chores. but on regular app, the visibility on the create page is different obviously. i'm wondering if i should do the authorization now or later , to test if app working right. i have more features to build and dont want the logging in and out to get in my way the next 5 days.

### Post any code you think might be relevant (one fenced block per file)
na

```

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

na
### What is your best guess as to the source of the problem?
its not a problem, more of a question about order of how to do things while building

### What things have you already tried to solve the problem?
i didnt authenticate yet , which is my question, when to do that

**Paste a link to your repository here**
https://github.com/tthephas/Chore-Tracker

**Comment by scarletpuma** [comment]
You may want to work on auth first, that way you can get it out of the way now and be able to fix any issues with it interacting with your other features as you build them.

**Comment by tthephas** [comment]
Ok thank you
