### ISSUE TITLE
Create Form not working

### ISSUE THREAD

**Issue by brianaleew** [sei-ec-remote/project-4-issues#216]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
Django 

### What's the problem you're trying to solve?
My form doesnt work after submit is hit 

### Post any code you think might be relevant (one fenced block per file)
```python
#the view:
class ApparelCreate(CreateView):
    model = Apparel
    fields = ['name', 'brand', 'color', 'size', 'img', 'style', 'type']
```
```python
#the url 
path('apparels/create/', views.ApparelCreate.as_view(), name='apparels_create'),
```
```html
{% extends 'base.html' %}
{% block content %}
    <h1>Add to the Closet! </h1>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="type" class="form-label">Apparel Type</label>
        <input
            class="form-control" 
            type="text" 
            name="type"
        >
        <label for="name" class="form-label">Apparel Name</label>
        <input
            class="form-control" 
            type="text" 
            name="name"
            placeholder="What would you like the name of this clothing item to be?"
        >
        <label for="brand" class="form-label">Brand</label>
        <input
            class="form-control" 
            type="text" 
            name="brand"
            placeholder="What brand is the item made by?"
        >
        <label for="color" class="form-label">Color</label>
        <input
            class="form-control" 
            type="text" 
            name="color"
            placeholder="What color/wash does the item have?"
        >
        <label for="size" class="form-label">Size</label>
        <input
            class="form-control" 
            type="text" 
            name="size"
            placeholder="What size is your item? (Ex: small, medium, large, 0, 12, etc.)"
        >
        <label for="style" class="form-label">Style Notes</label>
        <input
            class="form-control" 
            type="text" 
            name="style"
            placeholder="Input Style notes here: (Ex: heel-height: 3inches or sleeve-length: short-sleeve)"
        >
        <label for="img" class="form-label">Apparel Image</label>
        <input
            class="form-control" 
            type="file" 
            name="img"
            aria-describedby="imgHelp"
        >
        <div id="imgHelp" class="form-text">
            Choose an image to represent your clothing item (a.k.a a picture of your clothing item)
        </div>
        

        <input type="submit" value="Submit Form" class="btn btn-danger">
    </form>
{% endblock %}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
[09/Mar/2023 18:33:39] "POST /apparels/create/ HTTP/1.1" 200 4387 (pasted from terminal).
The page refreshes but the item is not created at all when i check the index page. 

### What is your best guess as to the source of the problem?
I have no idea at this point. Maybe my model is messed up? 

### What things have you already tried to solve the problem?
I've redone it, changed names, looked at timms code for catcollector and still confused... 

**Paste a link to your repository here**
https://github.com/brianaleew/GA-Final-Project

**Comment by asands94** [comment]
Are you seeing the apparel in the admin portal?

**Comment by brianaleew** [comment]
yes, I can create apparel from the admin portal as well

**Comment by asands94** [comment]
Sorry, I meant when you use the create form in django and the page refreshes, are you able to see the new apparel you made in the portal or does it not show up?

**Comment by brianaleew** [comment]
oh no, it doesnt show up in the admin portal

**Comment by asands94** [comment]
Ok I just wanted to check that just to see if there was a get request issue or not. It looks like you built this form out yourself instead of letting django make the form for you, that could be the issue

**Comment by brianaleew** [comment]
ok ill try making django make the form for me right now

**Comment by brianaleew** [comment]
ok so it definitely was that! what if we wanted to customize our own form? is it not allowed in django at all?

**Comment by asands94** [comment]
What did you want to customize? But yes you can customize forms in django

**Comment by brianaleew** [comment]
well now I'm a bit confused on how I would style it but also like adding placeholders and stuff like that

**Comment by asands94** [comment]
There are a few ways to add forms, you can also do it in the way we did it for the feeding, so something like this in your forms.py:

```py
from django.forms import ModelForm
from django.forms import TextInput
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    widgets ={
      'name': TextInput(attrs={'placeholder': 'name'})
    }
    fields = ['name','date', 'meal']
```

**Comment by brianaleew** [comment]
oh yes you're so right. Thank you Ashley! 
Solution: I was creating my own form inside my template instead of using django's built in form or creating a custom form using the above code format in a forms.py file.
