### ISSUE TITLE
Need some help rewiring some views. Built them backwards. Not sure of model form needed (like cat collect/feeding)

### ISSUE THREAD

**Issue by tthephas** [sei-ec-remote/project-4-issues#218]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
poor planning led to me building all views backwards. now i need to rework them to fit already built screens. 

### Post any code you think might be relevant (one fenced block per file)
```
  path('parents/', views.parents_index, name='parents_index'),
  path('parents/<int:parent_id>/', views.parents_detail, name='parents_detail'),
  path('parents/create/', views.ParentCreate.as_view(), name='parents_create'),
  path('parents/<int:pk>/update', views.ParentUpdate.as_view(), name='parents_update'),
  path('parents/<int:pk>/delete', views.ParentDelete.as_view(), name='parents_delete'),
  
  path('kids/', views.kids_index, name='kids_index'),
  path('kids/<int:kid_id>/', views.kids_detail, name='kids_detail'),


  path('parents/<int:pk>/kids_create/', views.KidCreate.as_view(), name='kids_create'),


  path('kids/<int:pk>/update', views.KidUpdate.as_view(), name='kids_update'),
  path('kids/<int:pk>/delete', views.KidDelete.as_view(), name='kids_delete'),
  
  
  path('chores/', views.chores_index, name='chores_index'),
  path('chores/create/', views.ChoreCreate.as_view(), name='chores_create'),
  path('chores/<int:chore_id>/', views.chores_detail, name='chores_detail'),
  path('chores/<int:pk>/update', views.ChoreUpdate.as_view(), name='chores_update'),
  path('chores/<int:pk>/delete', views.ChoreDelete.as_view(), name='chores_delete'),
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
errors are b/c i'm rewiring

### What is your best guess as to the source of the problem?
i shoudl have started with parents on all, as they own all accounts, kids, and then chores. but i built backwards. as i rework this, not sure if i should use model form or if that was just b/c we imbedded form for feedings

### What things have you already tried to solve the problem?
fixed on url as you can see above, parent/id/kidscreate
building model form now. but i am not sure what all else i need to fix to reroute

**Paste a link to your repository here**
https://github.com/tthephas/Chore-Tracker

**Comment by asands94** [comment]
What issue are you currently having?

**Comment by tthephas** [comment]
i'm not sure how to rewire/rework/refactor the routes. i'm confused on how to pass the id's . its different than we did in class b/c 1) i'im not using model form and 2) my chores (toys) are not a many to many, so they have a route that is owned by kids, then parents

**Comment by asands94** [comment]
In your chore model, you have a FK referencing kid so you could have a url path that is something like this:
```
 path('kids/<int:kid_id>/add_chore/', views.add_chore, name='add_chore'),
```
This is how you would associate the chore with the kid in general. Is this something like what you were thinking?

**Comment by tthephas** [comment]
yes for example i wrote this to create a kid (associated to a parent). woudl this be correct? is it not a CBV? like "class KidCreate(LoginRequiredMixin, CreateView):" ?  thats where i'm confused. if its a CBV i should/can use or if its a function view

```
# def kids_create(request, parent_id):
#   if form.is_valid():
#   # don't save the form to the db until it
#   # has the cat_id assigned
#   new_feeding = form.save(commit=False)
#   new_feeding.cat_id = cat_id
#   new_feeding.save()
# return redirect('detail', cat_id=cat_id)
```

**Comment by asands94** [comment]
Yes just make sure you have `form = KidForm(request.POST)` or something similar. Something like this should allow you to have a parents page, then on that details page you can add kids

**Comment by tthephas** [comment]
but thats not what i want. i want the user to click "add kid" or "add chore" and it takes them to a new page. that is why i'm confused. in class we did feedings on the same page , but i would like to use the forms i already built if possible.

**Comment by asands94** [comment]
Ok I see, then you should be able to have the kid form on the new page and you just have the form on a different page instead of on the detail page. Because the url that allows for a kid to be added to the parents will be in the form action of the kid form.

**Comment by tthephas** [comment]
ok, but i'm confused, and its not working. right now i'm getting this error even trying to run the app
AttributeError: 'function' object has no attribute 'as_view'

**Comment by tthephas** [comment]
trying to pass the kids id thru to the parent detail page, to match the urls, but still not working
```
def parents_detail(request, parent_id):
  parent = Parent.objects.get(id=parent_id)
  kids = Kid.objects.filter(user=request.user)
  return render(request, 'parents/detail.html', { 'parent': parent, 'kids': kids })
 ```

**Comment by asands94** [comment]
So you would have to change your kid method a bit since you want it on a new page. So using catcollector as an example with feeding and cats. The add feeding medthod could liook like this:

```py
def feeding(request):
    # bring in the cats that the logged in user owns
    cats = Cat.objects.filter(user=request.user)
    feeding_form = FeedingForm()
    # create the ModelForm using the data in request.POST
    form = FeedingForm(request.POST)
    # validate the form
    if form.is_valid():
      # don't save the form to the db until it
      # has the cat_id assigned
      new_feeding = form.save(commit=False)
      new_feeding.cat_id = cat_id
      new_feeding.save()
      # pass in the FeedingForm() so that the form can be seen
      # pass in cats so they can be looped through and a feeding will be displayed for each cat
    return render(request, 'feeding.html', {'cats': cats, 'feeding_form': feeding_form})
```

**Comment by tthephas** [comment]
so its not a CBV? that doesnt look like one.

**Comment by asands94** [comment]
No, I just left it as a custom method like we did with the original add_feeding method

**Comment by tthephas** [comment]
so now i do need a form in the forms py for this i assume?

**Comment by asands94** [comment]
Yeah exactly. This was just a way it made sense to me if wanting to have kids form on their own page

**Comment by tthephas** [comment]
this is not working. wrote like this but i really dont understand how it would work or what info shoudl be in it
```
@login_required
def kids_create(request):

  parents = Parent.objects.filter(user=request.user)
  kids_create = KidForm()
  form = KidForm()
  if form.is_valid():
  # don't save the form to the db until it
  # has the cat_id assigned
  new_kid = form.save(commit=False)
  new_kid.parent_id = parent_id
  new_kid.save()
return redirect('parents_detail', { 'kids': kids })

```

**Comment by tthephas** [comment]
and importing the form from forms.py seemed to screw everything else up below it

**Comment by tthephas** [comment]
rewrote to this below. still getting an error, cant get app to open at all
```
@login_required
def kids_create(request, parent_id):

  parents = Parent.objects.filter(user=request.user)
  kids_create = KidForm()
  form = KidForm(request.POST)
    
  if form.is_valid():
  # don't save the form to the db until it
  # has the parent id assigned
    new_kid = form.save(commit=False)
    new_kid.parent_id = parent_id
    new_kid.save()
  return redirect('parents_detail', { 'parents': parents, 'kids_create': kids_create })
```

**Comment by asands94** [comment]
Since you're using a custom method, you need to change parents_detail to the actual name of the html file so `parents_detail.html` if thats what you called it. Also make sure you return a render and not a redirect. You also need to add in request so `return render(request, ...`

**Comment by tthephas** [comment]
did that and still getting an error. 
re.error: redefinition of group name 'pk' as group 2; was group 1 at position 33

so should it be parents/id/detail.html ? i'm still very confused

**Comment by tthephas** [comment]
i'm still stuck here. able to start passing the right id's thru the forms. but , when i go to create a parent, i get an error when it tries to find that detail page. when i do an index of parents, it does show that i created the parent successfully, so it did post. cannot add kids either, thru the kids create function. error trying to find the parent.

**Comment by tthephas** [comment]
after i create, it fails to load the details page (no reverse found error). but when i go to index, its created, and when i cllick on it, it opens (the url, with the id, works, and renders). i am not sure why it wont render correct after the create, if it renders fine from the index

**Comment by asands94** [comment]
In your model, do you have the `get_absolute_url` method? You'll need that so you can redirect after creating and updating.

**Comment by tthephas** [comment]
yes. tim and i reworked some of the id stuff in the urls. maybe its this "parent_id : self.id" ?
```
class Parent(models.Model):
    name = models.CharField(max_length=50)
    children = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

        # override the str method in models to print better
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('parents_detail', kwargs={'parent_id': self.id})
```

**Comment by asands94** [comment]
It depends on what you have as your url for the parents detail page, can you share that url?

**Comment by tthephas** [comment]
yes it was. ok, thats one down. but still having other issues with the other routes, 

like when i go to update a parent now, this error 

AttributeError at /parents/15/update
Generic detail view ParentUpdate must be called with either an object pk or a slug in the URLconf.

**Comment by asands94** [comment]
Can you share the url for that update route?

**Comment by tthephas** [comment]
path('parents/<int:p_id>/update', views.ParentUpdate.as_view(), name='parents_update'),

**Comment by asands94** [comment]
If its asking for a pk then instead of `int:p_id`, try `<int:pk>`

**Comment by tthephas** [comment]
tim and i just changed all of the pk's over to p_id (or , k_id for kid, or c_id for chores)

**Comment by tthephas** [comment]
ok that worked. so maybe it works for update/delete like that? but not create? now i'll work on the kids routes

**Comment by tthephas** [comment]
when i go to add a kid now, this is the error. 

FieldError at /parents/6/kids_create/
Cannot resolve keyword 'parent' into field. Choices are: children, id, kid, name, user, user_id

and the url 
  path('parents/<int:p_id>/kids_create/', views.kids_create, name='kids_create'),

**Comment by tthephas** [comment]
parent create is still a cbv, and working. kids create we turned into a function, and is not working

**Comment by asands94** [comment]
Yeah for update and delete you'll use the `pk` still. Can you share the kids method

**Comment by tthephas** [comment]
```
# @login_required
# def kids_create(request, p_id):

#   parents = Parent.objects.filter(parent=p_id)

#   kids_create = KidForm()
#   form = KidForm(request.POST)
    
#   if form.is_valid():
#   # don't save the form to the db until it
#   # has the parent id assigned
#     new_kid = form.save(commit=False)
#     new_kid.p_id = p_id
#     new_kid.save()
#   return render(request, 'parents_detail.html', { 'parents': parents, 'kids_create': kids_create })
```

**Comment by tthephas** [comment]
just tried turning it back to CBV as well and its not working

**Comment by tthephas** [comment]
here is my kids create. since i'm not doing it on the same page , like we did cats/feeding, do i even need all this stuff about parents (like we did cats)?
```
@login_required
def kids_create(request, p_id):

  parents = Parent.objects.filter(parent=p_id)
  kids_create = KidForm()
  form = KidForm(request.POST)
    
  if form.is_valid():
  # don't save the form to the db until it
  # has the parent id assigned
    new_kid = form.save(commit=False)
    new_kid.p_id = p_id
    new_kid.save()
  return render(request, 'parents_detail.html', { 'parents': parents, 'kids_create': kids_create })
  ```

**Comment by tthephas** [comment]
when i try CBV i get closer. see below. it just needs the parent id, which is 6, which is in the url. but how do i put into the object?

IntegrityError at /parents/6/kids/create/
null value in column "parent_id" of relation "main_app_kid" violates not-null constraint
DETAIL:  Failing row contains (7, jimmy johns, 1, TEST, 44, null).

**Comment by asands94** [comment]
Have you added in a null=True in the model?

**Comment by tthephas** [comment]
no, where?

**Comment by tthephas** [comment]
i just need to know how to pass the parent id, which is in the url, to the form. i feel like it goes just like. "new_kid = kid.id" up top there, but somehow in a class based view.

**Comment by tthephas** [comment]
maybe right here under form.instance.user , but instead of the user, declaring that the parent is the parent id in the url
```
  def form_valid(self, form):
    # Assign the logged in user (self.request.user)
    form.instance.user = self.request.user
    
    # Let the CreateView do its job as usual
    return super().form_valid(form)
```

**Comment by asands94** [comment]
Thats what i was thinking as well, when you submit the form `form.instance.parent` should relate to the parent field on the kid model

**Comment by tthephas** [comment]
so would it be form.instance.parent = parent? i'm trying a few things

**Comment by tthephas** [comment]
that gave me "Kid has no parent"

**Comment by tthephas** [comment]
cant get it to work. i tried passing the parameter every which way. at this point do you suggest i just do it exactly like tim did in cats? to me , the UX doesnt make sense, but at this point i dont know what other options i have

**Comment by tthephas** [comment]
switched gears on this and trying auth more like the class example
