### ISSUE TITLE
I have a problem with the no URL to redirect to

### ISSUE THREAD

**Issue by blkurd** [sei-ec-remote/project-4-issues#219]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
I am using Django to build my app. I created a form for one of the models and after I click submit on the webpage, not the admin.

### Post any code you think might be relevant (one fenced block per file)

I wrote this code for redirect to the trip index page but it is not working. 

```
def get_absolute_url(self):
    return reverse('trips', kwargs={'trip_id': self.id })
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model. 

### What's the problem you're trying to solve?

Have the form submitted successfully and the page redirects to the trip index page. 

### What is your best guess as to the source of the problem?

I think it is a problem with having and id for a trip but I am not sure. I tried it but did not work. 

### What things have you already tried to solve the problem?

Creating an id in the views for the trips_index.

**Paste a link to your repository here**
https://github.com/blkurd/Travel-Tracker

**Comment by asands94** [comment]
Can you show the whole code for this model please

**Comment by blkurd** [comment]
This is from models.py

`class Trip(models.Model):
   date = models.DateField()
   country = models.CharField(max_length=100) `

This is from urls.py

`path('trips/', views.trips_index, name='trip-index'),
  path('trips/create', views.TripCreate.as_view(), name='trip-create'),`

This is from views.py

`def trips_index(request):
    trips = Trip.objects.all()
    return render(request, 'trips/index.html', {
    'trips': trips})`

`class TripCreate(CreateView):
    model = Trip
    fields = '__all__'
`

and this is the code I wrote for redirect to the trip index page after submiting a form. :

`def get_absolute_url(self):
    return reverse('trips', kwargs={'trip_id': self.id })`

**Comment by asands94** [comment]
Where exactly is this line of code 
```py
def get_absolute_url(self): return reverse('trips', kwargs={'trip_id': self.id })
```

**Comment by blkurd** [comment]
It is in the models.py

**Comment by asands94** [comment]
Do you have any urls where  `name='trips'`?

**Comment by blkurd** [comment]
I fixed to the url `name=trip-index` amd it did not work.

**Comment by asands94** [comment]
You need to have some kinds of page that has `name='trips'` since you put `trips` in your reverse section. The name you put there refers to the page you want users to go to once they submit a form

**Comment by blkurd** [comment]
I tried doing that, not working so far.

**Comment by asands94** [comment]
Can you share your all your urls and your full Trips model

**Comment by blkurd** [comment]
``
from django.urls import path
from . import views

urlpatterns = [ 
# The name='home' kwarg gives the route a name. Naming a route is optional but is considered a best practice.
  path('', views.home, name='home'),

# view.about is from the view file, defined function

  path('about/', views.about, name='about'),

  path('trips/', views.trips_index, name='trips'),
  path('trips/create', views.TripCreate.as_view(), name='trip-create'),

  path('experiences/', views.experiences_index, name='experience-index'),
  path('trips/create', views.ExperienceCreate.as_view(), name='experience-create'),

  path('experiences/<int:experience_id>/', views.experience_detail, name='detail'),

]

``

**Comment by blkurd** [comment]
`
from django.urls import path
from . import views

urlpatterns = [ 
# The name='home' kwarg gives the route a name. Naming a route is optional but is considered a best practice.
  path('', views.home, name='home'),

# view.about is from the view file, defined function

  path('about/', views.about, name='about'),

  path('trips/', views.trips_index, name='trips'),
  path('trips/create', views.TripCreate.as_view(), name='trip-create'),

  path('experiences/', views.experiences_index, name='experience-index'),
  path('trips/create', views.ExperienceCreate.as_view(), name='experience-create'),

  path('experiences/<int:experience_id>/', views.experience_detail, name='detail'),

]

`

**Comment by blkurd** [comment]
`from django.db import models
from django.urls import reverse

# Create your models here.

class Trip(models.Model):
   date = models.DateField()
   country = models.CharField(max_length=100) `

**Comment by asands94** [comment]
If thats your model then where did you put
```py
def get_absolute_url(self): return reverse('trips', kwargs={'trip_id': self.id })
```

**Comment by blkurd** [comment]
Should it not be in the models.py because that's where I can it?

**Comment by blkurd** [comment]
Probelm fixed! 

I had to add ` success_url= '/trips'` to the create view class of the model to that redirects me to the index page of it. Thank you, Ashely!
