### ISSUE TITLE
Questions about using socket.io and data structure/order of operations

### ISSUE THREAD

**Issue by rectorjordan94** [sei-ec-remote/project-4-issues#221]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I'm trying to get the frontend to update the current channel's threads which are displayed whenever a new message(thread) is created using a form, in real-time. I have some ideas about where to implement the code but I just want to make sure that I'm doing things in the right places or following the correct order of operations. 

### Post any code you think might be relevant (one fenced block per file)
```js
    const onSubmit = (e) => {
        e.preventDefault()
        createMessage(user, message)
            // nav to the show page
            .then(res => {
                createThread(user, res.data.message)
                    .then(res => {
                        // console.log('currentChannel: ', currentChannel)
                        // console.log('newly created thread: ', res.data.thread)
                        addThreadToChannel(user, currentChannel._id, res.data.thread._id)
                            // .then(() => triggerRefresh())
                            .then(() => {
                                // console.log(res.data)
                                socket.emit('thread', res.data.thread)
                            })
                            .catch(err => {
                                msgAlert({
                                    heading: 'Error',
                                    message: 'Could not add thread to channel',
                                    variant: 'danger'
                                })
                            })
                    })
                    .catch(err => {
                        msgAlert({
                            heading: 'Error',
                            message: 'Could not create thread',
                            variant: 'danger'
                        })
                    })
            })
            // send a success message
            .then(() => {
                msgAlert({
                    heading: 'Success',
                    message: 'Message sent successfully',
                    variant: 'success'
                })
            })
            // if there is an error tell the user about it
            .catch(() => {
                msgAlert({
                    heading: 'Error',
                    message: 'Failed to send message channel',
                    variant: 'danger'
                })
            })
    }
```
```js
io.on('connection', (socket) => {
	console.log(socket.id)
	socket.on('thread', (thread) => {
		console.log('thread', thread)
	})

	socket.on('disconnect', () => {
		console.log('user disconnected, socket.id: ', socket.id)
	})
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No errors at the moment, just want to talk through the way my data is structured and the order of operations needed to send a chat message and have it update on the page in real time.

### What is your best guess as to the source of the problem?
I have implemented a lot to make sure that data is passed to database and things are created in the right order so far, and I figured that was the right place to start, but now that I'm needing to implement socket.io I'm unsure if I took the right approach.

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/rectorjordan94/blink-api
https://github.com/rectorjordan94/blink-client

**Comment by timmshinbone** [comment]
It seems like you are doing things in the right order, but, that all depends on how that's showing up. Does your data appear to be creating/showing/refreshing properly?

**Comment by rectorjordan94** [comment]
As of now, it is working properly, I am able to automatically update the displayed threads on the page once a new thread(message) is sent via the form. I think I need to create another user and give them access to the channel to see if they are able to see the changes in real-time as well. That should give me a better idea of where to implement socket.

**Comment by timmshinbone** [comment]
Definitely, you might want to try running the app in another browser window simultaneously(possibly with a different chrome profile or incognito mode)

**Comment by rectorjordan94** [comment]
Working on that now, I'm able to send and receive messages on front & backend right now, trying to figure out how to trigger a refresh of threads on both client windows at the same time now...
