### ISSUE TITLE
Need help defining my response model to accept valid incoming texts & compare & populate Foreign Keys, etc

### ISSUE THREAD

**Issue by estebbins** [sei-ec-remote/project-4-issues#222]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
Trying to create a response model that will check itself and populate itself based on certain pieces of info.

### Post any code you think might be relevant (one fenced block per file)
```python
# Rough attempt at first model
class Response(models.Model):
    sms_sid = models.CharField(max_length=100)
    response = models.CharField(max_length=1000)
    to = models.CharField(max_length=100)
    from_num = models.CharField(max_length=100)
    msg_sid = models.CharField(max_length=100)
    question = models.ForeignKey(Question)
    player = models.ForeignKey(User, on_delete=models.SET_NULL)

    def __str__(self):
        # This must return a string
        return f"{self.player} is {self.response}"
    
    def check_answer(self):
        self.response = int(self.response)
        correct_answer = int(self.question.answer)
        if self.response > correct_answer:
            return False
        return True
    
    def check_active(self):
        if self.player.game.is_active:
            if self.player.player.phone_number == self.from_num:
                return True
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
no errors, just assistance in thinking about this

### What is your best guess as to the source of the problem?
lack of comfort with Django

### What things have you already tried to solve the problem?
Not that much...just trying to get on the right track.

**Paste a link to your repository here**
https://github.com/estebbins/FareIsFair-API

**Comment by timmshinbone** [comment]
I feel like the quiz should be the thing checking the responses. Like, your players all send their responses in, I feel like it would be easier for the parent model to check the response models associated with it. Does that seem right considering the workflow of your data?

**Comment by estebbins** [comment]
I'm not sure what it easier which is why I want to talk it through. I have to be able to validate and check the user info matches and that the game is even active to set a response. I have been struggling to access and update data in the foreign key & many to many relationships every step of the way.

**Comment by timmshinbone** [comment]
Sounds like the game would have access to all that info, so, my recommendation would be to try to check all responses from the game itself. 

Check the [DRF Docs Article on Serializers](https://www.django-rest-framework.org/api-guide/relations/#serializer-relations)  and also see if this [article](https://www.sankalpjonna.com/learn-django/the-right-way-to-use-a-manytomanyfield-in-django) is helpful

**Comment by estebbins** [comment]
Thanks - I'm trying to go into the weekend with a clearer picture of how to execute this process. Would it be possible to have a conversation?

**Comment by timmshinbone** [comment]
Sure thing!

**Comment by estebbins** [comment]
Resolved this by tracking the active question as a Foreign Key with a related name (to avoid the overlap with my many to many for questions) on the GameSession model
