### ISSUE TITLE
Using django messages. Having issue getting a message to come up when deleting an item

### ISSUE THREAD

**Issue by tthephas** [sei-ec-remote/project-4-issues#228]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

DR
### What's the problem you're trying to solve?
trying to get a message to come up when deleting an item. 

### Post any code you think might be relevant (one fenced block per file)
```
@login_required
def delete_chore(request, kid_id, chore_id):
  # Note that you can pass a toy's id instead of the whole toy object
  Kid.objects.get(id=kid_id).chores.remove(chore_id)
  messages.success(request, "SUCCESS YES")
  return redirect('kids_detail', kid_id=kid_id)
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/thomasthephasdin/.local/share/virtualenvs/django-env-2RLhBifv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_chore' with arguments '(5,)' not found. 1 pattern(s) tried: ['kids/(?P<kid_id>[0-9]+)/assoc_chore/(?P<chore_id>[0-9]+)/\\Z']

### What is your best guess as to the source of the problem?
i think i'm just missing some small detail to bring over the right kid/chore id, to have it render on screen

### What things have you already tried to solve the problem?
looked at django docs and examples, brought in necessary imports. could possibly be the "includes" method for django that might be needed to render html page but not sure

**Paste a link to your repository here**
https://github.com/tthephas/Chore-Tracker

code should be on "deletemessage" branch

**Comment by timmshinbone** [comment]
Share the code in the view template for your delete, I think there's a problem with it.

**Comment by tthephas** [comment]
from the page where its rendering?
```
            <div class="card-action">
              <form action="{% url 'delete_chore' chore.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn red">Confirm Done</button>

              </form>
            </div>
```

**Comment by tthephas** [comment]
i added "kid.id" after the delete chore function and it now renders, but clicking button doesnt do anything.

**Comment by timmshinbone** [comment]
We'll take a look after my meeting

**Comment by tthephas** [comment]
ok thanks

**Comment by tthephas** [comment]
still not sure how to get this message window to come up. pressing delete doesnt render anything

**Comment by timmshinbone** [comment]
Ok, let's jump into a breakout room about it, I'll slack ya

**Comment by tthephas** [comment]
thanks

**Comment by tthephas** [comment]
i was able to access the database, update the current balance (with a static number), then access the balance on teh chore (6 below), pass it thru the string, but i'm getting this error. seems very close to adding the number though

Reverse for 'delete_chore' with arguments '(3, 3, 6)' not found. 1 pattern(s) tried: ['kids/(?P<kid_id>[0-9]+)/unassoc_chore/(?P<chore_id>[0-9]+)/\\Z']

**Comment by tthephas** [comment]
its the right chore, the right kid, the right amount, just not rendering for some reason.

**Comment by tthephas** [comment]
got bank account to update fine. but messages still not showing.
