### ISSUE TITLE
Trying to delete a nested array in mongo/postman

### ISSUE THREAD

**Issue by Chrislee1996** [sei-ec-remote/project-4-issues#23]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I am trying to delete a nested array inside one of my routes. I am able to create/push it inside the nested array but unsure how to delete it

### Post any code you think might be relevant (one fenced block per file)
```
router.delete('/comments/:courseId/:reviewId/:commentId', requireToken,(req, res, next) => {
    const courseId = req.params.courseId
    // const review = req.body.review
    // find the product in the db
    Course.findById(courseId)
        // if product not found throw 404
        .then(handle404)
        .then(course => {
            const theComment = course.reviews[0]._id
            // console.log(course.reviews[0]._id,'here is the course')
            console.log(course.reviews[0].id,'here is the course')

            // requireOwnership(req, review)
            // call remove on the review we got on the line above requireOwnership
            theComment.remove()
            // return the saved product
            return course.save()
        })
        // send 204 no content
        .then(() => res.sendStatus(204))
        .catch(next)
})
```
Here is the delete route I have

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
TypeError: theComment.remove is not a function

### What is your best guess as to the source of the problem?
I am not writing/fetching the info correctly in my route

### What things have you already tried to solve the problem?
I'm console logging my routes but I'm just not sure how to delete the comment that is living inside the review

**Paste a link to your repository here**
https://github.com/Chrislee1996/CourseSearch-API

**Comment by timmshinbone** [comment]
What did this line: `console.log(course.reviews[0].id,'here is the course')` return?

**Comment by Chrislee1996** [comment]
That returned the reviewId 6267591e0962d60029d1c4df which is my normal array.

If I console.log (course.reviews[0].comments[0].id), this will return the commentId which is inside the nested array.

**Comment by timmshinbone** [comment]
ok, so, the second item you just sent is the one that you want removed?

**Comment by Chrislee1996** [comment]
Yes.  The issue is I'm trying to use .remove but it is saying it is not a function which is probably why I'm not getting it to work

**Comment by Chrislee1996** [comment]
Resolved! The comment was a subdocument of a subdocument (reviews) and we just had to grab the right objects. 

```
            const theReview = course.reviews.id(reviewId)
            console.log(theReview)
            // const theComment = course.reviews[0].comments.id(commentId)
            const theComment = theReview.comments.id(commentId)
```

Here is the gist of the code that made it make more sense. Of course, you have to name a variable for the reviewId and commentId with req.params.(whatever)
