### ISSUE TITLE
Trying to add a "delete" button and delete and uploaded photo from boto3/s3

### ISSUE THREAD

**Issue by tthephas** [sei-ec-remote/project-4-issues#233]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
trying to add a delete button next to our upload button, that we used to upload photos thru s3 using boto client. i updated the url, the views (below) and have the button as its own form with a post method. but its not working.

### Post any code you think might be relevant (one fenced block per file)
```
@login_required
def delete_photo(request, kid_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file: 
      s3 = boto3.client('s3', aws_access_key_id=AWS_ACCESS_KEY, aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
      key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
      try:
        s3.delete_object(photo_file, S3_BUCKET, key)
        url = f"{S3_BASE_URL}{S3_BUCKET}/{key}"
        photo = Photo(url=url, kid_id=kid_id)
        photo.delete()
      except Exception as error:
        print('Error deleting photo', error)
        return redirect('kids_detail', kid_id=kid_id)
    return redirect('kids_detail', kid_id=kid_id)
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
none

### What is your best guess as to the source of the problem?
i think its easier than i'm making it, to delete something from s3 vs adding. 

### What things have you already tried to solve the problem?
i used the adding code, changed to delete object which comes from the s3 docs. used delete instead of save. checked my views/urls to make sure routing was correct.

**Paste a link to your repository here**
https://github.com/tthephas/Chore-Tracker

deletepicture branch has the code

**Comment by tthephas** [comment]
since each kid has an id, and each photo is assigned to a kid, i'm assuming that its much easier to just access kid.id and the photo.id and delete. i can see this in the photo model thru admin (below), just not sure how to access it


Photo for kid_id: 3 @https://s3.us-east-2.amazonaws.com/sei-choretracker/89e7b7.webp

**Comment by asands94** [comment]
Make sure when you setup your AWS you add the ability to delete like we added the ability to get the objects

**Comment by tthephas** [comment]
is that in the aws portal?

**Comment by tthephas** [comment]
was that when we chose "getObjects" ? so i'd choose a delete one? would i have to create an entirely new bucket?

**Comment by tthephas** [comment]
ok i added that, generated and saved new policy. i see it added. but my button still doesnt work

            "Action": [
                "s3:DeleteObject",
                "s3:GetObject"
            ],

**Comment by tthephas** [comment]
getting the post request, with the right function, but picture not deleting
[13/Mar/2023 18:14:11] "POST /kids/1/delete_photo/ HTTP/1.1" 302 0

**Comment by tthephas** [comment]
seeing alot of posts with code like this. just not sure what my "key" is or how to write it for that kid.id and photo.id
```
def s3_delete(id):
    s3conn = boto.connect_s3(settings.AWS_ACCESS_KEY,
            settings.AWS_SECRET_ACCESS_KEY)
    bucket = s3conn.get_bucket(settings.S3_BUCKET)

    k = Key(bucket)
    k.key = str(id)
    k.delete()
```

**Comment by asands94** [comment]
Sorry for the delayed response, was in a meeting! But yes to what you did with the delete object in the AWS portal. Your key mught be refering to the key of the photo. like the one you created for the add_photo method

**Comment by tthephas** [comment]
ok but that was a variable created in the other function. does it now have an id? doesnt the photo have an id i can access?

**Comment by timmshinbone** [comment]
I think you should just delete the photo model itself and not worry about ths s3 getting deleted. All you have to do is remove the association from your database instead of having to do another s3 call to delete the photo.

**Comment by tthephas** [comment]
ok i'll try that

**Comment by tthephas** [comment]
i made the class model for photo delete. then changed the url, then tried but getting this error. then i entered <int:pk> in the url but still didnt work. what might i be missing?
Generic detail view PhotoDelete must be called with either an object pk or a slug in the URLconf.

**Comment by timmshinbone** [comment]
without seeing the code, I'm not sure, share the updated code

**Comment by tthephas** [comment]
i added taht int:pk again. got this error. i think it just is wondering what the route is. since i'm doing the model, do i need to create a form view like "cat_confirm_delete" type?
url here
```
  path('kids/<int:kid_id>/delete_photo/<int:pk>/', views.PhotoDelete.as_view(), name='delete_photo'),
```


error below

parents/<int:parent_id>/add_kid/ [name='add_kid']
kids/<int:kid_id>/assoc_chore/<int:chore_id>/ [name='assoc_chore']
kids/<int:kid_id>/add_photo/ [name='add_photo']
kids/<int:kid_id>/delete_photo/<int:pk>/ [name='delete_photo']
kids/ [name='kids_index']
kids/<int:kid_id>/ [name='kids_detail']
kids/create/ [name='kids_create']
kids/<int:pk>/update [name='kids_update']
kids/<int:pk>/delete [name='kids_delete']
chores/ [name='chores_index']
chores/create/ [name='chores_create']
chores/<int:chore_id>/ [name='chores_detail']
chores/<int:pk>/update [name='chores_update']
chores/<int:pk>/delete [name='chores_delete']
accounts/signup/ [name='signup']
accounts/
The current path, kids/1/delete_photo/, didn’t match any of these.

**Comment by tthephas** [comment]
if i go the photo model route, shoudl i have a delete screen like we did during class?

**Comment by scarletpuma** [comment]
Try that out and let us know if you have any errors or weird behavior.

**Comment by tthephas** [comment]
still not working. i created the url. i created the photo delete form. i created the button and tied it to the form and url, but getting this error. something with passing the photo id
Reverse for 'delete_photo' with arguments '('',)' not found. 1 pattern(s) tried: ['kids/(?P<kid_id>[0-9]+)/delete/(?P<photo_id>[0-9]+)\\Z']
