### ISSUE TITLE
Signup new users broke for apparently no reason (checkmate django, you defeated me gg)

### ISSUE THREAD

**Issue by mqpiffle** [sei-ec-remote/project-4-issues#236]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
hellscape errrr....django

### What's the problem you're trying to solve?
i'd like a user to do the first thing when they visit my lolsite

### Post any code you think might be relevant (one fenced block per file)
```
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('gigstr:home')
        else:
            error_message  = 'Invalid sign up - please try again.'
    form = CustomUserCreationForm()
    context = {'form': form, 'error_massage': error_message}
    return render(request, 'registration/signup.html', context)
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
no error(fu django), i'm expecting the user to be saved to the db and the page redirected somewhere(anywhere would be great)

### What is your best guess as to the source of the problem?
django

### What things have you already tried to solve the problem?
nothing i expect other people to fix my problems (/s in case you missed the salty sarcasm)

**Paste a link to your repository here**
https://github.com/mqpiffle/Project-X-Gigstr

**Comment by mqpiffle** [comment]
for context, the terminal is actually showing a 200 on POST (lololllol)
![image](https://user-images.githubusercontent.com/69863751/224994556-e0912b0d-3dad-4368-a9b8-53b483b9df6f.png)

**Comment by mqpiffle** [comment]
and yes i can add users in the admin
![image](https://user-images.githubusercontent.com/69863751/224995265-5a9e2aa8-69c1-45d0-a218-f0e12cf851fe.png)

**Comment by asands94** [comment]
Are you trying to force users to sign in when they first login?

**Comment by mqpiffle** [comment]
no, typical 'hit the signup button' functionality

**Comment by mqpiffle** [comment]
and this is for SIGN UP not SIGN IN/LOG IN

**Comment by asands94** [comment]
It looks like you're using a custom form and not the one we used in class, can you share that code?

**Comment by mqpiffle** [comment]
sorry the backtick key suddenly stopped working on my keyboard, gonna restart my computer brb

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'role']

**Comment by mqpiffle** [comment]
sorry my keyboard locked up, here ya go!
```
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'role']
```

**Comment by mqpiffle** [comment]
```
class CustomUser(AbstractUser):
    # define a set of choices for the role field
    # describing the types of user for the app
    # this will lead to the user types having permissions
    # to access certain parts of the app
    class Roles(models.IntegerChoices):
        ADMIN = 0, _('Admin')
        FAN = 1, _('Fan')
        BAND = 2, _('Band')
        VENUE = 3, _('Venue')

    # add the role field
    role = models.IntegerField(choices=Roles.choices, default=Roles.FAN, verbose_name=_('Role'))
    # def save(self, *args, **kwargs):
    #     if not self.pk:
    #         self.role = self.base_role
    #         return super().save(*args, **kwargs)
    
        
GROUPS = ['Admin', 'Fan', 'Band', 'Venue']
@receiver(post_save, sender=CustomUser)
def user(sender: CustomUser, instance: CustomUser, ** kwargs) -> None:
        group = Group.objects.get(name=GROUPS[instance.role])
        transaction.on_commit(lambda: instance.groups.set([group], clear=True))
```

**Comment by mqpiffle** [comment]
figured out by my sr dev buddy by using debug tools
