### ISSUE TITLE
Django Deployment Issue

### ISSUE THREAD

**Issue by brianaleew** [sei-ec-remote/project-4-issues#239]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
Django

### What's the problem you're trying to solve?
I am getting an error when trying to deploy on bit.io

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![Screen Shot 2023-03-14 at 9 11 36 AM](https://user-images.githubusercontent.com/119267904/225011953-a118e4fd-672e-45bb-b528-c7a7b529e54f.png)

### What is your best guess as to the source of the problem?
Something with my file structure maybe? 

### What things have you already tried to solve the problem?
I got the same error when trying to deploy last night, but thought maybe it was a commit issue so i did a new push to no avail. Some clarification on maybe build.sh's proper location might solve the issue. Also let me know what code i should add in 

**Paste a link to your repository here**
https://github.com/brianaleew/GA-Final-Project

**Comment by asands94** [comment]
Have you created the `build.sh` file at the top level of your app (which is where manage.py is)

**Comment by brianaleew** [comment]
It should look like this right?
![Screen Shot 2023-03-14 at 9 20 08 AM](https://user-images.githubusercontent.com/119267904/225013677-b432c6e4-135f-46b1-b689-75b58fd3a6c8.png)

**Comment by asands94** [comment]
Yup! have you pushed up your code since adding in this file?

**Comment by asands94** [comment]
I also notice that you have your code inside of an extra folder, which may be why render is not finding your build.sh file. So here is what my folder setup looks like on gitthub vs yours
![Screenshot 2023-03-14 at 9 27 33 AM](https://user-images.githubusercontent.com/84302689/225015575-6d234294-38a3-4ba6-bbf3-74f049dd0ee9.png)

![Screenshot 2023-03-14 at 9 27 55 AM](https://user-images.githubusercontent.com/84302689/225015769-d90b4ae9-2209-4a5c-b32a-c8a6adee9c7b.png)

**Comment by brianaleew** [comment]
Yes! the problem was my file structure. Things were nested one layer too deep! Deploy working now. Thanks for the help Ashley!
