### ISSUE TITLE
Deployment not rendering items

### ISSUE THREAD

**Issue by jawknee59** [sei-ec-remote/project-4-issues#242]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
django and python

### What's the problem you're trying to solve?
deployed app not rendering items

### Post any code you think might be relevant (one fenced block per file)
(https://jawcommerce.onrender.com/)
### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![Screenshot 2023-03-14 at 10 09 09 AM](https://user-images.githubusercontent.com/26725511/225045745-4ca595d7-7f83-4da6-a6f0-79d81e407877.png)

### What is your best guess as to the source of the problem?
bit.io database?

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://jawcommerce.onrender.com/

**Comment by asands94** [comment]
Did you do a seed file?

**Comment by jawknee59** [comment]
I created the items on localhost:8000/admin portal

**Comment by asands94** [comment]
Your localhost admin portal will only show up on your development environment, it won't show up once you're deployed

**Comment by jawknee59** [comment]
I would need to make a seed file for it to render?

**Comment by asands94** [comment]
Actually in your .env file, you can change your DATABASE_URL to your bit.io connection string and that should work

**Comment by jawknee59** [comment]
Tried that and still not rendering, do I need to do anything in the settings.py?

**Comment by asands94** [comment]
You'll just have to create the superuser again now that you added the DATABASE_URL to your env and make some stuff there again and then you should see it on your website

**Comment by jawknee59** [comment]
I should be able to see items in the bit.io database?

**Comment by asands94** [comment]
Yes. After you recreate your superuser and go to the admin portal, you'll need to add things to your database again that will then showup in your bit.io database
