### ISSUE TITLE
Sign Up Form displaying in base.html and signup.html

### ISSUE THREAD

**Issue by tayanaHL** [sei-ec-remote/project-4-issues#245]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
Django

### What's the problem you're trying to solve?
Trying to figure out why my sign up sheet is displaying in base.html

### Post any code you think might be relevant (one fenced block per file)
```
<!DOCTYPE html>
<html>
  <head>
    <title>ijwiwis</title>
    <!-- Import Materialize CSS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <!-- Navigation Bar -->
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Virtual ATM</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'signup' %}">Sign up</a></li>
          <li><a href="{% url 'signin' %}">Sign in</a></li>
        </ul>
      </div>
    </nav>
    
    <!-- Content -->
    {% block signin_form %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    {% endblock %}

    <!-- Sign-up and Sign-in Buttons -->
    <div class="container">
      <div class="row">
        <div class="col s6">
          <a href="{% url 'signup' %}" class="waves-effect waves-light btn-large">Sign up</a>
        </div>
        <div class="col s6">
          <a href="{% url 'signin' %}" class="waves-effect waves-light btn-large">Sign in</a>
        </div>
      </div>
    </div>
    
  </body>
</html>

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I'm seeing the sign up form in both base.html and signup.html when I only want to see it in the signup.html

### What is your best guess as to the source of the problem?
The way my base.html is probably set up wrong

### What things have you already tried to solve the problem?
I tried commenting out the form, but it causes more problems

**Paste a link to your repository here**
https://github.com/tayanaHL/Capstone-Project

**Comment by scarletpuma** [comment]
Is your sign up form working?

**Comment by tayanaHL** [comment]
Yes, it works.  The only problem is that when I try to comment out particular code from my base.html to remove it, it removes it from my signup.HTML as well.
<img width="1430" alt="Screenshot 2023-03-14 at 12 39 54 PM" src="https://user-images.githubusercontent.com/98771444/225105415-5e4b5ebd-7ee0-4f7e-bdc0-a922b22d6712.png">

**Comment by asands94** [comment]
Everything in your base.html file will be in all your files that's why it gets removed from everywhere. Since you have the signup actually working, I would move on to other functionality and then come back to styling
