### ISSUE TITLE
Mongoose Error when starting server for first time after setting up boilerplates

### ISSUE THREAD

**Issue by DaceyForward** [sei-ec-remote/project-4-issues#248]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN-Stack, 2-project Architecture

### What's the problem you're trying to solve?
Starting the server

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![Screen Shot 2023-10-09 at 3 51 10 PM](https://github.com/sei-ec-remote/project-4-issues/assets/139731478/9d00dc60-b2ad-42f8-8e92-b0f6985c9286)

### What is your best guess as to the source of the problem?
An issue with my db connection

### What things have you already tried to solve the problem?
Looking back through notes, videos, and google..

**Paste a link to your repository here**
[Xylo-Backend](https://github.com/DaceyForward/Project-4-XYLO-BACKEND.git)

**Comment by asands94** [comment]
It looks like you need to add your `MONGODB_URI` to your `.env file`

**Comment by DaceyForward** [comment]
I do have it there already. OMG, nevermind, I put "MONGOBD" 🤦‍♀️ working now! Thank you!

**Comment by asands94** [comment]
Yay!
