### ISSUE TITLE
Throw err on boilerplate

### ISSUE THREAD

**Issue by noahD0zer** [sei-ec-remote/project-4-issues#249]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
throw err on boilerplate

### Post any code you think might be relevant (one fenced block per file)
```

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Starting the development server...

/Users/noahmendoza/sei/projects/BG3-Creator-Frontend/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/noahmendoza/sei/projects/BG3-Creator-Frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/noahmendoza/sei/projects/BG3-Creator-Frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/noahmendoza/sei/projects/BG3-Creator-Frontend/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/noahmendoza/sei/projects/BG3-Creator-Frontend/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/noahmendoza/sei/projects/BG3-Creator-Frontend/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/noahmendoza/sei/projects/BG3-Creator-Frontend/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/noahmendoza/sei/projects/BG3-Creator-Frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/noahmendoza/sei/projects/BG3-Creator-Frontend/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.5.0

### What is your best guess as to the source of the problem?
node version? Or i forgot to do something we were supposed to do to the boilerplate that was taught during instruction.

### What things have you already tried to solve the problem?
npm cache clean -f
npm install -g n

**Paste a link to your repository here**
https://github.com/noahD0zer/BG3-Creator-Frontend

**Comment by asands94** [comment]
You may need to update your version of react

```
npm i -g npm-check-updates
ncu -u
npm install
```

**Comment by asands94** [comment]
If you go to your package.json and see your react is at 17 then it needs to be upgraded

**Comment by noahD0zer** [comment]
ncu -u says command not found, also my react is at 17.0.2, is this how i upgrade it?

**Comment by asands94** [comment]
did you run `npm i -g npm-check-updates` first? the previous message is the full way to update

**Comment by noahD0zer** [comment]
just copy pasted the full command you sent and am still receiving this error

**Comment by asands94** [comment]
Send a screenshot of your terminal after doing all the commands so I can see the error, thanks!

**Comment by noahD0zer** [comment]
<img width="1470" alt="Screenshot 2023-10-09 at 5 02 10 PM" src="https://github.com/sei-ec-remote/project-4-issues/assets/22017473/2177a787-7219-41ad-aa2e-f3cef13943cb">

**Comment by asands94** [comment]
Oh just run each one at a time, and wait for each one to finish running before doing the next one. then I think you should be ok

**Comment by noahD0zer** [comment]
<img width="1470" alt="Screenshot 2023-10-09 at 5 07 02 PM" src="https://github.com/sei-ec-remote/project-4-issues/assets/22017473/29e156cc-ff89-4e93-a82d-429a6e266f43">
still having the issue at the ncu command

**Comment by noahD0zer** [comment]
Also I know we're past EOD, I can find something else to do till tomorrow if you need to go!

**Comment by asands94** [comment]
Try this full command and if not we can troubleshoot first thing in the morning!

`npx npm-check-updates -u`

**Comment by noahD0zer** [comment]
That did it! Thank you so much and have a great evening...or day!

**Comment by asands94** [comment]
Awesome, you too!
