### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CameronASC20** [sei-ec-remote/project-4-issues#25]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Getting my index page to show

### Post any code you think might be relevant (one fenced block per file)
```
router.get('/', (req, res) => {
	const { username, userId, loggedIn } = req.session
	fetch('https://www.balldontlie.io/api/v1/players')
		.then((responseData) => {
			console.log(responseData)
			// return responseData
			return responseData.json()
			// res.send(responseData)
		})
		.then((jsonData) => {
			console.log(jsonData)
			// res.send(jsonData)
			res.render('basketball/index', { players: jsonData, username, loggedIn })
		})
		.catch(error => {
			res.redirect(`/error?error=${error}`)
		})
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![Screenshot from 2022-04-26 09-34-22](https://user-images.githubusercontent.com/68292255/165311948-bc8f48cd-5172-45a9-afa2-7e91318524ee.png)

### What is your best guess as to the source of the problem?
I can't connect to mongo because I don't have a mongourl

### What things have you already tried to solve the problem?
Nothing

**Paste a link to your repository here**
https://github.com/CameronASC20/capstone-project

**Comment by timmshinbone** [comment]
share your `models/connection.js` file here

**Comment by CameronASC20** [comment]
// make our .env variables available via process.env
require('dotenv').config()
// import mongoose
const mongoose = require('mongoose')

// connect to the database
// local database connection -> process.env.DATABASE_URL
// remote database connection -> process.env.MONGODB_URI
mongoose.connect(process.env.MONGODB_URI, {
	useUnifiedTopology: true,
	useNewUrlParser: true,
})

// save the connection in a variable
const db = mongoose.connection

// create some notification
db.on('open', () => console.log(`Mongoose connected to ${mongoose.connection.host}:${mongoose.connection.port}`))
db.on('close', () => console.log(`You are disconnected from ${mongoose.connection.host}:${mongoose.connection.port}`))
db.on('error', (error) => console.log(error))

// export the connection
module.exports = mongoose

**Comment by timmshinbone** [comment]
ok, great, now what does your `.env` file say? share that here as well

**Comment by CameronASC20** [comment]
I added my MONGO_URI  to the .env file
