### ISSUE TITLE
Error when using Update route

### ISSUE THREAD

**Issue by cooperwhitley** [sei-ec-remote/project-4-issues#253]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN 2 project architecture

### What's the problem you're trying to solve?

Having trouble getting my update route to work for a subdoc, seems like the function set is not configured. Not sure what dependency I'm missing, as it worked with almost exactly the same configuration when doing the code-along.

### Post any code you think might be relevant (one fenced block per file)
Patch route for the subdocument:
```js
router.patch('/sections/:articleId/:sectionId', requireToken, removeBlanks, (req, res, next) => {
	const articleId = req.params.articleId
	const sectionId = req.params.sectionId

	Article.findById(articleId)
		.then(handle404)
		.then(article => {
			const theSection = article.sections.id(sectionId)
                        // check for edit authorization on the article, if private only allow article owner to edit
			if (!article.publicallyEditable) {
				requireOwnership(req, article)
			}
                        // add req.user to article editor list, if they are not already on it
			if (!article.editors.includes(req.user.id)) {
				article.editors.push(req.user.id)
			}
                        // I know the previous lines function as they are copy-pasted from other routes that are working fine
                        // this seems to be the problem line, see error
			theSection.set(req.body.articleSection)
			return article.save()
		})
		.then(() => res.sendStatus(204))
		.catch(next)
})
```

dependencies/imports for this route file:
```
const express = require('express')
const passport = require('passport')
const Article = require('../models/article')
const ArticleSection = require('../models/articleSection')

const mongoose = require('mongoose')
const customErrors = require('../../lib/custom_errors')
const handle404 = customErrors.handle404
const requireOwnership = customErrors.requireOwnership
const removeBlanks = require('../../lib/remove_blank_fields')
const requireToken = passport.authenticate('bearer', { session: false })
const router = express.Router()
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

```
TypeError: Cannot read properties of null (reading 'set')
    at /home/uncleburger/sei/projects/openwiki/wikiAPI/app/routes/articleSection_routes.js:53:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### What is your best guess as to the source of the problem?

I think it is a missing dependency, either that or I haven't established set in some other way.

### What things have you already tried to solve the problem?

Kind of stumped as to where to address this, I cross referenced other routes, specifically the similar ones from the code-along, and they're formatted just the same.

**Paste a link to your repository here**

https://github.com/cooperwhitley/OpenWikiAPI

**Comment by asands94** [comment]
It looks like a scoping issue. You define `theSection` in one area, then try to use it another

**Comment by asands94** [comment]
Nevermind, I changed the colors and now I see it's fine!

**Comment by asands94** [comment]
I would do a console.log or `theSection` and see what it is. I would also do a console log for `article.sections` to make sure you're getting what you expect since you're assigning it to `theSection`

**Comment by cooperwhitley** [comment]
gotcha, will check that out, thanks!

**Comment by cooperwhitley** [comment]
I just put my id params in the API call in the wrong order......... 😓
