### ISSUE TITLE
3rd party API not pulling by ID

### ISSUE THREAD

**Issue by Kateattardo** [sei-ec-remote/project-4-issues#254]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN(mongoose + react)

### What's the problem you're trying to solve?
I'm using spoonacular for my 3rd party API.  I'm able to get recipes options to display but then when my onClick does not get the choice recipe.  In terminal the get request is going through but not showing in the browser

### Post any code you think might be relevant (one fenced block per file)
```
router.get('/recipes', async (req, res) => {
    const recipeId = req.query.recipeId;
    const url = `https://api.spoonacular.com/recipes/${recipeId}/information`
    try {
        const response = await axios.get(
            url,
            {
                params: {
                    apiKey: process.env.SPOONACULAR_API_KEY,
                }
            }
        );

```
const recipeViews = recipes.map(recipe => {
    const handleOnClick = async () => {
      try {
        const response = await axios.get(
          'http://localhost:8000/spoonacular/recipes',
          {
            params: {
              recipeId: recipe.id
            }
          }
        );
        setInstructions(response.data);

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I'm seeing an empty body{} in terminal but the recipe ID is also showing in termianl

### What is your best guess as to the source of the problem?
My backend code is missing 1 param maybe?

### What things have you already tried to solve the problem?
added params: ingredientInstructions

**Paste a link to your repository here**
https://github.com/Kateattardo/kitchwitchAPI.git

https://github.com/Kateattardo/kitchwitchClient.git

**Comment by asands94** [comment]
Can you share your frontend code that relates to this `onClick` that you're using? If the backend is showing the results as expected then there could be a wrong with a function you wrote on the frontend.

**Comment by Kateattardo** [comment]
const recipeViews = recipes.map(recipe => {
    const handleOnClick = async () => {
      try {
        const response = await axios.get(
          'http://localhost:8000/spoonacular/recipes',
          {
            params: {
              recipeId: recipe.id
            }
          }
        );
        setInstructions(response.data);
      } catch (error) {
        console.error("Error fetching recipes:", error);
      }
    };
