### ISSUE TITLE
Development server error

### ISSUE THREAD

**Issue by JordonM** [sei-ec-remote/project-4-issues#257]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Development server error in front end client when running npm start

### Post any code you think might be relevant (one fenced block per file)
```

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
/EmployeeExpAPP/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

### What is your best guess as to the source of the problem?
an error in npm install

### What things have you already tried to solve the problem?
tried adding and committing and running npm start again
**Paste a link to your repository here**
https://github.com/JordonM/EmployeeAPP/tree/main

**Comment by asands94** [comment]
Hey Jordon, it looks like you need to update your Package.json file. Here are the commands to run in terminal after you cd into your React app. Just make sure when you do an `ls` in your terminal you can see your package.json before running these commands.

Run one at a time.

`npm i -g npm-check-updates`
`ncu -u`
`npm install`

**Comment by JordonM** [comment]
`  EmployeeExpAPP git:(main) npm i -g npm-check-updates
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/npm-check-updates
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/npm-check-updates'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/npm-check-updates'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/npm-check-updates' `

![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/684c2375-5ff3-4088-a3f9-56f3151bad14)

**Comment by asands94** [comment]
You may need to do `sudo npm i -g npm-check-updates`

**Comment by JordonM** [comment]
Thank you
