### ISSUE TITLE
Show route not working

### ISSUE THREAD

**Issue by rsm-dnierman** [sei-ec-remote/project-4-issues#26]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

DR

### What's the problem you're trying to solve?

Show route not working

### Post any code you think might be relevant (one fenced block per file)
```python
class BinDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes=(IsAuthenticated,)
    def get(self, request, pk):
        """Show request"""
        # Locate the bin to show
        bin = get_object_or_404(Bin, pk=pk)
        # Only want to show owned bins?
        if request.user != bin.user:
            raise PermissionDenied('Unauthorized, you do not own this mango')

        # Run the data through the serializer so it's formatted
        data = BinSerializer(bin).data
        return Response({ 'bin': data })
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: as_view() takes 1 positional argument but 2 were given
[26/Apr/2022 13:50:04] "GET /bins/1/ HTTP/1.1" 500 63288

P.S. I have seen this type error before and I think someone accidentally swapped the takes and positional argument
numbers, because I would mess with it and I think it should read takes 2 positional arguments but 1 was given....

### What is your best guess as to the source of the problem?

django is expecting an argument in my show route even though I provided it it is not accepting it for some reason OR
nothing to actually do with the arguments and this error message is a red herring

### What things have you already tried to solve the problem?
copying and pasting the mango code and comparing the two and double checking my postman request

**Paste a link to your repository here**

HERE

**Comment by timmshinbone** [comment]
ok try changing this line:
```py
if request.user != bin.user:
            raise PermissionDenied('Unauthorized, you do not own this mango')
```
To this:
```py
if not request.user.id == mango.owner.id:
            raise PermissionDenied('Unauthorized, you do not own this mango')
```

and let me know if the behavior changes

**Comment by timmshinbone** [comment]
ignore the horrible indentation, that's markdown's fault lol

**Comment by rsm-dnierman** [comment]
my bins don't have users. I can get rid of the line completely

bin.py
```python
from django.db import models

class Bin(models.Model):
    barcode = models.IntegerField()
    active = models.BooleanField()
    bin_model_id = models.ForeignKey(
        'bin_model',
        on_delete=models.CASCADE
    )
    location_id = models.ForeignKey(
        'location',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"bin: {self.barcode} is located at {self.location_id} and Active Status = {self.active}"
    
    def as_dict(self):
        return {
            'id': self.id,
            'active': self.active,
            'bin_model_id': self.bin_model_id,
            'location_id': self.location_id
        }

```

**Comment by timmshinbone** [comment]
ok, in that case, do you need to protect that route with Auth?

**Comment by rsm-dnierman** [comment]
Yeah maybe I should get rid of auth all together for this model/ model's view?

**Comment by timmshinbone** [comment]
Yeah as long as you don't need to protect that resource you don't need the auth stuff

**Comment by rsm-dnierman** [comment]
I removed the ` permission_classes=(IsAuthenticated,)`

and added a conditional, so only a super user can use the delete route:

```python
    def delete(self, request, pk):
        """Delete request"""
        # Locate bin to delete
        print('DELETE REQUEST RUNNNING')
        bin = get_object_or_404(Bin, pk=pk)
        # Only delete if the user making the request is a superuser
        if(request.user.is_superuser):
            bin.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        else:
            raise PermissionDenied("Unauthorized, you do not have permission to delete this bin")
```
