### ISSUE TITLE
http://localhost:3000/products/6524639cd5d7bc6706a6ab2f (not displaying product)

### ISSUE THREAD

**Issue by kxiside** [sei-ec-remote/project-4-issues#261]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
cant create show pets page it just shows loading

### Post any code you think might be relevant (one fenced block per file)
```
<Link to={`/products/${product._id}`} className='btn btn-info'>
                    { product.name }
                </Link>
```

### What is your best guess as to the source of the problem?
maybe i have an outdated version because i followed the pets app for show and i still cant get it to work

### What things have you already tried to solve the problem?
changing id to _id

**Paste a link to your repository here**
https://github.com/kxiside/jackiemoon-client

**Comment by asands94** [comment]
In your App.jsx try adding a `/` to your route for ProductShow so `path='/products/:id'`

**Comment by kxiside** [comment]
i tried this earlier! 
still says loading.. also i got the babel plugin warning.
