### ISSUE TITLE
how to use timestamps in rendering. 

### ISSUE THREAD

**Issue by jpineda48** [sei-ec-remote/project-4-issues#262]
### What's the problem you're trying to solve?
I would like to add a Date to each entry I make. How do I use timestamps for that? I know it is straightforward but i feel so brain fried today. 

### Post any code you think might be relevant (one fenced block per file)
Entry Model
```
const journalEntrySchema = new mongoose.Schema({
    title: {
        type: String,
    },
    body:{
        type:String,
    },
    owner: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
        
    },

    }, {timestamps:true})



```
Entry Show
```
  <Container className='m-2'>
        <Card>
            <Card.Header>{entry.title}</Card.Header>
            <Card.Body>
                <Card.Text>
                    {entry.body}
                    {entry.timestamps}
                   
                    
                </Card.Text>
            </Card.Body>
            <Card.Footer>

```

### What things have you already tried to solve the problem?

**Paste a link to your repository here**

**Comment by asands94** [comment]
If you do a console.log for the entries you can take a look at all the data you get back and you should see the name of the property you want to use for the date
