### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by JordonM** [sei-ec-remote/project-4-issues#263]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Having an error getting to the API

### Post any code you think might be relevant (one fenced block per file)
```
import apiUrl from '../apiConfig'
import axios from 'axios'

export const getAllEmployees = () => {
    return axios(`${apiUrl}/employees`)
}

export const getOneEmployee = (id) => {
    return axios(`${apiUrl}/employees/${id}`)
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/80d54e82-c41f-4078-a764-fac3bd9d2448)
![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/d93b2233-76a4-470e-96d0-83590a2650c3)
![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/385c3c14-3dfe-4070-84b3-7bb8bd3b7a99)

### What is your best guess as to the source of the problem?
My API is being sending back the employee info back to the client.

### What things have you already tried to solve the problem?
I checked Postman and it works fine on there.

**Paste a link to your repository here**
https://github.com/JordonM/EmployeeAPP/tree/main
https://github.com/JordonM/EmployerExpAPI/tree/main

**Comment by timmshinbone** [comment]
Share a screenshot of the postman authorization section, and a screenshot of the route in the backend

**Comment by JordonM** [comment]
![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/2b30cbdb-6e15-42ca-83fe-aedd8eb49511)
![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/1de9e49c-c9ab-4470-ba7e-88820946bca3)

**Comment by timmshinbone** [comment]
So, that's a protected route, which means you need to use an authorization header, similar to how we do in createPet in the [pets app](https://github.com/timmshinbone/avocadoPetsClient/blob/main/src/api/pet.js)
