### ISSUE TITLE
NPM START ISSUE

### ISSUE THREAD

**Issue by brendinsgit** [sei-ec-remote/project-4-issues#266]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN
### What's the problem you're trying to solve?
Trying to run the react server with npm start/npm run start

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![issue_queue01](https://github.com/sei-ec-remote/project-4-issues/assets/139824521/49911246-b019-45cc-8f4d-8cfd3a191f85)

### What is your best guess as to the source of the problem?
Fixing the dependency issue

### What things have you already tried to solve the problem?
I tried following the steps in the error picture that I attached. I reinstalled the dependencies but still couldn't run the server afterwards.

**Paste a link to your repository here**
https://github.com/brendinsgit/Fish_Folio

**Comment by timmshinbone** [comment]
delete `package-lock.json` and `node_modules` from the react app, then run `npm install` and let me know if that fixes it

**Comment by asands94** [comment]
Run each of these commands separately to update your package json
```
npm i -g npm-check-updates
npx npm-check-updates -u
npm install
```

**Comment by brendinsgit** [comment]
I deleted them and reinstalled before but unfortunately it didn't work for my case. I tried the check-updates and that resolved the issue this time though. Thank you for the help!
