### ISSUE TITLE
Issues with rendering only toys that the user added

### ISSUE THREAD

**Issue by DaceyForward** [sei-ec-remote/project-4-issues#269]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN-Stack, 2-project architecture

### What's the problem you're trying to solve?
I want to see the toys added only by the logged in user on my Playroom page, which also has the rotations. I can render all the toys on this page, but when I try to add a ternary for the owner of the toys, it comes up with an error.

### Post any code you think might be relevant (one fenced block per file)
Playroom.js
```js
import RotationsIndex from "./rotations/RotationIndex"
import ToysIndex from "./toys/ToyIndex"
import { Container } from 'react-bootstrap'
import { Link } from 'react-router-dom'
import { useState } from 'react'
// import { useParams } from 'react-router-dom'
// import { indexToys } from '../../api/toy'

const Playroom = (props) => {
	const { msgAlert, user, toyCards } = props
	const [toy, setToy] = useState(null)
	// console.log('props in home', props)
	// const { id } = useParams()

	return (
		<Container className='m-2' style={{ textAlign: 'center' }}>
			<h1 className="playroomName">{user.firstName}'s Playroom</h1>
            <br/>
            <h4>My Toy Rotations</h4>
			<RotationsIndex msgAlert={msgAlert} />
			<Link to='/create-rotation' className='newToy btn btn-info'>
				Add A New Rotation
			</Link>
            <br/>
			<br />
            <h4>My Toy Box</h4>
            {/* { toys.owner ?  */}
                    {/* // <p>{ toyCards }</p>
                    // <Card.Footer >owner: {toy.owner.firstName}</Card.Footer> */}
			     {/* <ToysIndex msgAlert={msgAlert} /> */}
            {/* // : null } */}
			<div>
			{
				toy.owner && user && toy.owner._id === user._id
				?
				<>
					<ToysIndex msgAlert={msgAlert} /> 
				</>
				:
				null
			}
			</div>
		</Container>
	)
}

export default Playroom
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![Screen Shot 2023-10-12 at 10 32 01 PM](https://github.com/sei-ec-remote/project-4-issues/assets/139731478/0dd00f93-b948-4211-9483-c983e67e0237)

### What is your best guess as to the source of the problem?
I'm accessing owner wrong?

### What things have you already tried to solve the problem?
I've tried two different ternaries, and switching things around, adding imports, etc. I'm honestly so fried from looking at code, I feel like the issue is just staring me in the face and I just cannot see it!

**Paste a link to your repository here**
https://github.com/DaceyForward/Project-4-XYLO-FRONTEND.git (main branch)

**Comment by asands94** [comment]
If you're still having an issue with this, you could go into your backend routes and create a route that only shows logged in users toys, but adding that owner object inside of your `Find`. Here's an example from Timms code:. Look at his `/mine` route https://github.com/timmshinbone/avocadoPetsAPI/blob/main/app/routes/pet_routes.js
