### ISSUE TITLE
Post route issue

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/project-4-issues#27]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN(mongoose + react)

### What's the problem you're trying to solve?

POST route for tags runs into an error on postman.
The terminal doesn't give me an error at all and it looks like the post goes through but it actually doesn't.

### Post any code you think might be relevant (one fenced block per file)
the route:
```
// CREATE
// POST /tags
router.post('/tags/:setupId', requireToken, (req, res, next) => {
	// set owner of new example to be current user
	req.body.example.owner = req.user.id
    const setupId = req.params.setupId
    const tag = req.body.tag

	Setup.findById(setupId)
        .then((setup => {
            console.log("This is the setup\n", setup)
            Tag.create(tag)
                .then(tag => {
                    console.log("this is the new tag\n", tag)
                    setup.tags.push(tag)
                    setup.save()
                    res.status(201).json({ tag:tag.toObject()})
                })
        }))
		// if an error occurs, pass it off to our error handler
		// the error handler needs the error message and the `res` object so that it
		// can send an error message back to the client
		.catch(next)
})
```
Postman env:

![Screen Shot 2022-04-26 at 8 54 07 AM](https://user-images.githubusercontent.com/20195643/165315818-82a5843d-c0f5-4897-b254-3beb8db6cbdf.png)

Terminal:

<img width="1070" alt="Screen Shot 2022-04-26 at 8 54 46 AM" src="https://user-images.githubusercontent.com/20195643/165315939-96b39512-3b31-4224-901a-ef3d923b17fb.png">

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
error in postman:
```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>Cannot POST /tags/6266ef9a7b8889de65e0fae4</pre>
</body>

</html>
```

### What is your best guess as to the source of the problem?

syntax or my postman setup

### What things have you already tried to solve the problem?

- double checking postman env
- double checking route in vs code
- messing around with promise chain

**Paste a link to your repository here**
https://github.com/ivycle94/Project-4-api

**Comment by ivycle94** [comment]
I just realized I forgot to add the route to my `server.js` but now I get a different error:

Terminal:
```
 09:01:38 GMT-0500 (Central Daylight Time):
TypeError: Cannot set properties of undefined (setting 'owner')
    at /Users/ivyle/sei/projects/project4/app/routes/tag_routes.js:37:25
    at Layer.handle [as handle_request] (/Users/ivyle/sei/projects/project4/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ivyle/sei/projects/project4/node_modules/express/lib/router/route.js:137:13)
    at complete (/Users/ivyle/sei/projects/project4/node_modules/passport/lib/middleware/authenticate.js:262:13)
    at /Users/ivyle/sei/projects/project4/node_modules/passport/lib/middleware/authenticate.js:269:15
    at pass (/Users/ivyle/sei/projects/project4/node_modules/passport/lib/authenticator.js:428:14)
    at Authenticator.transformAuthInfo (/Users/ivyle/sei/projects/project4/node_modules/passport/lib/authenticator.js:450:5)
    at /Users/ivyle/sei/projects/project4/node_modules/passport/lib/middleware/authenticate.js:266:22
    at IncomingMessage.req.login.req.logIn (/Users/ivyle/sei/projects/project4/node_modules/passport/lib/http/request.js:45:13)
    at Strategy.strategy.success (/Users/ivyle/sei/projects/project4/node_modules/passport/lib/middleware/authenticate.js:247:13)

```
the error is telling me it's an owner issue, so I tried creating a new setup to see if the user creating the tag had to be the creator, but I am still getting the same error.

Postman:
![Screen Shot 2022-04-26 at 9 03 57 AM](https://user-images.githubusercontent.com/20195643/165317796-22109dbb-0e00-4b47-8e6e-e6ced23187fd.png)

**Comment by timmshinbone** [comment]
You forgot to remove this line:
```js
req.body.example.owner = req.user.id
```

**Comment by timmshinbone** [comment]
Also if this is updating a specific setup, then it should be a PATCH route, that's not enough to specifically fix the problem, but it's going to fall within the conventions we've laid out in the template for which routes do specific actions

**Comment by ivycle94** [comment]
Thank you!!! 

so even if this is a `create/post` route for a tag wouldn't it be a post? or is it because the tag will end up changing the setup model so I have to make it a patch instead?

**Comment by timmshinbone** [comment]
if the `tag` is its own model, it should have its own POST route for creating the tag, that's not associated with any other models. Then, tags should be associated with `setup`s via a PATCH route.

**Comment by ivycle94** [comment]
My post route for tags is now working just fine, thank you for the help and clearing my confusion Timm! I really appreciate it :D!
