### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by JordonM** [sei-ec-remote/project-4-issues#271]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
2nd flyctl deploy is getting an error

### Post any code you think might be relevant (one fenced block per file)
```

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/3b8e0f5a-16cc-4393-96a0-0da99ba72a56)

### What is your best guess as to the source of the problem?
After the flyctl launch my fly.toml doesnt look like it normally should
![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/3194c013-ae14-49ea-9962-34d935436066)
![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/d37be56e-b81c-459f-af33-7f035c7722b3)

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/JordonM/EmployerExpAPI/tree/main
https://github.com/JordonM/EmployeeAPP/tree/main

**Comment by asands94** [comment]
Did you add all your [env] information to your fly.toml?

**Comment by JordonM** [comment]
![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/a21abfbc-f367-42a0-b421-af42a83dbc1f)
yes

**Comment by timmshinbone** [comment]
Did you change _anything_ outside of the `[env]` section of the fly.toml file? Also, share a screenshot of your files section of vsCode, like this one:
![image](https://github.com/sei-ec-remote/project-4-issues/assets/55121526/5a4665f2-7ed4-4e70-b628-069332aa6416)

**Comment by JordonM** [comment]
![image](https://github.com/sei-ec-remote/project-4-issues/assets/14878928/3830b6da-0a22-4931-a25f-094d6f722016)
No I made no changes outside of env

**Comment by timmshinbone** [comment]
Ok, let's do a 1:1 soon, I'll slack ya
