### ISSUE TITLE
Setter function not working properly

### ISSUE THREAD

**Issue by cooperwhitley** [sei-ec-remote/project-4-issues#274]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN two app architecture

### What's the problem you're trying to solve?
my show react component is not properly setting a value

### Post any code you think might be relevant (one fenced block per file)
ArticleShow.jsx :
```
const [article, setArticle] = useState(null)
    
    const [updated, setUpdated] = useState(false)

    const navigate = useNavigate()

    const { id } = useParams()
    const {user, msgAlert} = props
    
    useEffect(() => {
        getOneArticle(id)
            .then(res => console.log(res.data.article))
            // the above console log is showing that the intended article has been found
            // It seems that the problem lies at the setter function call here
            .then(res => setArticle(res.data.article))
            // this console log still shows the value as null
            .then(console.log('article state: ', article))
            .catch(err => {
                msgAlert({
                    heading: 'Error',
                    message: messages.showArticleFailure,
                    variant: 'danger'
                })
            })
    }, [updated])
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

No error message, however article is still logging as null after the setter function has been invoked

### What is your best guess as to the source of the problem?

seems like the setter function is not behaving properly. useState and useEffect have been imported properly, however, so I am not sure what's happening

### What things have you already tried to solve the problem?

I have logged out a lot of stuff, in order to narrow down the problem. it seems that the setter function is the issue

**Paste a link to your repository here**

https://github.com/cooperwhitley/OpenWikiApp

**Comment by asands94** [comment]
Is it still null when you change the code on this page , save the changes, but do not refresh the browser?

**Comment by cooperwhitley** [comment]
Hm, I just tried using the setter function like this:
```
useEffect(() => {
        getOneArticle(id)
            .then(res => console.log('article: ', res.data.article))
            // .then(res => setArticle(res.data.article))
            .then(console.log('article state: ', article))
            .then(setArticle({title: 'test 2'}))
            .catch(err => {
                msgAlert({
                    heading: 'Error',
                    message: messages.showArticleFailure,
                    variant: 'danger'
                })
            })
    }, [updated])
```
and that updated state as expected, this is very strange

**Comment by cooperwhitley** [comment]
As I mentioned, res.data.article is logging the expected article object. So I'm not sure why it isn't setting properly.

**Comment by asands94** [comment]
Ohh lets jump into a room (10), I'm curious about that

**Comment by cooperwhitley** [comment]
On it
