### ISSUE TITLE
Promise is not being returned

### ISSUE THREAD

**Issue by lucas-richards** [sei-ec-remote/project-4-issues#277]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN
### What's the problem you're trying to solve?

return a value from promise
### Post any code you think might be relevant (one fenced block per file)
```
import { getAllTransactions } from "../../../api/transaction"

export const getQtyInPortfolio = (user, symbol) => {
    return new Promise((resolve, reject) => {
        getAllTransactions()
            .then(res => {
                    const transactions = res.data.transactions.filter(transaction => transaction.owner._id === user._id && transaction.symbol === symbol)
                    console.log('these are all the transactions',transactions)
                    const countStocks = transactions.reduce((count,obj)=>{
                        if (obj.buy === true) {
                            count.buy++;
                        } else {
                            count.sell++;
                        }
                        return count;
                    },{ buy: 0, sell: 0 })
                    console.log('this is countstocks',countStocks)
                    const qty = countStocks.buy - countStocks.sell
                    console.log('this is the qty',qty)
                    
                    resolve(qty); // Resolve the promise with the data
                })
                .catch((error) => {
                    reject(error); // Reject the promise if there's an error
                });
    });
};
```

### What is your best guess as to the source of the problem?

I'm not handling the return value properly

### What things have you already tried to solve the problem?

changed it to async, Promise, a function.

**Paste a link to your repository here**
https://github.com/lucas-richards/tradingPlaygroundClient

**Comment by asands94** [comment]
Do those console logs show any data?

**Comment by lucas-richards** [comment]
yes:
this is countstocks {buy: 8, sell: 9}
this is the qty -1

**Comment by asands94** [comment]
You're getting the quantity, are you not able to use it then? What are you trying to do thats not working

**Comment by lucas-richards** [comment]
I want to return the value and use it in another file

**Comment by asands94** [comment]
You could set the state and then use that state in another file. so create a useState for the qty or whatever value you want then in your function set it. then you can pass that state as props to another file

**Comment by lucas-richards** [comment]
I don't think I can use props in this case. It's not a component (I'm not returning jsx), It's just a function that return one value

**Comment by timmshinbone** [comment]
What component are you calling this function from? Can you share the code where it's being used

**Comment by lucas-richards** [comment]
```
}else if(!transaction.buy){
            const symbolTran = getQtyInPortfolio(user, transaction.symbol)
            console.log('symbolTran',symbolTran)
            console.log('transaction.quantity',transaction.quantity)
            if (symbolTran < transaction.quantity){
                return (
                    msgAlert({
                        heading: 'Oh no, you dont have enough stocks to sell!',
                        variant: 'danger'
                    })
                )
            }
                
        } 
```

**Comment by timmshinbone** [comment]
ok what's the console log say? and isn't that an async function? Also, how are you trying to use the value?

**Comment by lucas-richards** [comment]
console.log is not showing anything. Yes, it is async... I want to use it in an if statement
