### ISSUE TITLE
Postman 

### ISSUE THREAD

**Issue by spenserg92** [sei-ec-remote/project-4-issues#285]
### What's the problem you're trying to solve?
A GET request  for the platforms/mine route returns a 422 Unproccessable entity error

### Post any code you think might be relevant (one fenced block per file)
```js
router.get('/platforms/mine', requireToken, (req, res, next) => {
	Platform.find({owner: req.user.id})
		.then((platforms) => {
			return platforms.map((platform) => platform.toObject())
		})
		.then((platforms) => res.status(200).json({ platforms: platforms }))
		.catch(next)
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

{
    "stringValue": "\"mine\"",
    "valueType": "string",
    "kind": "ObjectId",
    "value": "mine",
    "path": "_id",
    "reason": {},
    "name": "CastError",
    "message": "Cast to ObjectId failed for value \"mine\" (type string) at path \"_id\" for model \"Platform\""
}
### What is your best guess as to the source of the problem?
something to do with the model?

### What things have you already tried to solve the problem?
re signing in and generating a new token and using that. tried creating a new user with a new token as well

**Paste a link to your repository here**
https://github.com/spenserg92/GameHub

**Comment by nayaba** [comment]
Can you try console.logging req.user and share the output?

**Comment by spenserg92** [comment]
It doesn't appear to be doing anything when i try to hit that route because I can't get a console.log to work. However here is the full error in the console.

![Screenshot 2024-02-09 at 3 20 03 PM](https://github.com/sei-ec-remote/project-4-issues/assets/149332042/cd912c44-fb63-4365-ba3e-cf688b0ae6f1)

**Comment by timmshinbone** [comment]
Can you share the request? Also, are you sending the token?

**Comment by spenserg92** [comment]
Yes, the token is from the most recent sign-in and was used to create a platform and that's the one I'm sending to this request. Here is the request in the console.

![Screenshot 2024-02-09 at 3 31 18 PM](https://github.com/sei-ec-remote/project-4-issues/assets/149332042/73206603-7eea-4ed0-b03b-d42fb8f84166)

**Comment by nayaba** [comment]
Can you screenshot what your request looks like in postman?  It seems like your controller doesn't think that req.user.id is real/useable... Can you show how the user is being attached to the request?

**Comment by spenserg92** [comment]
![Screenshot 2024-02-09 at 3 46 09 PM](https://github.com/sei-ec-remote/project-4-issues/assets/149332042/6a2c5ecf-9ff4-453f-a4f2-33f88055a0e7)
![Screenshot 2024-02-09 at 3 47 49 PM](https://github.com/sei-ec-remote/project-4-issues/assets/149332042/5cb6a098-c455-429a-b1ed-6cdf6d872f32)

**Comment by timmshinbone** [comment]
wait a minute, I know what the problem is. You have a route with the endpoint `'/platforms/:id'` that is listed before the route with the endpoint `'/platforms/mine'`. The word `mine` is satisfying the route parameter, and hitting the wrong route. Move the route with `'/platforms/:id'` to the bottom and this will be resolved

**Comment by spenserg92** [comment]
OMG thanks. I didn't realize the order mattered but that makes a lot of sense now. thank you!
