### ISSUE TITLE
API & Client

### ISSUE THREAD

**Issue by Jlarranaga** [sei-ec-remote/project-4-issues#286]
### What's the problem you're trying to solve?
API & Client wont connect. error when running client side

### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?

**Paste a link to your repository here**

**Comment by timmshinbone** [comment]
What does the error say?

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/f7b7eaff-51d6-4743-a46c-dbc6b624bdaa)

**Comment by timmshinbone** [comment]
look at the react boilerplate's instructions, right under that will have the code you need to run in your terminal to get the app running

**Comment by Jlarranaga** [comment]
Oh ok. I was reading the read me but somehow missed that. Thank you Timm
