### ISSUE TITLE
API Calls

### ISSUE THREAD

**Issue by Jlarranaga** [sei-ec-remote/project-4-issues#292]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN
### What's the problem you're trying to solve?
Sending search keyword to API side to make call to API

### Post any code you think might be relevant (one fenced block per file)
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/f48c55d1-aa91-4b04-b8d9-1278e82384cf)
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/c2238339-784b-4860-b271-9f63fa22dacc)
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/04fd5e12-da30-49eb-aef4-b6563689885e)

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/78a40962-1f52-4913-abce-0a5ff65a2925)

### What is your best guess as to the source of the problem?
Not making the right call to the API server side 

### What things have you already tried to solve the problem?
Google

**Paste a link to your repository here**

**Comment by timmshinbone** [comment]
Looks like you're not sending the user token. Take off `requireToken` from your index controller and the issue will be solved

**Comment by Jlarranaga** [comment]
Now this is throwing an error. I;m not sure why 
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/55d172e8-f31d-4712-8fa9-d17cbae6a07a)

**Comment by Jlarranaga** [comment]
I missed the semicolon... my bad

**Comment by Jlarranaga** [comment]
Still not working... 
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/0aa8d1f4-3682-43e5-95fa-2b9d7cc5a337)

**Comment by timmshinbone** [comment]
oh! You're not sending a post request, you're sending a GET from the front end. Check out my [client side api functions from the pets app](https://github.com/timmshinbone/applePiesPetsClient/blob/main/src/api/pet.js)

**Comment by Jlarranaga** [comment]
But im not creating anything. I am searching in the API and want the search results to come back and be displayed

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/62a7902f-f994-4b6d-82e1-3e46428f4ffd)

**Comment by timmshinbone** [comment]
POST doesn't need to be used for creating exclusively, only when you need a request body, which you have here

**Comment by Jlarranaga** [comment]
Ok, I used the POST method and its still not working. I'm at a loss

**Comment by timmshinbone** [comment]
show me the updated code

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/5bc499ee-f2a7-441e-9f5a-a851b1e1241d)

**Comment by Jlarranaga** [comment]
API
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/f7cbd6e3-afb0-4d97-8a65-4f8ead47948f)

**Comment by timmshinbone** [comment]
show me the allExercises function

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149622991/c9e791b2-7132-4d60-a99d-602b3c5a34a9)

**Comment by timmshinbone** [comment]
ok we can take a look together, check slack
