### ISSUE TITLE
Not sure where to trigger state change

### ISSUE THREAD

**Issue by BeccaK8** [sei-ec-remote/project-4-issues#294]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN

### What's the problem you're trying to solve?

I have a date navigation bar that has links to refresh the page for a different date but I'm trying to force the navigation bar to refresh too so I can change the color of the date button for what's selected 

<img width="561" alt="image" src="https://github.com/sei-ec-remote/project-4-issues/assets/150313386/afa04951-5c41-4e54-bc10-11f9847b5a45">

### Post any code you think might be relevant (one fenced block per file)
```js
const HealthDateNavigation = (props) => {

    const { handleClick, msgAlert, user } = props

    const [ showDate, setShowDate ] = useState(props.showDate)
    const [ updated, setUpdated ] = useState(false)

    const showDateObj = new Date(showDate)
    console.log('showDateObj = ', showDateObj)

    const diff = showDateObj.getDate() - showDateObj.getDay() + (showDateObj.getDay() === 0 ? 6 : 1)
    const startOfWeek = new Date(showDateObj.setDate(diff))
    let dateDivs = []

    dateDivs.push(<div key='left' className='date-nav-div'><FontAwesomeIcon icon={ faChevronLeft }/></div>)
    for (let i = 0; i < 7; i++) {
        const thisCardDate = new Date(startOfWeek)
        thisCardDate.setDate(startOfWeek.getDate() + i)
        dateDivs.push(
            <HealthDateNavButton 
                thisCardDate={thisCardDate} 
                showDate={showDate} 
                handleClick={handleClick}
            />
        )
    }
    dateDivs.push(<div key='right' className='date-nav-div'><FontAwesomeIcon icon={ faChevronRight }/></div>)

    return (
        <>
            <Container className='date-nav-section'>
                <div className='month-nav'>
                    { showDateObj.toLocaleString('default', { month: 'long'}) }
                </div>
                <div className='date-nav'>
                    { dateDivs }
                </div>
            </Container>
        </>
    )
}

export default HealthDateNavigation
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

No error message.  The "selected" date button is not changing color.

### What is your best guess as to the source of the problem?

I need a `useEffect` somewhere in the above code, I just don't know where.  I want to force `dateDivs` to refresh but how?

### What things have you already tried to solve the problem?

I tried moving the whole `for...loop` inside a useEffect but that hid my navigation altogether.

**Paste a link to your repository here**

https://github.com/BeccaK8/health-hub

**Comment by timmshinbone** [comment]
Is this the component code that is responsible for rendering the one you want to update the color of? or is that info in another component?

**Comment by rohit0796** [comment]
@BeccaK8  can i work on this?

**Comment by BeccaK8** [comment]
Yes, this is the component that renders the one I want to update.  The parent of this component also is notified because that parent will change the bottom half of the box to show the new date and it's health stuff.  (That parent part is working - I'm geting the state change there.  It's just the navigation component that's not refreshing

**Comment by timmshinbone** [comment]
Ok, then I'd say add a useEffect and another piece of state, similar to the `updated` boolean  I showed in the codealong. That should refresh this component

**Comment by timmshinbone** [comment]
oh, I see you've already got the updated piece of state, so add a useEffect that will re-render this component when things change, and plug that updated value into the dependency array

**Comment by BeccaK8** [comment]
I changed that to have a state for the `dateDivs`:
```js
 const [ dateDivs, setDateDivs ] = useState([])
```

with an `useEffect` that updates `dateDivs`:
```js
    useEffect(() => {
        console.log('in healthdatenav useeffect')
        console.log('old date divs = ', dateDivs)
        const newDateDivs = []

        /* handle prev week button */
        const prevWeekDate = new Date(startOfWeek)
        prevWeekDate.setDate(startOfWeek.getDate() - 7)
        newDateDivs.push(
            <HealthDateNavButton
                thisCardDate={prevWeekDate}
                showDate={showDate}
                displayValue='left'
                handleClick={onClick}
            />
        )

        /* show daily buttons for this week */
        // newDateDivs.push(<div key='left' className='date-nav-div'><FontAwesomeIcon icon={ faChevronLeft }/></div>)
        for (let i = 0; i < 7; i++) {
            const thisCardDate = new Date(startOfWeek)
            thisCardDate.setDate(startOfWeek.getDate() + i)
            newDateDivs.push(
                <HealthDateNavButton 
                    thisCardDate={thisCardDate} 
                    showDate={showDate} 
                    handleClick={onClick}
                />
            )
        }

        /* handle next week button */
        const nextWeekDate = new Date(startOfWeek)
        nextWeekDate.setDate(startOfWeek.getDate() + 7)
        newDateDivs.push(
            <HealthDateNavButton
                thisCardDate={nextWeekDate}
                showDate={showDate}
                displayValue='right'
                handleClick={onClick}
            />
        )

        // newDateDivs.push(<div key='right' className='date-nav-div'><FontAwesomeIcon icon={ faChevronRight }/></div>)
        setDateDivs(newDateDivs)
        console.log('new date divs = ', dateDivs)
    }, [updated])
```

**Comment by BeccaK8** [comment]
Now it's updating but it's a click behind.  For example:
- when first rendering, today (13) is green
- I click 15 - the bottom changes to the 15th info but the 13 stays green
- I then click 18 - the bottom changes to the 18th but now the 15 is green

so i'm a step behind...

**Comment by timmshinbone** [comment]
ok, let's resolve on zoom. Check slack

**Comment by timmshinbone** [comment]
Any updates on this?

**Comment by BeccaK8** [comment]
When I sat down and analyzed what was really required (thanks for the push there), I ended up removing all the extra garbage. By letting the parent state (HealthDateMine) drive the refreshes while the bottom-most child (HealthDateNavButton) updated that parent state, it refreshes great for most of the cases.  I have a problem now when clicking on a Sunday or Monday, so I'm tracing through  my date logic. (And time zones are confusing).  I think my original issue can be closed - so I will do that. Thanks for talking me through it yesterday!
