### ISSUE TITLE
Having an error testing my reservation rout

### ISSUE THREAD

**Issue by Tessabaxter12** [sei-ec-remote/project-4-issues#295]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I'm getting a 401 Unauthorized. Trying to have the reservation connected with the user id

### Post any code you think might be relevant (one fenced block per file)
```
const express = require('express')
const passport = require('passport')
const Reservation = require('../models/reservation')
const customErrors = require('../../lib/custom_errors')
const handle404 = customErrors.handle404
const requireOwnership = customErrors.requireOwnership
const removeBlanks = require('../../lib/remove_blank_fields')
const requireToken = passport.authenticate('bearer', { session: false })
const router = express.Router()

// CREATE
// POST / reservations
router.post('/reservations', requireToken, (req, res, next) => {
	// set owner of new reservations to be current user
	req.body.reservation.owner = req.user.id
	Reservation.create(req.body.reservation)
		// respond to succesful `create` with status 201 and JSON of new "reservation"
		.then((reservation) => {
			res.status(201).json({ reservation: reservation.toObject() })
		})
		// if an error occurs, pass it off to our error handler
		// the error handler needs the error message and the `res` object so that it
		// can send an error message back to the client
		.catch(next)
})

// UPDATE
// PATCH /reservations/5a7db6c74d55bc51bdf39793
router.patch('/reservations/:userId/:reservationId', requireToken, removeBlanks, (req, res, next) => {
	const { userId, reservationId } = req.params;
	// if the client attempts to change the `owner` property by including a new
	// owner, prevent that by deleting that key/value pair
	delete req.body.reservation.owner
	Reservaton.findById(req.params.id)
		.then(handle404)
		.then((reservation) => {
			// pass the `req` object and the Mongoose record to `requireOwnership`
			// it will throw an error if the current user isn't the owner
			requireOwnership(req, reservation)
			// pass the result of Mongoose's `.update` to the next `.then`
			return reservation.updateOne(req.body.reservation)
		})
		// if that succeeded, return 204 and no JSON
		.then(() => res.sendStatus(204))
		// if an error occurs, pass it to the handler
		.catch(next)
})
// DESTROY
// DELETE /reservations/5a7db6c74d55bc51bdf39793
router.delete('/reservations/:Id', requireToken, (req, res, next) => {
	const { userId, reservationId } = req.params;
	Reservation.findById(req.params.id)
		.then(handle404)
		.then((reservation) => {
			// throw an error if current user doesn't own `reservation`
			requireOwnership(req, reservation)
			// delete the reservation ONLY IF the above didn't throw
			reservation.deleteOne()
		})
		// send back 204 and no content if the deletion succeeded
		.then(() => res.sendStatus(204))
		// if an error occurs, pass it to the handler
		.catch(next)
})
module.exports = router
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I'm getting a 401 Unauthorized

### What is your best guess as to the source of the problem?
I'm not sure I have the user and Id set correctly

### What things have you already tried to solve the problem?
I watched the video and google searched

**Paste a link to your repository here**
https://github.com/Tessabaxter12/Bubbas-Place-API

**Comment by nayaba** [comment]
Can you elaborate on what behavior causes this 401?  Are you pressing a button your client, are you making a request in postman...?

**Comment by Tessabaxter12** [comment]
Sorry I tested it with postman.  My other model works but this model has the user information which might be incorrect?

**Comment by nayaba** [comment]
Which route are you testing?

**Comment by Tessabaxter12** [comment]
The create route is the one that is giving me a 401

**Comment by nayaba** [comment]
Can we try console.logging req.body and req.user?

**Comment by Tessabaxter12** [comment]
how would I do that and how would I test that?

**Comment by nayaba** [comment]
let's add it just before this line: `req.body.reservation.owner = req.user.id` in your post controller

**Comment by Tessabaxter12** [comment]
Okay and then should I try to send the call in postman again to test that?

**Comment by nayaba** [comment]
Yes, exactly.  Then look in your terminal for the console.log

**Comment by Tessabaxter12** [comment]
so if I get the following than I'm just doing something wrong in postman and my route is correct?

===== Incoming Request =====

Tue Feb 13 2024 13:55:39 GMT-0800 (Pacific Standard Time)
POST /reservations
body {"reservations":{"owner":"a40c71d906547782bb9371b40e0b72d8","date":"2024-02-13T12:00:00Z"}}

============================

**Comment by nayaba** [comment]
Yes, you're route is absolutely correct - my next thought is, are you adding the `token` to your postman request?

**Comment by Tessabaxter12** [comment]
Yes I added the token.  This is what the body looks like in postman ```
{
    "reservations" : {
    "owner": "a40c71d906547782bb9371b40e0b72d8",
    "date": "2024-02-13T12:00:00Z"
    }
}                                                
``` I used a owner Id for the owner. Its a post  {{url}}/reservations

**Comment by nayaba** [comment]
Can you screenshot where you're adding the token also?  And do you have more than one user?

**Comment by Tessabaxter12** [comment]
If the route is okay. Think I can tested it with the front in? I'm working on that now? I feel like its a postman thing I'm doing wrong and I'm running out of time. Would it be okay if I open this issue from the front end if needed?

**Comment by Tessabaxter12** [comment]
Thanks
