### ISSUE TITLE
event.target.id randomly doesn't return a value

### ISSUE THREAD

**Issue by BeccaK8** [sei-ec-remote/project-4-issues#297]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN

### What's the problem you're trying to solve?

On my date navigation, I have a series of 9 divs - one for every day of the current week, one for prev week, and one for next week.  I have confirmed that each of these divs has an "id" set to the date. I'm using this event.target.id in an `onclick` to change the parent state to the date.  Randomly event.target.id returns nothing, even though I'm clicking on the `div`

### Post any code you think might be relevant (one fenced block per file)
```js
    const handleDateClick = (evt) => {
        console.log('event id of clicked div is = ', evt.target.id)
        if (evt.target.id) {
            changeDate(evt.target.id)
            handleClick()
        } else {
            console.log('no div targeted so staying here')
        }
    }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

The error occurs downstream but in these logs, you can see when I `console.log()` the event.target.id that it is empty:

<img width="605" alt="image" src="https://github.com/sei-ec-remote/project-4-issues/assets/150313386/093bb33f-086f-413d-9cca-ac8e08c275b3">

### What is your best guess as to the source of the problem?

I don't know what's causing it to behave so randomly

### What things have you already tried to solve the problem?

The `handleDateClick()` shared above handles the error by not changing the state or triggering a refresh if event.target.id is empty.  I just would like to know what the root cause is so I can prevent it in the first place.

**Paste a link to your repository here**

https://github.com/BeccaK8/health-hub

**Comment by timmshinbone** [comment]
Change this line:
```js
console.log('event id of clicked div is = ', evt.target.id

**Comment by timmshinbone** [comment]
Change this line:
```js
console.log('event id of clicked div is = ', evt.target.id)
```
To this:
```js
console.log('event id of clicked div is = ', evt.target)
```

Share the results here

**Comment by BeccaK8** [comment]
I guess it's not random...if I click the free space of the div, it gets the correct target but if I click on the chevron itself, event.target returns something different:

<img width="605" alt="image" src="https://github.com/sei-ec-remote/project-4-issues/assets/150313386/94072fd7-efc4-4878-ba5c-07af3995e150">

But I can't add the same "id" to the icon, can I?

**Comment by BeccaK8** [comment]
Is there a way to get the event.target's parent element (the div) in this case?

**Comment by timmshinbone** [comment]
Is the onclick attached to the chevron or the div?

**Comment by BeccaK8** [comment]
the div

**Comment by timmshinbone** [comment]
Mind sharing the code for that?

**Comment by BeccaK8** [comment]
```js
    return (
        <div 
            key={`div_${formattedHealthDate}` } 
            className={ showing ? 'date-nav-div selected-date' : 'date-nav-div unselected-date'}
            onClick={handleDateClick}
            id={ formattedHealthDate }
        >
            {
                displayValue
                ?
                    displayValue === 'left'
                    ?
                    <FontAwesomeIcon icon={ faChevronLeft } />
                    : 
                    <FontAwesomeIcon icon={ faChevronRight } />
                :
                thisCardDate.toLocaleString('default', { day: 'numeric' })
            }
        </div>
    )
```

**Comment by BeccaK8** [comment]
As a try, I added the same "id" to the Icon and it works in some cases but now I'm occasionally getting a different target.event that I have no idea where it's coming from (maybe css) ... `<path fill=...`

<img width="605" alt="image" src="https://github.com/sei-ec-remote/project-4-issues/assets/150313386/79233f16-c941-48ca-b163-e99156fc6826">

**Comment by timmshinbone** [comment]
That `<path>` looks like it's the svg. Maybe try adding the date as a [data attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) to the `<FontAwesomeIcon />` ? Then changing your handleClick to read the target type and determine if it should use the id or the data attribute?

**Comment by BeccaK8** [comment]
Data attribute works for the svg.  But it does  not work for the `<path>`

**Comment by BeccaK8** [comment]
I found this on StackOverflow and it seems to work...thoughts?

[`evt.target.closest("DIV")`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest)

**Comment by timmshinbone** [comment]
I'd have to see it in action, how did the behavior change?

**Comment by BeccaK8** [comment]
I changed by `handleDateClick()` to what's below - to get the div first, either directly or by finding the closest div to the svg or path.  Then I can get the id off that div.  I still have a catch all in case something doesn't work, but fingers crossed, I may have finally gotten my nav 100% working.

```js
    const handleDateClick = (evt) => {
        const theDiv = (evt.target.nodeName === 'DIV') ? evt.target : evt.target.closest("DIV")
        const newDate = theDiv.id;
        if (newDate) {
            changeDate(newDate)
            handleClick()
        } else {
            console.log('no div targeted so staying here', evt.target)
        }
    }
```

**Comment by timmshinbone** [comment]
That looks pretty good to me!
