### ISSUE TITLE
Api issue 

### ISSUE THREAD

**Issue by Quantumcode9** [sei-ec-remote/project-4-issues#299]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?

GET Request 
### Post any code you think might be relevant (one fenced block per file)
```
//Backend: routes/product_routes

router.get('/search/:keyword', async (req, res) => {
    const keyword = req.params.keyword;
    const url = `https://api.bestbuy.com/v1/products((search=${keyword}))?apiKey=${process.env.BESTBUY_API_KEY}&format=json`

    try {
        const response = await axios.get(url);
        res.status(200).json(response.data.products); 
    } catch (error) {
        console.error('Search API error:', error);
        res.status(500).json({ message: 'Failed to fetch products' });
    }
});

// Frontend: api/product.js
export const searchProducts = (keyword) => {
  return axios.get(`/search/${keyword}`);
};

//Frontend: components/shared/Search 
const Search = () => {
    const [keyword, setKeyword] = useState(''); 
    const [products, setProducts] = useState([]);
  
    const handleSearch = (event) => { 
      event.preventDefault();
      searchProducts(keyword)
        .then((response) => {
          setProducts(response.data);
        })
        .catch((error) => {
          console.error('The error was:', error);
        });
    };
    return (
        <div>
            <form onSubmit={handleSearch}>
                <input
                    type="text"
                    value={keyword}
                    onChange={(e) => setKeyword(e.target.value)}
                    placeholder="Search"
                />
                <button type="submit">Search</button>
            </form>

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

Search.jsx:16 The error was: Error: Request failed with status code 404

### What is your best guess as to the source of the problem?
Me

### What things have you already tried to solve the problem?

Many things

**Paste a link to your repository here**
https://github.com/Quantumcode9/Sellout

**Comment by nayaba** [comment]
Usually when we see a 404 error the first thing we want to check is that we're navigating to the right route.  Can you share what url you're inputting into postman?

**Comment by nayaba** [comment]
Just noticed your frontend code here *facepalm

Have you successfully tested this route in postman, and can we console.log `keyword` inside of the handleSearch function?

**Comment by Quantumcode9** [comment]
I haven’t tested in Postman. I've only tested it in their query builder, I’ll try that now.
