### ISSUE TITLE
Unable to change classroom a student is in.

### ISSUE THREAD

**Issue by cloudedl** [sei-ec-remote/project-4-issues#30]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DJANGO

### What's the problem you're trying to solve?
I am trying to get a choice field to show up in my Student Update page

### Post any code you think might be relevant (one fenced block per file)
```py

class StudentUpdate(UserPassesTestMixin, UpdateView):

    model= Student
    fields = ['classroom','lessons_completed', 'results' ]
  

    def test_func(self):
        return self.request.user.is_staff

    # now we use a function to determine if our form data is valid
    def form_valid(self, form):
        # commit=False is useful when we're getting data from a form
        # but we need to populate with some non-null data
        # saving with commit=False gets us a model object, then we can add our extra data and save
        self.object = form.save(commit=False)
        self.object.save()

        classroom = str(self.object.classroom_id)
        # print('what is self.object', self.object.classroom_id)
        # pk is the primary key, aka the id of the object
        return HttpResponseRedirect('/teacher/classroom/' + classroom + '/'+ str(self.object.pk))

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
The Classroom field on my update form is unclickable

### What is your best guess as to the source of the problem?
I've researched https://docs.djangoproject.com/en/4.0/ref/forms/fields/#django.forms.ModelChoiceField.queryset
I am unable to figure out the syntax for the queryset to match a database query to my classrooms.

### What things have you already tried to solve the problem?
I have tried 

```py
field2 = forms.ModelChoiceField(queryset=Classroom.objects.all())
```

**Paste a link to your repository here**
https://github.com/johnzwiss/Capstone-Project

**Comment by cloudedl** [comment]
![Screenshot from 2022-04-26 11-51-30](https://user-images.githubusercontent.com/86618182/165341352-34f3542e-94d3-438d-b304-bbec810451d3.png)

**Comment by timmshinbone** [comment]
try querying all the classrooms and save them to a variable, something like what you have in the ModelChoiceField, like this:
```py
all_classrooms = Classroom.objects.all()
```

then, set up your field like this and see if the behavior changes:

```py
field2 = forms.IntegerField(choices=all_classrooms)
```

**Comment by tkolsrud** [comment]
Hey cloud was this resolved?

**Comment by cloudedl** [comment]
Attempting a different route to get the same effect. Thanks for the assistance. Resolved for now.
