### ISSUE TITLE
Routing Issues

### ISSUE THREAD

**Issue by F2easy** [sei-ec-remote/project-4-issues#300]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
1) I have an issue pushing stocks into my portfolio array im not sure how I would go about grabbing the stocks.

2) I want to know how I would go about navigating through show pages

### Post any code you think might be relevant (one fenced block per file)
```
## Route im trying to use to push stock info into array 
router.post('/portfolio/:portfolioId/:stockSymbol', requireToken, (req, res, next) => {
  const portfolioId = req.params.id;
  const symbol = req.body.symbol;
  console.log("portfolioId:", portfolioId);
  console.log("ticker:", ticker);

  Portfolio.findById(portfolioId)
    .then(portfolio => {
      if (!portfolio) {
        throw new Error('Portfolio not found');
      }

      portfolio.StockList.push({ ticker }); // Add the ticker as an object to the StockList array

      return portfolio.save(); // Save the updated portfolio
    })
    .then(updatedPortfolio => {
      res.status(200).json(updatedPortfolio); // Send back the updated portfolio
    })
    .catch(error => {
      // Pass the error to the error handler middleware
      next(error);
    });
});

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
the console log for both portfolioID and ticker are coming up empty

### What is your best guess as to the source of the problem?
Im not reffering to the right thing but im a little confused and don't know what to refer to at this point

### What things have you already tried to solve the problem?
I tried grabbing everything by the ticker/symbol instead of an id because I want my routes to specify each stock by the ticker/symbol since they are all unique. The symbol would be a substitute for my ID.  

**Paste a link to your repository here**
https://github.com/F2easy/WallStreetAPI

**Comment by F2easy** [comment]
Once I get this to work I just have create the delete stock functionality and all I have to do is style. I smell the finishLine

**Comment by nayaba** [comment]
I see you're setting `portfolioId` equal to `req.params.id` but I don't actually see id defined in your params.  I do, however, see `portfolioId` and `stockSymbol` defined in your params.  Along those same lines, where is `ticker` coming from, as I don't see it defined anywhere...?

**Comment by F2easy** [comment]
ticker and symbol are supposed to be the same thing

**Comment by F2easy** [comment]
I wanted to use symbol to navigate through my API since my API doesn't have stockIDs
note im pretty confused on the backend

**Comment by nayaba** [comment]
Let's try modifying these lines and see if we're able to get our console.logs to show up:

```js
  const portfolioId = req.params.portfolioId;
  const ticker = req.body.symbol;
  ```

**Comment by F2easy** [comment]
`router.patch('/portfolio/:id/symbol', requireToken, (req, res, next) => {
	const portfolioId = req.params.portfolioId;
  const ticker = req.body.symbol;
	console.log("portfolioId", portfolioId)
	console.log("ticker", ticker)`

**Comment by F2easy** [comment]
I still got undefined for both of them

**Comment by nayaba** [comment]
What is the route url you're using?

**Comment by F2easy** [comment]
/portfolio/:id/symbol

**Comment by nayaba** [comment]
So the one I'm seeing in your controller is this:
```js
/portfolio/:portfolioId/:stockSymbol
```
can we get these two urls to match up?

**Comment by F2easy** [comment]
Oh I haven't commited in a while give me a sec lol
