### ISSUE TITLE
CREATE/UPDATE Requests

### ISSUE THREAD

**Issue by Jbuckley3** [sei-ec-remote/project-4-issues#304]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
Mern

### What's the problem you're trying to solve?
my POST request for create isn't working quite right. It creates the new exercise however the owner field is not being created so then I am not able to update or delete it

### Post any code you think might be relevant (one fenced block per file)
```
```

### What is your best guess as to the source of the problem?
Possibly not setting my model up properly or not using the built in function of the template correctly

### What things have you already tried to solve the problem?
Made some changes to the model, but I still don't think i fully understand the owner aspect of it. 

**Paste a link to your repository here**
(https://github.com/Jbuckley3/MongoMusclesAPI)

**Comment by timmshinbone** [comment]
Share the post route for exercises and the model

**Comment by Jbuckley3** [comment]
`
const exerciseSchema = new mongoose.Schema(
	{
/*     owner: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User', 
        required: true,
        }, */
        name: {
			type: String,
			required: true,
		},
        description: { 
            type: String, 
            required: true 
        },
        duration: {
            type: String, 
            required: true 
            },
        date: {
            type: Date,
            required: true 
            },
	},
	{
		timestamps: true,
	}
)
`

I had owner commented out because i wasn't sure i was using it correctly. Is that what would be causing the problem?

**Comment by timmshinbone** [comment]
yeah, that's definitely the cause of it. So, uncomment it, delete all your old exercises from the database, and start adding some new ones

**Comment by Jbuckley3** [comment]
Great thanks Timm!
