### ISSUE TITLE
Deployment Bug

### ISSUE THREAD

**Issue by spenserg92** [sei-ec-remote/project-4-issues#308]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Ran into an error when trying to deploy. Saying it cant find a file.

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![Screenshot 2024-02-15 at 2 20 40 PM](https://github.com/sei-ec-remote/project-4-issues/assets/149332042/0b6304c7-7e26-43ba-acd9-c9952dec07a9)

### What is your best guess as to the source of the problem?
I renamed a folder to be lowercase but it didn't change it in GitHub. 

### What things have you already tried to solve the problem?
Is there a way to change it in GitHub or should I change it back to the original in VS Code?

**Paste a link to your repository here**
https://github.com/spenserg92/Client-GameHub

**Comment by timmshinbone** [comment]
try running this in the terminal and then attempting another push:
```
git config core.ignorecase false
```

**Comment by spenserg92** [comment]
That seems to have worked. Thanks!
