### ISSUE TITLE
Cors still blocking deployment

### ISSUE THREAD

**Issue by spenserg92** [sei-ec-remote/project-4-issues#309]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Cors still won't allow access to my netlify app

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![Screenshot 2024-02-15 at 3 00 20 PM](https://github.com/sei-ec-remote/project-4-issues/assets/149332042/8c5742fc-23e8-4406-863a-a4afd802a755)

### What is your best guess as to the source of the problem?
Not sure on this one

### What things have you already tried to solve the problem?
redoing the deployment just to make sure

**Paste a link to your repository here**
https://github.com/spenserg92/GameHub
https://github.com/spenserg92/Client-GameHub

**Comment by timmshinbone** [comment]
show me the code where you added your client origin(or the value on your fly.io dashboard)

**Comment by spenserg92** [comment]
![Screenshot 2024-02-15 at 3 57 24 PM](https://github.com/sei-ec-remote/project-4-issues/assets/149332042/7aa1def6-9e5e-427f-a455-c57e6a8e6167)
<img width="744" alt="Screenshot 2024-02-15 at 3 58 22 PM" src="https://github.com/sei-ec-remote/project-4-issues/assets/149332042/bfd62dd8-a78a-49c1-82dd-87730b5d248f">

**Comment by timmshinbone** [comment]
you need the `http://www.` at the beginning of your url

**Comment by timmshinbone** [comment]
like this:
```
https://applepiespets.netlify.app
```

**Comment by spenserg92** [comment]
Ah that makes sense. 
![image](https://github.com/sei-ec-remote/project-4-issues/assets/149332042/a7e9d1b0-f6f6-41cc-ac14-cd2dd358a04f)

**Comment by spenserg92** [comment]
Thanks!
