### ISSUE TITLE
Authentication credentials in React

### ISSUE THREAD

**Issue by katherine-kania** [sei-ec-remote/project-4-issues#31]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
When I make an axios call to my database to retrieve all the flowers, I get this error on my API side:
```
"detail": "Authentication credentials were not provided."
```
and on my client side:
```
GET http://localhost:8000/flowers/ 401 (Unauthorized)
```

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
See above.

### What is your best guess as to the source of the problem?
I know in Postman we add in a token in our headers each time we signed in. I believe its something similar to it.

### What things have you already tried to solve the problem?
Sharing the secret key with frontend didn't work. 

**Paste a link to your repository here**
https://github.com/katherine-kania/project-4-client

**Comment by katherine-kania** [comment]
Additional note.. react front end was able to access the database because I allowed me to sign-in with an existing user.

**Comment by tkolsrud** [comment]
Hmm, well first thing is it looks like your api endpoint is missing the trailing `/`, not sure if that would effect auth though...

**Comment by tkolsrud** [comment]
ah looks like the `sign up` and `sign out` are too in `auth.js` -- that's probably the issue, is that signing up isn't actually creating a user in the db

**Comment by katherine-kania** [comment]
I fixed the ```/``` but still having the Authorization error to retrieve the flowers from database. I don't have an issue with the login users. 
I just tried this in my flower index function but it couldn't recognize 'token'.
```
import apiUrl from '../apiConfig'
import axios from 'axios'


// index function
export const getAllFlowers = (user) => {
    console.log('this is the user:', user)
    return axios({
        url: `${apiUrl}/flowers/`,
        method: 'GET',
        headers: {
            Authorization: `Token token=${user.token}`
        }
    })
}
```
The user is coming out undefined in the console log. I know that the user has a token when I log in it console logs the user token.

**Comment by tkolsrud** [comment]
have you tried testing after creating a new user?

**Comment by katherine-kania** [comment]
Yes, I just tried. I was able to make a new user but for some reason during my Axios call for flowers, I can't get my user token so it's not letting me retrieve the flower data.

**Comment by tkolsrud** [comment]
I think david had a similar issue, and it was literally a missing comma, he said the solution is in here:
https://stackoverflow.com/questions/53649252/django-rest-framework-basepermissionmetaclass-object-is-not-iterable

**Comment by timmshinbone** [comment]
change this:
```js
Authorization: `Token token=${user.token}`
```
to this:
```js
Authorization: `Token ${user.token}`
```

**Comment by timmshinbone** [comment]
David's issue was back-end related, if the route is working in postman the issue is broken token syntax coming from react, in this case, one line change should fix it.

**Comment by katherine-kania** [comment]
I tried it and couple other ways and it can't recognize token. I am passing it in the routes.
![image](https://user-images.githubusercontent.com/98362705/165380511-cdd45227-2ffb-4aec-a273-a0e8b9300b90.png)

**Comment by timmshinbone** [comment]
what did the console log of the user print out?

**Comment by katherine-kania** [comment]
The user in the IndexFlowers component is printing the user w/ the token. In the flower api where I call all flowers function its printing undefined. I wonder is that because it's before the axios call? 
![image](https://user-images.githubusercontent.com/98362705/165383771-df9ae200-e92b-4b2c-a469-d01ca34a96c3.png)

**Comment by timmshinbone** [comment]
OH! You need to pass the user to the function,
```js
getAllFlowers(user)
```

**Comment by katherine-kania** [comment]
wow.. lol. It worked and this worked too:
```
Authorization: `Token ${user.token}`
```

**Comment by katherine-kania** [comment]
Thank you!!!
