### ISSUE TITLE
Adding Tags to Main Model

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/project-4-issues#32]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN(mongoose + react)

### What's the problem you're trying to solve?

I can't add tags into my my main model.

### Post any code you think might be relevant (one fenced block per file)
Patch route:
```
// UPDATE
// PATCH /examples/5a7db6c74d55bc51bdf39793
router.patch('/tags/:setupId/:tagId', requireToken, removeBlanks, (req, res, next) => {
	// if the client attempts to change the `owner` property by including a new
	// owner, prevent that by deleting that key/value pair
    const setupId = req.params.setupId

	Setup.findById(setupId)
		.then(handle404)
		.then((setup) => {
            // you have the setup now
            // have to grab the tagId
            Tag.findById(tagId)
                .then(tagId)
                    // once you found the tagId
                    // push tagId into the tags of setup
                    tags.push(tag.id)
                    // save the tagId that was pushed
                    return tags.save()
                .catch(next)
		})
		// if that succeeded, return 204 and no JSON
		.then(() => res.sendStatus(204))
		// if an error occurs, pass it to the handler
		.catch(next)
})
```
Postman: 
![Screen Shot 2022-04-26 at 11 01 57 AM](https://user-images.githubusercontent.com/20195643/165343388-9751ffbd-3694-4dcc-b483-74dcd5e211cb.png)

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
- error 404
```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>Cannot PATCH /6267fb2480f45d3df0270cfb/6268037ade0a2df4c9d2c57c</pre>
</body>

</html>
```

### What is your best guess as to the source of the problem?

I didn't set up my patch correctly. I wasn't sure how to grab the IDs of 2 different models and put it into my promise chain, so I know my route is all wrong. I want to console.log to see if I am even grabbing the IDs correctly, but I don't really know how to effectively use console logs when all I'm doing is testing on postman and can't see any of the logs.

### What things have you already tried to solve the problem?

- read doc : https://www.bezkoder.com/mongodb-many-to-many-mongoose/
- google 
- try to rewrite/mess with my patch route 

**Paste a link to your repository here**
https://github.com/ivycle94/Project-4-api

**Comment by ornery-mouse** [comment]
Can you post the route that should be handling the patch request?

**Comment by cory-yonomi** [comment]
Looks like in Postman you're missing the initial /tags/ parameter in the URL. Any console.logs you put in are going to show in your server's terminal. Right after each `.then` is a good place to log, so that you can double check what you're passing along the promise chain

**Comment by ivycle94** [comment]
Thank you! I totally missed that! 

So when I am able to see the client side i can actually see the logs, but when I'm only working with the api side it's like a 50/50 if my log shows up in the terminal. Do you have any tips to deal with that?

**Comment by ivycle94** [comment]
This is the current error I am getting after fixing the url:

![Screen Shot 2022-04-26 at 2 21 13 PM](https://user-images.githubusercontent.com/20195643/165376197-41f84f60-d867-45f4-96b8-56a804dd395f.png)


![Screen Shot 2022-04-26 at 2 23 15 PM](https://user-images.githubusercontent.com/20195643/165376531-a62bfa6b-ada5-4598-92dc-cd9bb122ec7e.png)

**Comment by timmshinbone** [comment]
Ivy you need to actually pass ids to the url so that your code can run and utilize the right data. Those `:setupId` and `:tagId` lines are placeholders. Fill them with actual ids

**Comment by ivycle94** [comment]
I've been using it as a variable by adding it to the path variables inside postman like this:
![Screen Shot 2022-04-26 at 2 28 36 PM](https://user-images.githubusercontent.com/20195643/165377347-514375dd-3ddc-4667-b3e8-9497bc724220.png)


Unless I'm using the tool totally wrong, but it worked when I worked on my other routes when I set ID to a variable.

**Comment by timmshinbone** [comment]
then in the url they need to look like this: `{{setupId}}` not the way you have them

**Comment by ivycle94** [comment]
I'm still a bit confused because how I set it up still worked normally without the curly braces. When I try to add the curly braces right now it just resets my path variable in postman.

**Comment by ivycle94** [comment]
This is what my current code is right now and I am not sure why my `push()` is coming up as `undefined`. I tried looking at the docs but no luck.

patch route:

```js
// UPDATE
// PATCH /examples/5a7db6c74d55bc51bdf39793
router.patch('/tags/:setupId/:tagId', requireToken, removeBlanks, (req, res, next) => {
	// if the client attempts to change the `owner` property by including a new
	// owner, prevent that by deleting that key/value pair
    const setupId = req.params.setupId

	Setup.findById(setupId)
		.then(handle404)
		.then((setup) => {
			console.log("this is the setup id", setupId)
			const tagId = req.params.tagId
            // you have the setup now
            // have to grab the tagId
            Tag.findById(tagId)
                .then(tagId => {
			console.log("this is the tag id", tagId)
			// once you found the tagId
			// push tagId into the tags of setup
			Setup.tags.push(tagId)
			// save the tagId that was pushed
			return Setup.tags.save()	
		})
                .catch(next)
		})
		// if that succeeded, return 204 and no JSON
		.then(() => res.sendStatus(204))
		// if an error occurs, pass it to the handler
		.catch(next)
})
```

Current Error:

![Screen Shot 2022-04-26 at 3 24 42 PM](https://user-images.githubusercontent.com/20195643/165385998-9704ce82-add2-41f9-8fa2-069c78f5f234.png)

**Comment by ivycle94** [comment]
I have no idea why my indentation is going crazy when i post a code block of my code.

**Comment by ivycle94** [comment]
Christos helped me resolve the issue! Thanks for the help everyone :)!
