### ISSUE TITLE
How to create a route to update only one field

### ISSUE THREAD

**Issue by rsm-dnierman** [sei-ec-remote/project-4-issues#36]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?

More of a best practice question, before I start building it out. If I have an object that I would only like to update ONE value for, should I create a separate route to do this or should I use the pre-existing edit route and re-pass all the values that aren't changed?

### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?

**Paste a link to your repository here**

**Comment by timmshinbone** [comment]
I like the idea of a specific route for that one specific edit if it's something you're doing all the time. Never hurts to have too many controllers, and you can get really specific with what data it's expecting and what gets sent.
