### ISSUE TITLE
Django ManyToMany Tables provide me with ids but I need the actual columns in the manytomany table.

### ISSUE THREAD

**Issue by ladomino** [sei-ec-remote/project-4-issues#37]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
Django API

### What's the problem you're trying to solve?
Trying to get the data from a ManyToMany table to return the columns from the ManyToMany table so I can return it via JSON.
It is consistent for all my manytomany tables.   So take an example - I have a college and a manytomany table I call collegetracking that stores a collegeid and userid and a status column.   When I specifically ask for the college tracked by a user - I get back all the columns in the college table and only the id in the tracking college table.

Below if you look at the code - you only get the id for track_colleges even though Track College Serializer is setup to show columns.

### Post any code you think might be relevant (one fenced block per file)
```
class TrackCollegeSerializer(serializers.ModelSerializer):
    class Meta:
        model = TrackCollege
        fields = ('id', 'status')

class CollegeSerializer(serializers.ModelSerializer):
    track_colleges = TrackCollegeSerializer(many=True)
    class Meta:
        model = College
        fields = ('id', 'name', 'city', 'state', 'image', 'early_decision', 'early_action', 'regular_decision', 
        'app_home_link', 'track_colleges')```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?


### What is your best guess as to the source of the problem?
Probably something I don't know and how perhaps TrackCollegeSerializer needs to be passed something so it can return the
actual columns and not just an id.

### What things have you already tried to solve the problem?
Probably just about everything.

**Paste a link to your repository here**
Branch is dev
https://github.com/ladomino/college-trackr/tree/dev

**Comment by timmshinbone** [comment]
Hey Laurie, so, the `TrackCollegeSerializer` and the `CollegeSerializer` are separate entities that don't talk to each other. I'd recommend doing something similar to the cat_collector code where we got all of the toys that were not associated with the cat. See the code here:
```py
def cats_show(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    # get all of the cattoys that this cat is not associated with
    available_toys = CatToy.objects.exclude(id__in = cat.cattoys.all().values_list('id'))
```

that `.exclude` can be replaced with something like a `get` or `all` for your purposes, but the `id__in = ...` and the `values_list('id')` pieces are going to help you in your search to build the correct technique for getting the right data.

I'd recommend setting up a new variable to get those pieces, and customizing the serializer that way. Let me know how it goes.
