### ISSUE TITLE
Trigger refresh isn't working when a user favorites a happy hour

### ISSUE THREAD

**Issue by patrickga94** [sei-ec-remote/project-4-issues#39]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Trying to trigger a refresh of the page when clicking on a button but it isn't working

### Post any code you think might be relevant (one fenced block per file)
```
    const triggerRefresh = () => {
        setUpdated(prev => !prev)
    }

    const faveHappyHour = () => {
        addFavorite(user, happyHour._id)
            .then(()=>{
                triggerRefresh()
                console.log('updated', updated)
            })
            .catch(console.error)
    }

    const unFave = () => {
        removeFavorite(user, happyHour._id)
            .then(()=>{
                navigate('/')
            })
            .catch(console.error)
    }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
The button is clicked and the function runs, setting the 'updated' piece of state to false or true but the page won't reload

### What is your best guess as to the source of the problem?
Not really sure

### What things have you already tried to solve the problem?
Tried changing how I call the trigger refresh function

**Paste a link to your repository here**
https://github.com/patrickga94/Happy-houR-client

**Comment by timmshinbone** [comment]
Try adding an effect hook and put the updated value inside the effect hook's dependency array. Let me know how it goes.

**Comment by patrickga94** [comment]
Like this? This isn't working

```
    useEffect(()=>{
        console.log('updated', updated)
        getOneHappyHour(id, user)
            .then(res => {
                setHappyHour(res.data.happyHour)
            })
            .catch(console.error)
    }, [updated])
```

**Comment by patrickga94** [comment]
I think the issue is that the faveHappyHour function affects the user directly and the page doesn't register those changes until the whole site refreshes

**Comment by timmshinbone** [comment]
hmm, let's take a look in a 1:1
