### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by katherine-kania** [sei-ec-remote/project-4-issues#41]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
The show component is working but the data from api is being blocked by CORS policy.

### Post any code you think might be relevant (one fenced block per file)
```
import apiUrl from '../apiConfig'
import axios from 'axios'


// index function
export const getAllFlowers = (user) => {
    // console.log('this is the user:', user)
    return axios({
        url: apiUrl + `/flowers/`,
        method: 'GET',
        headers: {
            Authorization: `Token ${user.token}`
        }
    })
}

// show function
export const getOneFlower = (flowerId, user) => {
    return axios({
        url: apiUrl + `/flowers/${flowerId}/`,
        method: 'SHOW',
        headers: {
            Authorization: `Token ${user.token}`
        }
    })
}
```
```
import React, {useState, useEffect} from 'react'
import { getOneFlower} from '../../api/flowers'
import { useParams } from 'react-router-dom'
import { Spinner, Container, Card, Button } from 'react-bootstrap'

const cardContainerLayout = {
    display: 'flex',
    justifyContent: 'center',
    flexFlow: 'row wrap'
}

const ShowFlower = (props) => {

    const [flower, setFlower] = useState(null)
    const {user, msgAlert} = props
    const { id } = useParams()
    console.log('id in showFlower', id)
    console.log('user in showFlower', user)
    
    useEffect(() => {
        getOneFlower(id, user)
            .then(res => {
                console.log('flower in showFlower', res.data.flower)
                setFlower(res.data.flower)
            })
        
            .catch(() => {
                msgAlert({
                    heading: 'No flower found',
                    message: 'flower missing',
                    variant: 'danger',
                })
            })
    }, [])

    if (!flower) {
        return (
            <Container fluid className="justify-content-center">
                <Spinner animation="border" role="status" variant="warning" >
                    <span className="visually-hidden">Loading....</span>
                </Spinner>
            </Container>
        )
    }

    return (
        <>
            <Container className="fluid">
                <Card>
                    <Card.Header>{flower.name}</Card.Header>
                    <Card.Body>
                        <Card.Text>
                            <small>Color: {flower.color}</small><br/>
                            <small>Estimated price per stem: ${flower.price_stem}</small><br/>
                            <Card.Img variant="top" src={`${flower.img}`} />
                        </Card.Text>
                    </Card.Body>
                    <Card.Footer>
                    </Card.Footer>
                </Card>
            </Container>
        </>
    )
}

export default ShowFlower
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

![image](https://user-images.githubusercontent.com/98362705/165530740-75593caa-b751-4126-a2cd-2dadac01b227.png)

### What is your best guess as to the source of the problem?
Based on some reading:
Once the browser receives this header information back, it compares the frontend domain with the Access-Control-Allow-Origin value from the server. If the frontend domain does not match the value, the browser raises the red flag and blocks the API request with the CORS policy error.

But I am not sure where the values are not matching up? 
I see a lot of different solutions on google but wanted to get an opinion so that I don't break something for later on deployment, etc.

### What things have you already tried to solve the problem?
I tried passing only user and then only Id through the getOneFlower() but it then was missing a token in both situations. 

**Paste a link to your repository here**
https://github.com/katherine-kania/project-4-client
https://github.com/katherine-kania/project-4-api

**Comment by DoireannJane** [comment]
You might need to follow these steps: https://forhjy.medium.com/django-react-has-been-blocked-by-cors-policy-net-err-failed-725723b019d4

**Comment by katherine-kania** [comment]
Ok, thank you! I will try this out now.

**Comment by DoireannJane** [comment]
It looks like coors-headers is pretty much set up in your boilerplate but just make sure everything lines up and if you're still having the issue we can do some more digging!

**Comment by katherine-kania** [comment]
CORS headers was installed already and I ran the install again just in case. I  tried adding in the following to just make sure and it's still giving me the same error.
```
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
```

I also made sure I have all the ```/``` on my front end.

**Comment by tkolsrud** [comment]
Darn, no success setting `CORS_ORIGIN_ALLOW_ALL` to True huh?

**Comment by katherine-kania** [comment]
No success. I placed it local and production the way it showed in the document Doire shared and tried other areas in my api settings.py. 

I am working on the other components and routes for now. We will see if the issue comes up again within those as well.

**Comment by katherine-kania** [comment]
Timm helped out a lot before lunch and we still couldn't get it to work. 
UPDATE:
I just created my SHOW order component and I am getting the same error. It has something to do with the SHOW method.
![image](https://user-images.githubusercontent.com/98362705/165583423-bf323833-ebfa-47ee-a9fd-41d78aeafc9b.png)

**Comment by katherine-kania** [comment]
I just got it working! 
I commented out / got rid of : 
```
// method: 'SHOW',
```
![image](https://user-images.githubusercontent.com/98362705/165584682-183c798e-aa07-4ef1-a077-b6a45ea97400.png)
