### ISSUE TITLE
cant update the date feild in my edit page 

### ISSUE THREAD

**Issue by stephanieonyekaba** [sei-ec-remote/project-4-issues#42]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN 
### What's the problem you're trying to solve?
updating two feilds in my edit page 

### Post any code you think might be relevant (one fenced block per file)
``` const handleChange = (e) => {
        // e === event
        // e.persist()

        setJournal(prevJournal => {
            const entry = e.target.entry
            const date = e.target.date
            let value = e.target.value

            const updatedValue = { entry: value }
            const updatedValuee = { date: value }
            console.log('etarget type', e.target.type)
            console.log('prevJournal', prevJournal)
            console.log('updatedValue', updatedValue)
            // if (e.target.entry === 'string') {
            //     value = parseInt(e.target.value)
            // }
            return {...prevJournal, ...updatedValue}
            return {...prevJournal, ...updatedValuee}
        })
    }

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

no error message but it wont allow me to type in the date section 
### What things have you already tried to solve the problem?

**Paste a link to your repository here**
*the issue is in my client code, but I have both repos posted just in case you want to see my backend 

https://github.com/stephanieonyekaba/Mindful_Api
https://github.com/stephanieonyekaba/Mindful_Client

**Comment by tkolsrud** [comment]
It looks like you're still in the repo for your group project, you'll probably want to create a new repository and set the remote to that one. In the meantime, which file is that code coming from? just so we can get a little more context

**Comment by timmshinbone** [comment]
Hey Stephanie, are you still working on this bug?

**Comment by tkolsrud** [comment]
Hey timm we are working on it right now. Reading the mongoose docs about using dates

**Comment by tkolsrud** [comment]
Hey stephanie, drop that whole handleClick/hook code block in here

**Comment by stephanieonyekaba** [comment]
`const EditJournalModal = (props) => {
    const { user, show, handleClose, updateJournal, msgAlert, triggerRefresh } = props
    const [journal, setJournal] = useState(props.journal)

    const handleChange = (e) => {
        // e === event
        // e.persist()

        setJournal( () => {
            // const entry = e.target.entry
            const date = e.target.date
            let value = e.target.value

            const updatedValue = { entry: value }
            console.log('etarget type', e.target.type)
            // console.log('prevJournal', prevJournal)
            console.log('updatedValue', updatedValue)
            // if (e.target.entry === 'string') {
            //     value = parseInt(e.target.value)
            // }
            return { updatedValue}

        })
    }

    const handleSubmit = (e) => {
        // e === event
        e.preventDefault()

        console.log('the journal to submit', journal)
        updateJournal( journal)
            // if create is successful, we should navigate to the show page
            .then(() => handleClose())
            // then we send a success message
            .then(() =>
                msgAlert({
                    heading: 'Journal Updated! Success!',
                    message: 'u did it',
                    variant: 'success',
                }))
            .then(() => triggerRefresh())
            // if there is an error, we'll send an error message
            .catch(() =>
                msgAlert({
                    heading: 'Oh No!',
                    message: 'that aint it',
                    variant: 'danger',
                }))
        console.log('this is the journal', journal)
    }

    return (
        <Modal show={show} onHide={handleClose}>
            <Modal.Header closeButton></Modal.Header>
            <Modal.Body>
                <JournalForm 
                    journal={journal}
                    handleChange={handleChange}
                    handleSubmit={handleSubmit}
                    heading="Edit journal!"
                />
            </Modal.Body>
        </Modal>
    )
}`

**Comment by timmshinbone** [comment]
Hey Stephanie, are you still working on this issue?
