### ISSUE TITLE
Error 401 Unauthorized

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/project-4-issues#43]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN(mongoose + react)

### What's the problem you're trying to solve?

I am trying to access the index page for my main model but I keep running into a 401 error even when I am signed in.
The route works when I tested it on postman, but it's the client side that I am having issues with.

### Post any code you think might be relevant (one fenced block per file)
api axios route:
```js
export const getAllSetups = () => {
    return axios(`${apiUrl}/setups`)
}
```
index component:
```js
import React, { useState, useEffect } from 'react'
import { getAllSetups } from '../../api/setup'
import { Card, Button } from 'react-bootstrap'
import { Link } from 'react-router-dom'
// add message handling

const cardContainerLayout = {
    display: 'flex',
    justifyContent: 'center',
    flexFlow: 'row wrap'
}

const IndexSetups = (props) => {

    const [setups, setSetups] = useState(null)
    const { msgAlert } = props

    useEffect(() => {
        getAllSetups()
            .then(res => {
                setSetups(res.data.setups)
                // console.log("res.data", res.data);
                // console.log("IndexSetup: setups: ", setups)
            })
            .then(() => {
                // msgAlert({
                //     heading: 'Spooky Setups have been retrieved!',
                //     message: indexSetupsSuccess,
                //     variant: 'success',
                // })
            })
            .catch(() => {
                // msgAlert({
                //     heading: 'Failed to retrieve Spooky Setups!',
                //     message: indexSetupsFailure,
                //     variant: 'danger',
                // })
            })
    }, [])

    if (!setups) {
        return <p>Loading ...</p>
    } else if (setups.length === 0) {
        return <p>No Setups yet, go add some</p>
    }

    let setupCards

    if (setups.length > 0) {
        setupCards = setups.map(setup => (
            <Card key={setup._id} style={{ width: '30%' }} className="m-2">
                {/* <Card.Header className='header-name'>{setup.name}</Card.Header> */}
                <Card.Body className="card-body d-flex flex-column justify-content-end">

                    <p><img src={setup.img}></img></p>

                    <Card.Text className="card-text">
                        <p className="header-name">{setup.title}</p>
                        <Link to={`/setups/${setup.id}`}>
  
                        </Link>
                    </Card.Text>
                </Card.Body>
            </Card>
        ))
    }

    return (
        <>
            <h3>All the Setups</h3>
            <div style={cardContainerLayout}>
                {setupCards}
            <a href="#top"><Button variant='dark'>Back to Top of Page</Button></a>
            </div>
        </>
    )
}


export default IndexSetups
```
app.js route fragments:
```js
<Fragment>
				<Header user={user} />
				<Routes>
					<Route path='/' element={<Home msgAlert={msgAlert} user={user} />} />
					<Route path='/setups' element={<IndexSetups msgAlert={msgAlert} />} />
					<Route
						path='/sign-up'
						element={<SignUp msgAlert={msgAlert} setUser={setUser} />}
					/>
					<Route
						path='/sign-in'
						element={<SignIn msgAlert={msgAlert} setUser={setUser} />}
					/>
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

<img width="790" alt="Screen Shot 2022-04-27 at 9 20 07 AM" src="https://user-images.githubusercontent.com/20195643/165540164-c6c967fe-6e2d-4f50-b655-73929f3573b0.png">

### What is your best guess as to the source of the problem?

I think when I try to hit my index route it's logging out my user before I can get to the actual route.

### What things have you already tried to solve the problem?

-referred to old project
-looked through code to see if I was missing any Auth
- restarted app

**Paste a link to your repository here**
https://github.com/ivycle94/Project4-client

**Comment by DoireannJane** [comment]
Trying to figure out what your issue is, did you make any headway since you posted this?

**Comment by ivycle94** [comment]
unfortunately no :(, I'm referring back to my project 3 but nowhere in the files do i see any mention of adding an auth.

**Comment by ivycle94** [comment]
I couldn't figure out how to fix it so I just took off my auth token within my routes from the backend, because this path should be accessible for public users. This won't really solve why I'm having issues with my Auth but should I just open the issues ticket again when I encounter the problem again? I sorta wanna get as much done as possible so I will continue to work on this route with public access.

**Comment by DoireannJane** [comment]
Feel free to pop in the main room a little later so we can get some eyes on it!
