### ISSUE TITLE
Unable to delete a comment that is left under a review

### ISSUE THREAD

**Issue by Chrislee1996** [sei-ec-remote/project-4-issues#44]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Right now, I am able to render a comment under a review however, I cannot delete the comment on my client. 

### Post any code you think might be relevant (one fenced block per file)
```
export const removeComment = (user, courseId, reviewId, commentId) => {
    console.log('our user in comments', user)
    console.log('our courseId in delete', courseId)
    console.log('our review Id in delete', reviewId)
    console.log('our comment Id in delete', commentId)
    return axios({
        url: `${apiUrl}/comments/${courseId}/${reviewId}/${commentId}`,
        method: 'DELETE',
        headers: {
            Authorization: `Token token=${user.token}`
        }
    })
}
```

```
const ShowComment = (props) => {
    // most of these are simply to pass to edit modal
    const {comment, user, triggerRefresh, course, review} = props
    
    const destroyComment = () => {
        removeComment(user,course._id, review._id, comment._id )
            .then(() => triggerRefresh())
            // if there is an error, we'll send an error message
            .catch(console.error)
    }

```
Above is how I am calling it. 

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
Cannot read properties of undefined (reading '_id')
```
It doesn't like course._id because it is undefined but if I take it out, it does nothing. One thing I noticed is that when I do take out course._id, the console log for courseId is logging the reviewId and the reviewId is logging the comment Id. 

### What is your best guess as to the source of the problem?
Not quite sure honestly. It works perfectly on my API side but I feel like it's not getting courseId properly.  Just in case, here is my delete route.

```
router.delete('/comments/:courseId/:reviewId/:commentId', requireToken,(req, res, next) => {
    const courseId = req.params.courseId
    const reviewId = req.params.reviewId
    const commentId = req.params.commentId
    Course.findById(courseId)
        // if product not found throw 404
        .then(handle404)
        .then(course => {
            const theReview = course.reviews.id(reviewId)
            console.log(theReview)
            const theComment = theReview.comments.id(commentId)
            console.log(theComment,'here is theComment on line 42')
            // requireOwnership(req, review)
            theComment.remove()
            // return the saved product
            return course.save()
        })
        // send 204 no content
        .then(() => res.sendStatus(204))    
        .catch(next)
})
```

### What things have you already tried to solve the problem?
I tried changing/swapping out the Id's but that just crashes my server.  I tried playing around with the React Components and I think course is not passing correctly. 

**Paste a link to your repository here**
https://github.com/Chrislee1996/CourseSearch-Client
https://github.com/Chrislee1996/CourseSearch-API

**Comment by timmshinbone** [comment]
When you console log the course in the show comment component, what does it say?

**Comment by Chrislee1996** [comment]
It logs undefined.

**Comment by Chrislee1996** [comment]
Okay it was a stupid error that Cory helped me with! Turns out I wasn't passing course whats so ever.
