### ISSUE TITLE
Not an issue, just a question on feasibility and implementation

### ISSUE THREAD

**Issue by NikPurvis** [sei-ec-remote/project-4-issues#48]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
How to present the user with the option to modify their bookshelf (add or delete) based on whether or not the book is already on the shelf.

### Post any code you think might be relevant (one fenced block per file)
n/a

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
n/a

### What is your best guess as to the source of the problem?
n/a

### What things have you already tried to solve the problem?

No problem to solve, but what's leading me to ask: I've written the queries and have the conditional add/delete working great. If the book's on the shelf, the button click will remove it, and if it's not on the shelf, we add it. Very cool, very full of myself right now, feeling awesome. 

As I'm getting ready to plop it into the render though, I realize that as currently written, the code to check all this won't run until the user clicks a button that hasn't been decided yet. So I'm wondering the best way to go about implementing this. Before I choose a rabbit hole to go down though and lose potentially fruitless hours, I thought I'd get opinions on which way to go (or if I'm way out of line). Ideas I've had:

1. Put this code into the book details view so it'll always run when the user goes there, and then pass a flag or a variable or something, based on the current code conditional, to another conditional on the template that will determine the button to render and corresponding code to run. User clicks, the action happens, we party.

2. Change directions a little and instead, on the details view, have a bookshelf button that when clicked, runs the code and delivers a pop-up that asks the user if they want to [add/delete].

3. Basically leave that for now and come back to it when I start prettying it all up in React.

I think # 2 will be easiest (though I haven't done a popup in what feels like forever, so what do I know), but it also feels way clunkier and adding unnecessary stuff to the user experience. I'm leaning toward # 1, but wondering if this is against best practices, or just a really terrible idea, because of the database hits. Then there's # 3, but I confess I feel shakiest when it comes to React, so would going this route actually negate my concerns about # 1, or is it functionally the same exact thing just with a different wrapper?

All comments and wisdom accepted and appreciated!

**Paste a link to your repository here**
https://github.com/NikPurvis/capstone-project

**Comment by cory-yonomi** [comment]
To me, that seems like a great opportunity for using React's state. Letting the front end look at what is where and render accordingly. Ideally with a full stack app like this you want to get to where the separation of concerns is apparent, i.e the backend is just giving information to the front end, for the frontend to decide how to display it.

**Comment by NikPurvis** [comment]
Fantastic, that's what I'll do then. Thank you so much!
