### ISSUE TITLE
Repo is unable to read current directory 

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/project-4-issues#5]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN(mongoose + react)

### What's the problem you're trying to solve?

When I try to type git commands I keep running into the same error.

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
This is the original error:
```
fatal: Unable to read current working directory: Operation not permitted
```

This is the error I'm getting trying to exit my Terminal:
```
maximum nested function level reached; increase FUNCNEST?
```
fatal: Unable to read current working directory: Operation not permitted

### What is your best guess as to the source of the problem?

I think it's because I messed with my folder structure earlier.

### What things have you already tried to solve the problem?

-revert the folders back
-go to system preferences and adjusting disk access settings
-exiting terminal

**Paste a link to your repository here**[
](https://github.com/ivycle94/Project-4)

**Comment by DoireannJane** [comment]
Weird. Are you in zsh?

**Comment by ivycle94** [comment]
I didn't realize I was still in the `pipenv shell`! Thanks Doire! It's weird because I wasn't having issues for my previous git commands until now and I was in the `pipenv shell` the whole time. Should I be worried I set up the repo in my `pipenv shell `
