### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CameronASC20** [sei-ec-remote/project-4-issues#51]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
My show route does not work

### Post any code you think might be relevant (one fenced block per file)
```
router.get('/:id', (req, res) => {
	console.log('PARAMS', req.params.id)
	fetch(`https://www.balldontlie.io/api/v1/players/${req.params.id}`)
		.then(jsonData => {
			const basketball = jsonData.data.json()
			console.log('DATA', basketball)
		.then(basketball => {
				console.log('LOOK AT THIS', basketball)
				res.render('superhero/show', { basketball: basketball })
			})
		})
		.catch(error => {
			res.redirect(`/error?error=${error}`)
		})
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Cannot GET /basketball/14

### What is your best guess as to the source of the problem?
I am not going far enough into the JSON data

### What things have you already tried to solve the problem?
I added .data after jsonData

**Paste a link to your repository here**
https://github.com/CameronASC20/capstone-project

**Comment by cory-yonomi** [comment]
Usually a "Cannot GET x" error means you're not hitting a route correctly, it shouldn't be a problem with data. Double check your urls/how they're getting called

**Comment by CameronASC20** [comment]
The page shows up, but I got new error. TypeError: Cannot read properties of undefined (reading 'json')

**Comment by cory-yonomi** [comment]
Add the code block that's causing that

**Comment by CameronASC20** [comment]
```
router.get('/:id', (req, res) => {
	console.log('PARAMS', req.params.id)
	fetch(`https://www.balldontlie.io/api/v1/players/${req.params.id}`)
		.then(jsonData => {
			const basketball = jsonData.json()
			console.log('DATA', basketball)
		.then(basketball => {
				console.log('LOOK AT THIS', basketball)
				res.render('basketball/show', { basketball: basketball })
			})
		})
		.catch(error => {
			res.redirect(`/error?error=${error}`)
		})
})
```

**Comment by cory-yonomi** [comment]
Console.log the `jsonData` that you're getting before you do anything else to it and add add the reponse here. You'll also need to make sure the `.then()` that changes jsonData `return`s whatever the result of those changes so that it's passed to the next `.then`

**Comment by CameronASC20** [comment]
```
DATA Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://www.balldontlie.io/api/v1/players/14',
    status: 200,
    statusText: 'OK',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
```

**Comment by CameronASC20** [comment]
When I add .json() to jsonData this pops up.
```
DATA Promise { <pending> }
```
