### ISSUE TITLE
Render check marks on edit form 

### ISSUE THREAD

**Issue by kaiguy920** [sei-ec-remote/project-4-issues#54]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Edit form is taking in prevOutfit data & recognizing tags as "checked", but cannot get the edit form to render the actual check mark

### Post any code you think might be relevant (one fenced block per file)
```js
 const handleTagSelect = (e) => {
        const outfitTags = outfit.tags

        let updatedTarget
        const checked = e.target.checked
        if (checked) {
            updatedTarget = outfitTags.push(e.target.value)
        } else {
            let index = outfitTags.indexOf(e.target.value)
            outfitTags.splice(index, 1)
            updatedTarget = outfitTags
        }
        return { ...updatedTarget }
    }
```

Example of outfit form check
```js
  <Form.Check
                    inline
                    label="evening"
                    name="tags"
                    value="626844a16c8d870164be1820"
                    onChange={handleTagSelect}
                // checked={''}
                />
                <br />
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error

### What is your best guess as to the source of the problem?
syntax to get check to physically pre-fill

### What things have you already tried to solve the problem?
console logging & comparing to pet example

**Paste a link to your repository here**
https://github.com/steviemilitello/check-my-fit-client

**Comment by timmshinbone** [comment]
Check out this example from the pet-client code:
```js
<Form.Check 
                    label='is this pet adoptable?'
                    name='adoptable'
                    defaultChecked={pet.adoptable}
                    onChange={handleChange}
                />
```
See if you can implement something like that for yours

**Comment by timmshinbone** [comment]
damn that indentation went WILD

**Comment by kaiguy920** [comment]
Since the category is a string value & not a boolean, it's not liking anything I put in for defaultChecked value 💩

**Comment by kaiguy920** [comment]
Solution on form:

```js
  <Form.Label>Tags</Form.Label><br />
                {tags.map((tag, index) => {
                    return (
                        <Form.Check
                            key={index}
                            inline
                            label={tag.category}
                            name="tags"
                            value={tag._id}
                            onChange={(e) => handleTagSelect(e, tag)}
                            defaultChecked={selectedTags.includes(tag._id)}
                        />
                    )
                })}
```
