### ISSUE TITLE
getting a type error

### ISSUE THREAD

**Issue by jscodeguy** [sei-ec-remote/project-4-issues#56]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
mern

### What's the problem you're trying to solve?
I'm not able to get any display for my character object

### Post any code you think might be relevant (one fenced block per file)
```
const GameArea = (props) => {

    const [character, setChar] = useState(null)
    const { id } = useParams()
    const [updated, setUpdated] = useState(false)
    console.log('id in gamePage', id)
    console.log('this is props in game page', props)
    console.log('this is character', character)
    useEffect(() => {
        getCharacter(id)
        .then(res => setChar(res.data.character))
            .catch((error) => {
            })
    }, [updated])
    
    return(
        <>
            <div>
                GamePage
                <p>{character.name}</p>
            </div>
            <div>
                store
            </div>
        </>
    )
}

export default GameArea
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Uncaught TypeError: Cannot read properties of null (reading 'name')

### What is your best guess as to the source of the problem?
I'm not calling it correctly in my component 

### What things have you already tried to solve the problem?
tried shuffling it around and have like 8 console logs, tried messing around with props and state and not getting any return

**Paste a link to your repository here**
https://github.com/jscodeguy/capstone-client

**Comment by timmshinbone** [comment]
Your return needs to be wrapped in some sort of if statement, because when the component renders, there's no `character` on the first render, then your effectHook runs, and after that you have a character. So you need something returning when you _don't_ have a character as that's the first condition of your component

**Comment by jscodeguy** [comment]
just threw a conditional in with the loading thing you had in pets and it's just indefinitely loading, and after trying to work on it we're now getting a 422 (Unprocessable Entity) status code

**Comment by jscodeguy** [comment]
fixed this by setting character model to unique and changing the get route
