### ISSUE TITLE
My Event Create Form stopped working???

### ISSUE THREAD

**Issue by thefrostyausty** [sei-ec-remote/project-4-issues#60]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DTP

### What's the problem you're trying to solve?
I wanted to run through my app and I attempted to create a new event and it will not submit? 

### Post any code you think might be relevant (one fenced block per file)
```py
{% extends 'base.html' %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!">
  </form>
{% endblock %}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error message, the form is stuck on the page

### What is your best guess as to the source of the problem?
I think it's because I haven't logged in as a user

### What things have you already tried to solve the problem?
Attempting to log in as a user then seeing if the problem persist(I haven't done this yet)

**Paste a link to your repository here**
https://github.com/thefrostyausty/CP-TakeItOrLeaveIt

**Comment by tkolsrud** [comment]
Was logging in successful?

**Comment by thefrostyausty** [comment]
I think I'm missing some steps so I have to add my Urls and my views

**Comment by tkolsrud** [comment]
The action attribute on your form is empty as well, which would make it difficult to hit that route

**Comment by thefrostyausty** [comment]
Thank you, I forgot all about that 😅 but now I'm having trouble with my signup coming up as a 'forbidden 403 error'
![Screen Shot 2022-04-28 at 1 32 54 PM (2)](https://user-images.githubusercontent.com/98559337/165813150-e2accd05-7877-4270-b4e8-44eb4806f70b.png)
