### ISSUE TITLE
I need some help reformatting my create route 

### ISSUE THREAD

**Issue by stephanieonyekaba** [sei-ec-remote/project-4-issues#63]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN 
### What's the problem you're trying to solve?
I am unable to submit documents in my create route form and would like some assistance in reformatting 
### Post any code you think might be relevant (one fenced block per file)
``reformat the create route so I can create a new journal `
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?


### What is your best guess as to the source of the problem?


### What things have you already tried to solve the problem?


**Paste a link to your repository here**
https://github.com/stephanieonyekaba/Mindful_Client
https://github.com/stephanieonyekaba/Mindful_Api

**Comment by timmshinbone** [comment]
Share the code for the original create form and for the api function that gets called when submitting the form
