### ISSUE TITLE
Unable to create new Event

### ISSUE THREAD

**Issue by thefrostyausty** [sei-ec-remote/project-4-issues#68]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DTP

### What's the problem you're trying to solve?
I had this issue and was then met with other issues but currently my form will not create new events entries for the user and I am uncertain as to why, when the success url is correct? and I have tried matching it in my form action and it will not go through!

### Post any code you think might be relevant (one fenced block per file)
**main_app/views.py**
```py
class EventCreate(CreateView):
    model = Event
    fields = ['image', 'title', 'description', 'takes']
    success_url = '/events'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/events/' + str(self.object.pk))

```
**event_form.html**
```html
{% extends 'base.html' %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!">
  </form>
{% endblock %}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error message and behavior I am seeing no new event being rendered when hitting the submit button

### What is your best guess as to the source of the problem?
Maybe this time something is wrong within the views or the exact route I should be rendering/redirecting to?

### What things have you already tried to solve the problem?
Changing the form action and matching it to the EventCreate

**Paste a link to your repository here**
https://github.com/thefrostyausty/CP-TakeItOrLeaveIt
<img width="1744" alt="Screen Shot 2022-04-28 at 4 19 02 PM" src="https://user-images.githubusercontent.com/98559337/165838589-8ec71256-77b7-4ebe-805b-c3df1278d6bc.png">
<img width="2240" alt="Screen Shot 2022-04-28 at 4 18 15 PM" src="https://user-images.githubusercontent.com/98559337/165838593-9193c159-f0ec-457b-b954-7034096bbcc5.png">
<img width="1547" alt="Screen Shot 2022-04-28 at 4 16 54 PM" src="https://user-images.githubusercontent.com/98559337/165838616-766b0818-63a3-471a-b974-9b81e1170784.png">
<img width="2240" alt="Screen Shot 2022-04-28 at 4 16 31 PM" src="https://user-images.githubusercontent.com/98559337/165838631-d8def04b-b82d-4114-a462-3362c45355b5.png">

**Comment by DoireannJane** [comment]
Is the event being created at all?

**Comment by thefrostyausty** [comment]
Not at all

**Comment by DoireannJane** [comment]
Could u screenshot your postman really quick? One of us will pop in shortly

**Comment by thefrostyausty** [comment]
I didn't use postman 😅 since I was seeding test data for the initial model
