### ISSUE TITLE
Cannot access /admin/

### ISSUE THREAD

**Issue by rsm-dnierman** [sei-ec-remote/project-4-issues#7]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
cannot access /admin.

### Post any code you think might be relevant (one fenced block per file)
everything I am using is directly from the template provided 
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...

### What is your best guess as to the source of the problem?

I am in a catch 22  - I need to sign in to create a session and I need a session to be able to sign in...

### What things have you already tried to solve the problem?

Googled this issue and looked at stackoverflow

**Paste a link to your repository here**
[/composting-mgmt-systems-api](https://github.com/dnierman0920/composting-mgmt-systems-api)

**Comment by timmshinbone** [comment]
The django-api-boilerplate uses token auth, so it shouldn't need sessions, see [auth lesson here](https://github.com/sei-ec-remote/django-auth-lesson)

It also utilizes `python-dotenv` package which needs to be installed with pip, as is listed in that lesson as well as the boilerplate's documentation

**Comment by rsm-dnierman** [comment]
Turns out I accidentally installed `dotenv` wihtin my `repo` and not in my `venv`.. thank you for pointing me in the right place
