### ISSUE TITLE
Setting the state of character

### ISSUE THREAD

**Issue by Nash4star** [sei-ec-remote/project-4-issues#73]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
mongoose  + react

### What's the problem you're trying to solve?
setting the state of character in app.js, then passing character along as props into our other components

### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?
everything

**Paste a link to your repository here**
https://github.com/Nash4star/capstone-client/tree/main

**Comment by tkolsrud** [comment]
Can you elaborate at all/drop a code block in here?

**Comment by cory-yonomi** [comment]
Found the character wasn't getting created on sign up, addressed that and some options for including it on the req.user
