### ISSUE TITLE
Issue with Model Validation

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/project-4-issues#75]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN

### What's the problem you're trying to solve?

I am trying to create a subdocument, but the post fails because of the main models setup validation error.

### Post any code you think might be relevant (one fenced block per file)
`models/setup.js`
```js
const mongoose = require('mongoose')
const User = require('./user')
const Tag = require('./tag')
const commentSchema = require('./comment')
const { Schema, model } = mongoose

const setupSchema = new mongoose.Schema(
    {
        title: {
            type: String,
            required: true,
        },
        img: {
            type: String,
            required: true,
        },
        description: {
            type: String,
            required: true,
        },
        tags: [{
			type: mongoose.Schema.Types.ObjectId,
			ref: 'Tag',
        }],
        // tags: {
		// 	type: [mongoose.Schema.Types.ObjectId],
		// 	ref: 'Tag'
        // },
        owner: {
            type: mongoose.Schema.Types.ObjectId,
			ref: 'User',
        },
        comments: [commentSchema]
    },
    {timestamps: true,}
)



module.exports = mongoose.model('Setup', setupSchema)
```
`models/comment.js`
```js
const mongoose = require('mongoose')

const commentSchema = new mongoose.Schema({
    note: {
        type: String,
        required: true
    },
    author: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    }
}, {
    timestamps: true
})

module.exports = commentSchema
```

`routes/comment_routes.js`
```js
// CREATE
// POST /comment
router.post('/comments/:setupId', requireToken, (req, res, next) => {
	// set owner of new comment to be current user
	req.body.comment.owner = req.user.id

	// ========== ATTEMPT #1?
	// Comment.create(req.body.comment)
	// 	// respond to succesful `create` with status 201 and JSON of new "comment"
	// 	.then((comment) => {
	// 		res.status(201).json({ comment: comment.toObject() })
	// 	})
	// 	// if an error occurs, pass it off to our error handler
	// 	// the error handler needs the error message and the `res` object so that it
	// 	// can send an error message back to the client
	// 	.catch(next)

	// ========== ATTEMPT #2?
	// Setup.findById(setupId)
	// 	.then(setup => {
	// 		setup.comments.push(req.body.comment)
	// 	})
	// 	.then(() => {
	// 		res.sendStatus(204)
	// 	})
	// 	.catch(console.error)

	// ========== SOLUTION ========
	const comment = req.body.comment
	req.body.comment.owner = req.user.id
	//get our setupId from req.params.id
	const setupId = req.params.setupId
	console.log("This is setupId\n", setupId)
	//find the setup
	Setup.findById(setupId)
		.then(handle404)
	//push the comment to the comments array
		.then(setup => {
			// requireOwnership(req, setup)
			console.log('this is the setup', setup)
			console.log('this is the comment', comment)
			setup.comments.push(comment)
			//save the setup
			return setup.save()
		})
	//then we send the setup as json
		.then(setup => res.status(201).json({setup: setup}))
	//catch errors and send to the handler
		.catch(next)

})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

<img width="970" alt="Screen Shot 2022-04-29 at 8 28 53 AM" src="https://user-images.githubusercontent.com/20195643/165953854-877c3f12-3f12-4a0b-a81c-cf60265e656f.png">

![Screen Shot 2022-04-29 at 8 33 53 AM](https://user-images.githubusercontent.com/20195643/165954694-0bc3eba7-c3b5-44c6-9258-0aa552b4e6cd.png)

### What is your best guess as to the source of the problem?

It has something to do with with my `setup` schema and `comment` schema and how I am pushing the `comment` into the `setups` . When I comment out `required: true` for the author in `models/comment.js` I am able to post a comment, so I think it's something to do with the author field.

### What things have you already tried to solve the problem?

- console.log
- commenting out code to test things
- referring back to old deliverables, projects, etc
- double checking code for any syntax errors

**Paste a link to your repository here**
https://github.com/ivycle94/Project-4-api

**Comment by DoireannJane** [comment]
The setup has an owner and your comment has an author correct?

**Comment by DoireannJane** [comment]
`req.body.comment.owner = req.user.id` <--- this should be referring to the comment author no?

**Comment by ivycle94** [comment]
Oh yeah you're right. I swapped it to `req.body.comment.author = req.user.id` but it's still giving me the same validation error! :(

**Comment by ivycle94** [comment]
Thank you Doire and Timm :D!
