### ISSUE TITLE
comment delete not working

### ISSUE THREAD

**Issue by steviemilitello** [sei-ec-remote/project-4-issues#80]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN

### What's the problem you're trying to solve?

trying to allow a user to delete a comment that they have posted

### Post any code you think might be relevant (one fenced block per file)

comment_routes.js (api)

```
// DELETE -> to delete a comment
router.delete('/comments/:outfitId/:commId', requireToken, (req, res) => {

    // first we want to parse out our ids
    const outfitId = req.params.outfitId
    const commId = req.params.commId
    // then we'll find the outfit
    Outfit.findById(outfitId)
        .then(outfit => {
            const theComment = outfit.comments.id(commId)
            // only delete the comment if the user who is logged in is the comment's author
            if (theComment.author == req.user.id) {
                // then we'll delete the comment
                theComment.remove()
                // return the saved game
                return outfit.save()
            } else {
                return
            }
        })
        .then(() => res.sendStatus(204))
        .catch(error => {
            // catch any errors
            console.log(error)
            res.send(error)
        })
})

```
comment.js (client)
```
// DELETE -> remove function
export const removeComment = (user, outfitId, commId) => {
    console.log('user', user)
    return axios({
        url: `${apiUrl}/comments/${outfitId}/${commId}`,
        method: 'DELETE',
        headers: {
            Authorization: `Token token=${user.token}`
        }
    })
}
```

ShowOutfit.js (client)

```
 const removeTheComment = () => {

        removeComment(user, outfit._id, comment._id)

            .then(() => setUpdated(true))
            .catch(() => {
                msgAlert({
                    heading: 'Comment deletion failed.',
                    message: 'failed to delete your comment',
                    variant: 'danger',
                })
            })
    }

```
```
 outfit.comments.map((comment, user) => (
                    comment.author === user.id ?
                        (<Card>
                            <Card.Title><strong>{comment.name}</strong></Card.Title>
                            <Card.Body className="show-page-card">
                                <p>{comment.note}</p>
                                <p>Date: <Moment format="MMMM DD, YYYY">{comment.date}</Moment></p>
                            </Card.Body>
                            <Card.Footer>
                               <Button onClick={() => removeTheComment()}>Delete</Button>
                            </Card.Footer>
                        </Card>)
                        :
                        (<Card>
                            <Card.Title><strong>{comment.name}</strong></Card.Title>
                            <Card.Body className="show-page-card">
                                <p>{comment.note}</p>
                                <p>Date: <Moment format="MMMM DD, YYYY">{comment.date}</Moment></p>
                            </Card.Body>
                        </Card>)
                ))}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

n/a

### What is your best guess as to the source of the problem?

not sure, since we are trying to map through the comments we aren't sure how to get the other information such as user and the delete button, to show up

### What things have you already tried to solve the problem?

we've tried attempting to access the user within the map, as well as attempting to use different syntaxes within the map to make it work

**Paste a link to your repository here**

https://github.com/steviemilitello/check-my-fit-api
https://github.com/steviemilitello/check-my-fit-client

**Comment by cory-yonomi** [comment]
Have y'all gotten a delete to work from Postman?

In the last code block, I see `user` getting passed as the second argument to the map. `.map`'s second parameter is always the current index of the array you're going through, so when you're comparing `comment.author` to `user.id` inside that function, you're actually comparing the author to index.id. I'd expect you could get your user from the `user` state set in App.js

**Comment by steviemilitello** [comment]
thank you!
yep, it works in postman! 
yeah we're not able to get user in the map! we're mapping over the comments so we're having a hard time having the delete button display relative to the user.

**Comment by steviemilitello** [comment]
All set!! Thanks so much for your help!!
