### ISSUE TITLE
'Takes' can be created for User created 'Events' but breaks for other user 'events'

### ISSUE THREAD

**Issue by thefrostyausty** [sei-ec-remote/project-4-issues#81]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DTP

### What's the problem you're trying to solve?
I managed to have the user who created their event to view and make a take on their own event. However when it comes to leaving it on another user it breaks, but the code should work for both ends??

### Post any code you think might be relevant (one fenced block per file)
**views.py**
```py
def takes_index(request, event_id):
    takes = Take.objects.all()
    event = Event.objects.get(id=event_id)
    return render(request, 'takes/index.html', { 'takes': takes, 'event': event })
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
`Not Found: /takes`

### What is your best guess as to the source of the problem?
I think it has to either do with authentication, or the user not being passed correctly? or the takes_index has to readjust to include the user?

### What things have you already tried to solve the problem?
I have tried messing with the urls and views but it still works for the original user and not for any non original user events created

**Paste a link to your repository here**
https://github.com/thefrostyausty/CP-TakeItOrLeaveIt

<img width="2240" alt="Screen Shot 2022-04-29 at 2 01 56 PM" src="https://user-images.githubusercontent.com/98559337/165998647-2fb34077-af01-4291-918a-3b4681768856.png">
<img width="2240" alt="Screen Shot 2022-04-29 at 2 01 25 PM" src="https://user-images.githubusercontent.com/98559337/165998666-a52a7ec7-8009-4b93-8625-784758544b81.png">
<img width="2240" alt="Screen Shot 2022-04-29 at 1 56 25 PM" src="https://user-images.githubusercontent.com/98559337/165998682-2088c7b2-3b44-4f26-bce8-b81245a72bae.png">
<img width="1847" alt="Screen Shot 2022-04-29 at 1 56 12 PM" src="https://user-images.githubusercontent.com/98559337/165998702-3ba65f79-eabc-43fb-ba7b-8df73289bb41.png">
<img width="1747" alt="Screen Shot 2022-04-29 at 1 56 00 PM" src="https://user-images.githubusercontent.com/98559337/165998710-490a5762-2002-4dd5-91e7-eed3f59aada7.png">

**Comment by tkolsrud** [comment]
First of all i can't believe that was 2009, it feels like that happened yesterday
