### ISSUE TITLE
Having trouble pushing my items into favorites array 

### ISSUE THREAD

**Issue by stephanieonyekaba** [sei-ec-remote/project-4-issues#87]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN 

### What's the problem you're trying to solve?

I am trying to push items from my yoga show page into favorites

### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?

**Paste a link to your repository here**

**Comment by timmshinbone** [comment]
Share the code you're trying to accomplish this with
