### ISSUE TITLE
Not able to create a virtual in my schema using an array of object references.

### ISSUE THREAD

**Issue by yazeedhani** [sei-ec-remote/project-4-issues#9]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I have an array of Expense object references in my schema. Each expense contains an amount field.
I want to create a virtual called totalExpenses that loops the expenses array to add each amount in an expense to a counter variable.
However, I am not able to populate the object references for each expense ref in the expenses array. 
I only get the IDs.

### Post any code you think might be relevant (one fenced block per file)
```
const monthTrackerSchema = new mongoose.Schema(
	{
		month: {
			type: String,
			required: true,
		},
		year: {
			type: Number,
			required: true,
		},
		annualTakeHome: {
			type: Number,
		},
		monthlyTakeHome: {
			type: Number,
		},
		budget: {
			type: Number,
		},
		monthly_savings: {
			type: Number,
			default: 0,
		},
		monthly_cashflow: {
			type: Number,
			default: 0,
		},
		expenses: 
			[
				{
					type: mongoose.Schema.Types.ObjectId,
					ref: 'Expense',
					// required: true,
				}
			]
		,
		owner: {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'User',
			required: true,
		},
	},
	{
		timestamps: true,
		toObject: {virtuals: true},
		toJSON: {virtuals: true}
	}
)

monthTrackerSchema.virtual('totalExpenses').get(function() {
	let total = 0
	for(let i = 0; i < this.expenses.length; i++)
	{
		console.log(`Expense ${i} :`, this.expenses[i])
		total += 1
	}

	return total
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Expense 0 : new ObjectId("6265fa8c8d9242bb1a6e3464")
Expense 1 : new ObjectId("6265fa918d9242bb1a6e346c")
Expense 2 : new ObjectId("6265fc428d9242bb1a6e3473")
TOtal expenses 3
Expense 0 : new ObjectId("6265fa8c8d9242bb1a6e3464")
Expense 1 : new ObjectId("6265fa918d9242bb1a6e346c")
Expense 2 : new ObjectId("6265fc428d9242bb1a6e3473")

### What is your best guess as to the source of the problem?
Not being able to populate each expense to get it's fields.

### What things have you already tried to solve the problem?
Tried using populate inside the for loop above, but that didn't work.

**Paste a link to your repository here**
https://github.com/yazeedhani/FinP-API

**Comment by tkolsrud** [comment]
Are the expenses their own models or just a schema that's referenced in the subdocument?

**Comment by yazeedhani** [comment]
No, the expenses are their own model.

```
const expenseSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true,
    },
    category: {
        type: String,
        default: 'Savings',
        required: true,
    },
    amount: {
        type: Number,
        required: true,
    },
    monthTracker: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'MonthTracker',
        required: true,
    },
    owner: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    }
})

module.exports = mongoose.model('Expense', expenseSchema)
```

**Comment by DoireannJane** [comment]
So you want to map the keys and values?

**Comment by yazeedhani** [comment]
I want to be able to accumulate the amount filed in each expense in the expenses array.

**Comment by tkolsrud** [comment]
You might not be able to do that all in one step like that. Have you tried just using that array of object refs to populate an array of the expenses?

**Comment by yazeedhani** [comment]
I guess that is what i;m trying to do. I don't know how to populate that within a virtual though.

**Comment by tkolsrud** [comment]
From looking at the docs, I think you can only do that using attributes that are stored directly in that model. So in this case, it's working the way its supposed to, but it's just grabbing the ids bc that's the only hard data stored in that model

**Comment by tkolsrud** [comment]
but this does seem like something that's kind of perfectly suited to react, ie using hooks to manipulate data that you've pulled in to the browser

**Comment by yazeedhani** [comment]
Yeah, i guess i'll try that out when i build my client.
I'll comment back here to let you know if it worked!

**Comment by tkolsrud** [comment]
Cool idea though, wish i was more familiar with virtual attributes -- but just based on the docs that seems a little ambitious... We should leave this open though in case anyone wants to continue looking into it

**Comment by timmshinbone** [comment]
Did you import the model `Expense` at the top of the `monthlyTracker` file? That might be a step toward getting the virtuals to work

**Comment by yazeedhani** [comment]
I did not. I'm able to add to the expenses array without importing `Expense` though. Is importing `Expense` only for virtuals?

**Comment by timmshinbone** [comment]
Yeah that's how you get Expense data in another model file.
