### ISSUE TITLE
small issue with merging 

### ISSUE THREAD

**Issue by nrissman** [sei-ec-remote/project-4-issues#91]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?

when i try to run git pull upstream main it says that i have merging conflicts with my node modules 
### Post any code you think might be relevant (one fenced block per file)
```
```

### What is your best guess as to the source of the problem?

my git ignore is not registering 
### What things have you already tried to solve the problem?

merging, pruning, erasing existing code
**Paste a link to your repository here**

**Comment by mattkeane-ga** [comment]
In order to work correctly, your `.gitignore` needs to be at root level of your repository (i.e. it needs to be at same level as your `.git` directory). To test this, you should be able to run `ls -a` and see both files. You may also need to remove `node_modules` from your commit history. You can do so with `git rm -r --cached node_modules`.

**Comment by nrissman** [comment]
they are at the same level, but they still sent with my last commit and i just removed them with that command

**Comment by nrissman** [comment]
![Screen Shot 2022-08-22 at 1 15 05 PM](https://user-images.githubusercontent.com/102564376/185980396-a1afc790-9cbe-44fb-b2e0-80bd22ed6578.png)

**Comment by mattkeane-ga** [comment]
Make sure that the `.gitignore` includes `node_modules`, then run `git rm -r --cached node_modules`, then do an add, and a commit.

**Comment by mattkeane-ga** [comment]
It may also be the case that that whoever made the last push may need to do this step and then push again before you can pull.

**Comment by nrissman** [comment]
hey we have something pretty weird going on with package.lock json now and we may have messed our code up
