### ISSUE TITLE
merging problem

### ISSUE THREAD

**Issue by lancenguyen100** [sei-ec-remote/project-4-issues#95]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN
### What's the problem you're trying to solve?
MERGING ISSUE

### Post any code you think might be relevant (one fenced block per file)
```
WON'T ALLOW ME TO PULL
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I CAN'T PULL FROM UPSTREAM BRANCH

### What is your best guess as to the source of the problem?
I AM NOT SURE

### What things have you already tried to solve the problem?
LOOK ONLINE

**Paste a link to your repository here**[
](https://github.com/dangdo85/project-4-client)

**Comment by aishcann** [comment]
issue solved by running the terminal's suggested commands
