### ISSUE TITLE
getting a path error while trying to import a file

### ISSUE THREAD

**Issue by Mahider-Mengiste** [sei-ec-remote/project-4-issues#99]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I am trying to import ShowNewCommentModal from the comments directory but I am getting module not found, can't resolve this module, Although the module is inside the comments directory

### Post any code you think might be relevant (one fenced block per file)
```
import LoadingScreen from '../shared/LoadingScreen'
import { getOneRecipe, updateRecipe, removeRecipe} from '../../api/recipes'
import messages from '../shared/AutoDismissAlert/messages'
import EditRecipeModal from './EditRecipeModal'
import NewCommentModal from '../comments/NewCommentModal'
import ShowComment from '../comments/'
import deleteComment from '../../api/comments'

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

Module not found: Can't resolve '../comments/NewCommentModal' in '/Users/mahideryoseph/sei/projects/project-4-recipe-app/Recipe-app-client/Recipe-app-client/src/components/recipes'

### What is your best guess as to the source of the problem?
My best guess is there is an error in the path. i have also tested it by copying and pasting the path. 
Here is the path of the file that i want to import: /Users/mahideryoseph/sei/projects/project-4-recipe-app/Recipe-app-client/Recipe-app-client/src/components/comments /ShowComment.js

- in here there is a space between comments and showcomment.js (comments /ShowComment.js). 

### What things have you already tried to solve the problem?
I have tried to rename the showComment.js thinking that was what is causing the space it didn't work. 

**Paste a link to your repository here**

**Comment by timmshinbone** [comment]
You should not be working on react if your API isn't done. Also, we haven't had a 1:1 to even approve your project yet. Check slack.
